export interface CuratedStation {
  name: string;
  searchTerms: string[];
}

export const CURATED_STATIONS: Record<string, CuratedStation[]> = {
  IN: [
    { name: 'Radio Mirchi', searchTerms: ['radio mirchi', 'mirchi 98.3'] },
    { name: 'Red FM', searchTerms: ['red fm', '93.5 red'] },
    { name: 'Radio City', searchTerms: ['radio city', '91.1 fm'] },
    { name: 'Big FM', searchTerms: ['big fm', '92.7 big'] },
    { name: 'Fever FM', searchTerms: ['fever fm', 'fever 104'] },
    { name: 'All India Radio', searchTerms: ['all india radio', 'air', 'akashvani'] },
    { name: 'Vividh Bharati', searchTerms: ['vividh bharati'] },
    { name: 'Radio One', searchTerms: ['radio one 94.3'] },
    { name: 'AIR FM Gold', searchTerms: ['air fm gold', 'fm gold'] },
    { name: 'AIR FM Rainbow', searchTerms: ['air rainbow', 'fm rainbow'] },
    { name: 'Radio Nasha', searchTerms: ['radio nasha'] },
    { name: 'Ishq FM', searchTerms: ['ishq fm'] },
    { name: 'Bollywood Radio', searchTerms: ['bollywood', 'hindi songs'] },
    { name: 'Punjabi Radio', searchTerms: ['punjabi radio', 'air punjabi'] },
    { name: 'Tamil FM', searchTerms: ['tamil fm', 'suryan fm'] },
    { name: 'Telugu Radio', searchTerms: ['telugu radio', 'radio telugu'] },
    { name: 'Malayalam Radio', searchTerms: ['malayalam radio', 'radio mango'] },
    { name: 'Kannada Radio', searchTerms: ['kannada radio', 'radio mirchi kannada'] },
    { name: 'Marathi Radio', searchTerms: ['marathi radio', 'radio mirchi marathi'] },
    { name: 'Bengali Radio', searchTerms: ['bengali radio', 'radio mirchi bangla'] },
  ],
  US: [
    { name: 'iHeartRadio', searchTerms: ['iheartradio', 'iheart'] },
    { name: 'NPR', searchTerms: ['npr', 'national public radio'] },
    { name: 'Kiss FM', searchTerms: ['kiss fm', 'kiis fm'] },
    { name: 'Hot 97', searchTerms: ['hot 97', 'hot97'] },
    { name: 'Power 105', searchTerms: ['power 105'] },
    { name: 'Z100', searchTerms: ['z100', 'whtz'] },
    { name: 'KEXP', searchTerms: ['kexp'] },
    { name: 'WNYC', searchTerms: ['wnyc'] },
    { name: 'KROQ', searchTerms: ['kroq'] },
    { name: 'KCRW', searchTerms: ['kcrw'] },
    { name: 'SiriusXM Hits', searchTerms: ['siriusxm', 'sirius hits'] },
    { name: 'Classic Rock', searchTerms: ['classic rock', 'rock radio'] },
    { name: 'Country Music', searchTerms: ['country radio', 'country music'] },
    { name: 'Hip Hop', searchTerms: ['hip hop radio', 'rap radio'] },
    { name: 'Jazz FM', searchTerms: ['jazz fm', 'smooth jazz'] },
    { name: 'Classical Radio', searchTerms: ['classical radio', 'wqxr'] },
    { name: 'ESPN Radio', searchTerms: ['espn radio'] },
    { name: 'CBS Radio', searchTerms: ['cbs radio'] },
    { name: 'Bloomberg Radio', searchTerms: ['bloomberg radio'] },
    { name: 'BBC World Service', searchTerms: ['bbc world service'] },
  ],
  GB: [
    { name: 'BBC Radio 1', searchTerms: ['bbc radio 1'] },
    { name: 'BBC Radio 2', searchTerms: ['bbc radio 2'] },
    { name: 'BBC Radio 3', searchTerms: ['bbc radio 3'] },
    { name: 'BBC Radio 4', searchTerms: ['bbc radio 4'] },
    { name: 'BBC Radio 5', searchTerms: ['bbc radio 5 live'] },
    { name: 'BBC Radio 6 Music', searchTerms: ['bbc 6 music', 'bbc radio 6'] },
    { name: 'Capital FM', searchTerms: ['capital fm', 'capital radio'] },
    { name: 'Heart FM', searchTerms: ['heart fm', 'heart radio'] },
    { name: 'Kiss FM UK', searchTerms: ['kiss fm uk', 'kiss fresh'] },
    { name: 'Classic FM', searchTerms: ['classic fm'] },
    { name: 'Absolute Radio', searchTerms: ['absolute radio'] },
    { name: 'LBC', searchTerms: ['lbc radio', 'lbc 97.3'] },
    { name: 'talkSPORT', searchTerms: ['talksport'] },
    { name: 'Smooth Radio', searchTerms: ['smooth radio'] },
    { name: 'Radio X', searchTerms: ['radio x'] },
    { name: 'Magic FM', searchTerms: ['magic fm', 'magic radio'] },
    { name: 'Virgin Radio', searchTerms: ['virgin radio uk'] },
    { name: 'Planet Rock', searchTerms: ['planet rock'] },
    { name: 'Jazz FM UK', searchTerms: ['jazz fm uk'] },
    { name: 'Scala Radio', searchTerms: ['scala radio'] },
  ],
  DE: [
    { name: 'Bayern 3', searchTerms: ['bayern 3', 'br3'] },
    { name: 'SWR3', searchTerms: ['swr3', 'swr 3'] },
    { name: 'WDR 2', searchTerms: ['wdr 2', 'wdr2'] },
    { name: '1Live', searchTerms: ['1live', 'einslive'] },
    { name: 'NDR 2', searchTerms: ['ndr 2', 'ndr2'] },
    { name: 'Antenne Bayern', searchTerms: ['antenne bayern'] },
    { name: 'Radio Hamburg', searchTerms: ['radio hamburg'] },
    { name: 'Radio FFH', searchTerms: ['radio ffh', 'ffh'] },
    { name: 'HR3', searchTerms: ['hr3', 'hr 3'] },
    { name: 'MDR Jump', searchTerms: ['mdr jump'] },
    { name: 'Deutschlandfunk', searchTerms: ['deutschlandfunk'] },
    { name: 'Radio Bob', searchTerms: ['radio bob'] },
    { name: 'Klassik Radio', searchTerms: ['klassik radio'] },
    { name: 'Sunshine Live', searchTerms: ['sunshine live'] },
    { name: 'bigFM', searchTerms: ['bigfm', 'big fm germany'] },
    { name: 'Energy Berlin', searchTerms: ['energy berlin'] },
    { name: 'RTL Radio', searchTerms: ['rtl radio'] },
    { name: 'Rock Antenne', searchTerms: ['rock antenne'] },
    { name: 'Radio 7', searchTerms: ['radio 7'] },
    { name: 'RPR1', searchTerms: ['rpr1'] },
  ],
  FR: [
    { name: 'NRJ', searchTerms: ['nrj', 'nrj france'] },
    { name: 'RTL', searchTerms: ['rtl france', 'rtl radio'] },
    { name: 'Europe 1', searchTerms: ['europe 1'] },
    { name: 'France Inter', searchTerms: ['france inter'] },
    { name: 'France Info', searchTerms: ['france info', 'franceinfo'] },
    { name: 'France Culture', searchTerms: ['france culture'] },
    { name: 'France Musique', searchTerms: ['france musique'] },
    { name: 'RFM', searchTerms: ['rfm france'] },
    { name: 'Skyrock', searchTerms: ['skyrock'] },
    { name: 'Fun Radio', searchTerms: ['fun radio'] },
    { name: 'Virgin Radio France', searchTerms: ['virgin radio france'] },
    { name: 'Nostalgie', searchTerms: ['nostalgie france'] },
    { name: 'Cherie FM', searchTerms: ['cherie fm'] },
    { name: 'RMC', searchTerms: ['rmc radio'] },
    { name: 'RTL2', searchTerms: ['rtl2 france'] },
    { name: 'Radio Nova', searchTerms: ['radio nova'] },
    { name: 'FIP', searchTerms: ['fip radio'] },
    { name: 'Mouv', searchTerms: ['mouv radio'] },
    { name: 'Radio Classique', searchTerms: ['radio classique'] },
    { name: 'TSF Jazz', searchTerms: ['tsf jazz'] },
  ],
  JP: [
    { name: 'NHK Radio', searchTerms: ['nhk radio', 'nhk world'] },
    { name: 'J-Wave', searchTerms: ['j-wave', 'jwave'] },
    { name: 'Tokyo FM', searchTerms: ['tokyo fm'] },
    { name: 'InterFM', searchTerms: ['interfm', 'inter fm'] },
    { name: 'Nippon Broadcasting', searchTerms: ['nippon broadcasting'] },
    { name: 'TBS Radio', searchTerms: ['tbs radio'] },
    { name: 'FM Yokohama', searchTerms: ['fm yokohama'] },
    { name: 'Bay FM', searchTerms: ['bay fm'] },
    { name: 'NACK5', searchTerms: ['nack5'] },
    { name: 'FM802', searchTerms: ['fm802'] },
    { name: 'ZIP-FM', searchTerms: ['zip-fm', 'zipfm'] },
    { name: 'Cross FM', searchTerms: ['cross fm'] },
    { name: 'FM North Wave', searchTerms: ['fm north wave'] },
    { name: 'Alpha Station', searchTerms: ['alpha station'] },
    { name: 'Radio Nippon', searchTerms: ['radio nippon'] },
    { name: 'J-Pop Radio', searchTerms: ['j-pop', 'jpop radio'] },
    { name: 'Anime Radio', searchTerms: ['anime radio'] },
    { name: 'Asia Dream', searchTerms: ['asia dream radio'] },
    { name: 'Radio Neo', searchTerms: ['radio neo'] },
    { name: 'FM Aichi', searchTerms: ['fm aichi'] },
  ],
  BR: [
    { name: 'Jovem Pan', searchTerms: ['jovem pan'] },
    { name: 'Band FM', searchTerms: ['band fm', 'radio bandeirantes'] },
    { name: 'Mix FM', searchTerms: ['mix fm brasil'] },
    { name: 'Globo FM', searchTerms: ['globo fm', 'radio globo'] },
    { name: 'Transamérica', searchTerms: ['transamerica'] },
    { name: 'Nativa FM', searchTerms: ['nativa fm'] },
    { name: 'Antena 1', searchTerms: ['antena 1'] },
    { name: 'Kiss FM Brasil', searchTerms: ['kiss fm brasil'] },
    { name: 'Alpha FM', searchTerms: ['alpha fm brasil'] },
    { name: 'CBN', searchTerms: ['cbn radio'] },
    { name: 'BandNews FM', searchTerms: ['bandnews fm'] },
    { name: 'Eldorado FM', searchTerms: ['eldorado fm'] },
    { name: 'Cidade FM', searchTerms: ['cidade fm'] },
    { name: 'Tupi FM', searchTerms: ['tupi fm'] },
    { name: 'Nova Brasil FM', searchTerms: ['nova brasil'] },
    { name: 'Energia 97 FM', searchTerms: ['energia 97'] },
    { name: 'Gazeta FM', searchTerms: ['gazeta fm'] },
    { name: 'Metropolitana FM', searchTerms: ['metropolitana fm'] },
    { name: 'Rádio Disney', searchTerms: ['radio disney brasil'] },
    { name: 'Rede Aleluia', searchTerms: ['rede aleluia'] },
  ],
  AU: [
    { name: 'Triple J', searchTerms: ['triple j', 'abc triple j'] },
    { name: 'ABC Radio', searchTerms: ['abc radio', 'abc news radio'] },
    { name: 'KIIS FM', searchTerms: ['kiis fm', 'kiis 106.5'] },
    { name: 'Nova FM', searchTerms: ['nova fm', 'nova 96.9'] },
    { name: 'Smooth FM', searchTerms: ['smooth fm australia'] },
    { name: '2GB', searchTerms: ['2gb', '2gb sydney'] },
    { name: '3AW', searchTerms: ['3aw', '3aw melbourne'] },
    { name: 'Triple M', searchTerms: ['triple m'] },
    { name: 'Mix FM', searchTerms: ['mix fm australia'] },
    { name: 'Gold FM', searchTerms: ['gold fm australia'] },
    { name: 'Hit Network', searchTerms: ['hit network', 'hit fm'] },
    { name: 'Fox FM', searchTerms: ['fox fm'] },
    { name: 'WSFM', searchTerms: ['wsfm'] },
    { name: 'Edge Radio', searchTerms: ['edge radio'] },
    { name: 'FBi Radio', searchTerms: ['fbi radio'] },
    { name: 'Double J', searchTerms: ['double j'] },
    { name: 'RN', searchTerms: ['radio national', 'abc rn'] },
    { name: 'Classic FM Australia', searchTerms: ['abc classic'] },
    { name: 'SBS Radio', searchTerms: ['sbs radio'] },
    { name: 'JJJ Unearthed', searchTerms: ['unearthed'] },
  ],
  CA: [
    { name: 'CBC Radio One', searchTerms: ['cbc radio one', 'cbc radio'] },
    { name: 'CBC Music', searchTerms: ['cbc music', 'cbc radio 2'] },
    { name: 'Virgin Radio', searchTerms: ['virgin radio canada'] },
    { name: 'CHUM FM', searchTerms: ['chum fm'] },
    { name: 'Kiss 92.5', searchTerms: ['kiss 92.5', 'kiss fm toronto'] },
    { name: 'CFNY Edge', searchTerms: ['cfny', 'edge 102'] },
    { name: 'Q107', searchTerms: ['q107'] },
    { name: 'CFRB', searchTerms: ['cfrb', 'newstalk 1010'] },
    { name: 'CJAD', searchTerms: ['cjad'] },
    { name: 'CKOI', searchTerms: ['ckoi'] },
    { name: 'Rouge FM', searchTerms: ['rouge fm'] },
    { name: 'NRJ Canada', searchTerms: ['nrj canada'] },
    { name: 'The Beat', searchTerms: ['the beat 92.5'] },
    { name: 'CFOX', searchTerms: ['cfox'] },
    { name: 'The Peak', searchTerms: ['the peak vancouver'] },
    { name: 'CHEZ 106', searchTerms: ['chez 106'] },
    { name: 'Jack FM', searchTerms: ['jack fm canada'] },
    { name: 'Indie88', searchTerms: ['indie88'] },
    { name: 'boom 97.3', searchTerms: ['boom 97.3'] },
    { name: 'Classical 96.3 FM', searchTerms: ['classical 96.3'] },
  ],
  ES: [
    { name: 'Cadena SER', searchTerms: ['cadena ser'] },
    { name: 'Los 40', searchTerms: ['los 40', 'los cuarenta'] },
    { name: 'COPE', searchTerms: ['cope radio'] },
    { name: 'Onda Cero', searchTerms: ['onda cero'] },
    { name: 'RNE', searchTerms: ['rne', 'radio nacional'] },
    { name: 'Radio 3', searchTerms: ['radio 3 rne'] },
    { name: 'Cadena Dial', searchTerms: ['cadena dial'] },
    { name: 'Cadena 100', searchTerms: ['cadena 100'] },
    { name: 'Europa FM', searchTerms: ['europa fm spain'] },
    { name: 'Rock FM', searchTerms: ['rock fm spain'] },
    { name: 'Kiss FM Spain', searchTerms: ['kiss fm spain'] },
    { name: 'Máxima FM', searchTerms: ['maxima fm'] },
    { name: 'Melodía FM', searchTerms: ['melodia fm'] },
    { name: 'RAC1', searchTerms: ['rac1'] },
    { name: 'Catalunya Radio', searchTerms: ['catalunya radio'] },
    { name: 'esRadio', searchTerms: ['esradio'] },
    { name: 'Radio Marca', searchTerms: ['radio marca'] },
    { name: 'Hit FM', searchTerms: ['hit fm spain'] },
    { name: 'Flaixbac', searchTerms: ['flaixbac'] },
    { name: 'Radio Clásica', searchTerms: ['radio clasica rne'] },
  ],
  MX: [
    { name: 'Los 40 México', searchTerms: ['los 40 mexico'] },
    { name: 'Exa FM', searchTerms: ['exa fm'] },
    { name: 'La Mejor FM', searchTerms: ['la mejor fm'] },
    { name: 'Alfa Radio', searchTerms: ['alfa radio mexico'] },
    { name: 'Beat 100.9', searchTerms: ['beat 100.9'] },
    { name: 'Mix FM', searchTerms: ['mix fm mexico'] },
    { name: 'Radio Fórmula', searchTerms: ['radio formula'] },
    { name: 'W Radio', searchTerms: ['w radio mexico'] },
    { name: 'MVS Radio', searchTerms: ['mvs radio'] },
    { name: 'Radio Centro', searchTerms: ['radio centro'] },
    { name: 'Imagen Radio', searchTerms: ['imagen radio'] },
    { name: 'Radio UNAM', searchTerms: ['radio unam'] },
    { name: 'Horizonte', searchTerms: ['horizonte 107.9'] },
    { name: 'Reactor 105.7', searchTerms: ['reactor 105.7'] },
    { name: 'Ibero 90.9', searchTerms: ['ibero 90.9'] },
    { name: 'Rock 101', searchTerms: ['rock 101 mexico'] },
    { name: 'La Z', searchTerms: ['la z fm'] },
    { name: 'Ke Buena', searchTerms: ['ke buena'] },
    { name: 'Radio Disney México', searchTerms: ['radio disney mexico'] },
    { name: 'Universal Stereo', searchTerms: ['universal stereo'] },
  ],
};

export const getCountriesWithCuratedStations = (): string[] => {
  return Object.keys(CURATED_STATIONS);
};

export const getCuratedStationsForCountry = (countryCode: string): CuratedStation[] => {
  return CURATED_STATIONS[countryCode.toUpperCase()] || [];
};
