export interface CuratedRadioStation {
  id: string;
  name: string;
  streamUrl: string;
  website: string;
  country: string;
  countryCode: string;
  language: string;
  genre: string;
  bitrate: number;
  favicon: string;
}

export const CURATED_RADIO_STATIONS: CuratedRadioStation[] = [
  // India (IN)
  {
    id: "air-vividh-bharati",
    name: "All India Radio - Vividh Bharati",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio001/playlist.m3u8",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Music",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "air-fm-rainbow",
    name: "All India Radio - FM Rainbow",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio002/playlist.m3u8",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Contemporary, Pop",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "air-fm-gold",
    name: "All India Radio - FM Gold",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio003/playlist.m3u8",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Golden Hits, Retro",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "air-raagam",
    name: "All India Radio - Raagam",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio004/playlist.m3u8",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Classical, Indian Classical",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "radio-mirchi-mumbai",
    name: "Radio Mirchi 98.3 FM",
    streamUrl: "https://radioindia.net/radio/mirchi98/icecast.audio",
    website: "https://mirchi.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Pop",
    bitrate: 128,
    favicon: "https://mirchi.in/favicon.ico",
  },
  {
    id: "radio-city-mumbai",
    name: "Radio City 91.1 FM",
    streamUrl: "https://prclive1.listenon.in/Hindi",
    website: "https://www.radiocity.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Music",
    bitrate: 128,
    favicon: "https://www.radiocity.in/favicon.ico",
  },
  {
    id: "red-fm-935",
    name: "Red FM 93.5",
    streamUrl: "https://prclive1.listenon.in/redfm",
    website: "https://www.redfmindia.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Pop",
    bitrate: 128,
    favicon: "https://www.redfmindia.in/favicon.ico",
  },
  {
    id: "big-fm-927",
    name: "Big FM 92.7",
    streamUrl: "https://prclive1.listenon.in/bigfm",
    website: "https://bigfmindia.com/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Hits",
    bitrate: 128,
    favicon: "https://bigfmindia.com/favicon.ico",
  },
  {
    id: "fever-fm-104",
    name: "Fever FM 104",
    streamUrl: "https://prclive1.listenon.in/fever",
    website: "https://www.fever.fm/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Contemporary, Pop",
    bitrate: 128,
    favicon: "https://www.fever.fm/favicon.ico",
  },
  {
    id: "radio-one-943",
    name: "Radio One 94.3 FM",
    streamUrl: "https://prclive1.listenon.in/radioone",
    website: "https://www.radioone.fm/",
    country: "India",
    countryCode: "IN",
    language: "English",
    genre: "English, Urban",
    bitrate: 128,
    favicon: "https://www.radioone.fm/favicon.ico",
  },
  {
    id: "suryan-fm-tamil",
    name: "Suryan FM",
    streamUrl: "https://stream.zeno.fm/xuzpqrp6fahvv",
    website: "https://www.sunnetwork.in/suryanfm/",
    country: "India",
    countryCode: "IN",
    language: "Tamil",
    genre: "Tamil, Music",
    bitrate: 128,
    favicon: "https://www.sunnetwork.in/favicon.ico",
  },
  {
    id: "club-fm-kerala",
    name: "Club FM 94.3",
    streamUrl: "https://stream.zeno.fm/6zzh9qzq9zzuv",
    website: "https://www.clubfm.in/",
    country: "India",
    countryCode: "IN",
    language: "Malayalam",
    genre: "Malayalam, Music",
    bitrate: 128,
    favicon: "https://www.clubfm.in/favicon.ico",
  },
  {
    id: "radio-mango-kerala",
    name: "Radio Mango",
    streamUrl: "https://stream.zeno.fm/6zzh9qzq9zzuv",
    website: "https://www.radiomango.fm/",
    country: "India",
    countryCode: "IN",
    language: "Malayalam",
    genre: "Malayalam, Music",
    bitrate: 128,
    favicon: "https://www.radiomango.fm/favicon.ico",
  },

  // United States (US)
  {
    id: "kexp-seattle",
    name: "KEXP 90.3 FM Seattle",
    streamUrl: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3",
    website: "https://www.kexp.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Alternative, Indie",
    bitrate: 128,
    favicon: "https://www.kexp.org/favicon.ico",
  },
  {
    id: "wfmu-jersey",
    name: "WFMU",
    streamUrl: "https://stream0.wfmu.org/freeform-128k",
    website: "https://wfmu.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Freeform, Eclectic",
    bitrate: 128,
    favicon: "https://wfmu.org/favicon.ico",
  },
  {
    id: "kcrw-la",
    name: "KCRW Los Angeles",
    streamUrl: "https://kcrw.streamguys1.com/kcrw_192k_mp3_on_air",
    website: "https://www.kcrw.com/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Eclectic, Alternative",
    bitrate: 192,
    favicon: "https://www.kcrw.com/favicon.ico",
  },
  {
    id: "wxpn-philly",
    name: "WXPN Philadelphia",
    streamUrl: "https://wxpn-ice.streamguys1.com/xpn-mp3-hi",
    website: "https://xpn.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "AAA, Americana",
    bitrate: 128,
    favicon: "https://xpn.org/favicon.ico",
  },
  {
    id: "npr-music",
    name: "NPR Music",
    streamUrl: "https://npr-ice.streamguys1.com/live.mp3",
    website: "https://www.npr.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "News, Music",
    bitrate: 128,
    favicon: "https://www.npr.org/favicon.ico",
  },
  {
    id: "wnyc-ny",
    name: "WNYC New York",
    streamUrl: "https://fm939.wnyc.org/wnycfm",
    website: "https://www.wnyc.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Public Radio, Talk",
    bitrate: 128,
    favicon: "https://www.wnyc.org/favicon.ico",
  },
  {
    id: "hot97-ny",
    name: "Hot 97 New York",
    streamUrl: "https://stream.revma.ihrhls.com/zc1465",
    website: "https://www.hot97.com/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Hip Hop, R&B",
    bitrate: 128,
    favicon: "https://www.hot97.com/favicon.ico",
  },
  {
    id: "kiis-fm-la",
    name: "KIIS-FM 102.7 Los Angeles",
    streamUrl: "https://stream.revma.ihrhls.com/zc1481",
    website: "https://www.iheart.com/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Top 40, Pop",
    bitrate: 128,
    favicon: "https://www.iheart.com/favicon.ico",
  },
  {
    id: "kroq-la",
    name: "KROQ Los Angeles",
    streamUrl: "https://stream.revma.ihrhls.com/zc1485",
    website: "https://kroq.radio.com/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Alternative Rock",
    bitrate: 128,
    favicon: "https://kroq.radio.com/favicon.ico",
  },
  {
    id: "wamu-dc",
    name: "WAMU 88.5 Washington DC",
    streamUrl: "https://hd1.wamu.org/",
    website: "https://www.wamu.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "NPR, Public Radio",
    bitrate: 128,
    favicon: "https://www.wamu.org/favicon.ico",
  },

  // United Kingdom (GB)
  {
    id: "bbc-radio-1",
    name: "BBC Radio 1",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Pop, Contemporary",
    bitrate: 320,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "bbc-radio-2",
    name: "BBC Radio 2",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Adult Contemporary",
    bitrate: 320,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "bbc-radio-3",
    name: "BBC Radio 3",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_three",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Classical, Jazz",
    bitrate: 320,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "capital-fm-uk",
    name: "Capital FM",
    streamUrl: "https://media-ice.musicradio.com/CapitalMP3",
    website: "https://www.globalplayer.com/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://www.capitalfm.com/favicon.ico",
  },
  {
    id: "kiss-fm-uk",
    name: "Kiss FM UK",
    streamUrl: "https://media-ice.musicradio.com/KissMP3",
    website: "https://www.globalplayer.com/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Dance, Electronic",
    bitrate: 128,
    favicon: "https://www.kissfm.com/favicon.ico",
  },
  {
    id: "absolute-radio-uk",
    name: "Absolute Radio",
    streamUrl: "https://ais-sa3.cdnstream1.com/2569_128.mp3",
    website: "https://absoluteradio.co.uk/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Rock, Alternative",
    bitrate: 128,
    favicon: "https://absoluteradio.co.uk/favicon.ico",
  },

  // Japan (JP)
  {
    id: "j-wave-tokyo",
    name: "J-WAVE 81.3 FM Tokyo",
    streamUrl: "https://radiko.jp/",
    website: "https://www.j-wave.co.jp/",
    country: "Japan",
    countryCode: "JP",
    language: "Japanese",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.j-wave.co.jp/favicon.ico",
  },
  {
    id: "nhk-fm-japan",
    name: "NHK-FM",
    streamUrl: "https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/domestic/263942/live.m3u8",
    website: "https://www.nhk.or.jp/radio/",
    country: "Japan",
    countryCode: "JP",
    language: "Japanese",
    genre: "Classical, Music",
    bitrate: 128,
    favicon: "https://www.nhk.or.jp/favicon.ico",
  },
  {
    id: "interfm-tokyo",
    name: "InterFM897 Tokyo",
    streamUrl: "https://musicbird.leanstream.co/JCB069-MP3",
    website: "https://www.interfm.co.jp/",
    country: "Japan",
    countryCode: "JP",
    language: "Japanese, English",
    genre: "International, Pop",
    bitrate: 128,
    favicon: "https://www.interfm.co.jp/favicon.ico",
  },

  // Germany (DE)
  {
    id: "1live-wdr",
    name: "1LIVE WDR",
    streamUrl: "https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3",
    website: "https://www1.wdr.de/radio/1live/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www1.wdr.de/favicon.ico",
  },
  {
    id: "antenne-bayern",
    name: "Antenne Bayern",
    streamUrl: "https://stream.antenne.de/antenne",
    website: "https://www.antenne.de/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.antenne.de/favicon.ico",
  },
  {
    id: "ndr2-germany",
    name: "NDR 2",
    streamUrl: "https://icecast.ndr.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3",
    website: "https://www.ndr.de/ndr2/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Rock",
    bitrate: 128,
    favicon: "https://www.ndr.de/favicon.ico",
  },
  {
    id: "bayern3",
    name: "Bayern 3",
    streamUrl: "https://streams.br.de/bayern3_2.m3u",
    website: "https://www.br.de/radio/bayern3/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.br.de/favicon.ico",
  },
  {
    id: "dlf-kultur",
    name: "Deutschlandfunk Kultur",
    streamUrl: "https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3",
    website: "https://www.deutschlandfunkkultur.de/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Culture, Music",
    bitrate: 128,
    favicon: "https://www.deutschlandfunkkultur.de/favicon.ico",
  },

  // France (FR)
  {
    id: "france-inter",
    name: "France Inter",
    streamUrl: "https://icecast.radiofrance.fr/franceinter-midfi.mp3",
    website: "https://www.radiofrance.fr/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Talk, Music",
    bitrate: 128,
    favicon: "https://www.radiofrance.fr/favicon.ico",
  },
  {
    id: "nrj-france",
    name: "NRJ France",
    streamUrl: "https://scdn.nrjaudio.fm/fr/30001/mp3_128.mp3",
    website: "https://www.nrj.fr/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.nrj.fr/favicon.ico",
  },
  {
    id: "france-musique",
    name: "France Musique",
    streamUrl: "https://icecast.radiofrance.fr/francemusique-midfi.mp3",
    website: "https://www.radiofrance.fr/francemusique/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Classical, Jazz",
    bitrate: 128,
    favicon: "https://www.radiofrance.fr/favicon.ico",
  },
  {
    id: "fip-france",
    name: "FIP",
    streamUrl: "https://icecast.radiofrance.fr/fip-midfi.mp3",
    website: "https://www.radiofrance.fr/fip",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Eclectic, World",
    bitrate: 128,
    favicon: "https://www.radiofrance.fr/favicon.ico",
  },

  // Australia (AU)
  {
    id: "triple-j-abc",
    name: "triple j",
    streamUrl: "https://live-radio01.mediahubaustralia.com/2TJW/mp3/",
    website: "https://www.abc.net.au/triplej/",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    genre: "Alternative, Youth",
    bitrate: 128,
    favicon: "https://www.abc.net.au/favicon.ico",
  },
  {
    id: "abc-classic",
    name: "ABC Classic",
    streamUrl: "https://live-radio01.mediahubaustralia.com/CLYW/mp3/",
    website: "https://www.abc.net.au/classic/",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    genre: "Classical",
    bitrate: 128,
    favicon: "https://www.abc.net.au/favicon.ico",
  },
  {
    id: "kiis-1065-sydney",
    name: "KIIS 1065 Sydney",
    streamUrl: "https://21233.live.streamtheworld.com/KIIS1065.mp3",
    website: "https://www.kiis1065.com.au/",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://www.kiis1065.com.au/favicon.ico",
  },

  // Canada (CA)
  {
    id: "cbc-music",
    name: "CBC Music",
    streamUrl: "https://cbcliveradio-lh.akamaihd.net/i/CBCMUSIC_OTT@311823/master.m3u8",
    website: "https://www.cbc.ca/listen/live-radio",
    country: "Canada",
    countryCode: "CA",
    language: "English",
    genre: "Eclectic, Canadian",
    bitrate: 128,
    favicon: "https://www.cbc.ca/favicon.ico",
  },
  {
    id: "virgin-radio-toronto",
    name: "Virgin Radio Toronto",
    streamUrl: "https://18233.live.streamtheworld.com/CKFMFM.mp3",
    website: "https://www.iheartradio.ca/",
    country: "Canada",
    countryCode: "CA",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://www.iheartradio.ca/favicon.ico",
  },
  {
    id: "102-1-the-edge",
    name: "102.1 The Edge",
    streamUrl: "https://18393.live.streamtheworld.com/CFNYFM.mp3",
    website: "https://www.theedge.ca/",
    country: "Canada",
    countryCode: "CA",
    language: "English",
    genre: "Alternative Rock",
    bitrate: 128,
    favicon: "https://www.theedge.ca/favicon.ico",
  },

  // Brazil (BR)
  {
    id: "jovem-pan",
    name: "Jovem Pan FM",
    streamUrl: "https://stream.zeno.fm/7amqbfn6hfeuv",
    website: "https://jovempan.com.br/",
    country: "Brazil",
    countryCode: "BR",
    language: "Portuguese",
    genre: "Pop, News",
    bitrate: 128,
    favicon: "https://jovempan.com.br/favicon.ico",
  },
  {
    id: "radio-globo-br",
    name: "Rádio Globo",
    streamUrl: "https://stream.zeno.fm/qb0gx9b3qfquv",
    website: "https://globoplay.globo.com/radio/",
    country: "Brazil",
    countryCode: "BR",
    language: "Portuguese",
    genre: "Pop, Talk",
    bitrate: 128,
    favicon: "https://globoplay.globo.com/favicon.ico",
  },
  {
    id: "transamerica-br",
    name: "Rádio Transamérica",
    streamUrl: "https://stream.zeno.fm/dmxg0b6n5zzuv",
    website: "https://www.transamerica.com.br/",
    country: "Brazil",
    countryCode: "BR",
    language: "Portuguese",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.transamerica.com.br/favicon.ico",
  },

  // Mexico (MX)
  {
    id: "los40-mexico",
    name: "Los 40 México",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_MEXICOAAC.aac",
    website: "https://los40.com.mx/",
    country: "Mexico",
    countryCode: "MX",
    language: "Spanish",
    genre: "Pop, Latin",
    bitrate: 128,
    favicon: "https://los40.com.mx/favicon.ico",
  },
  {
    id: "exa-fm-mx",
    name: "Exa FM México",
    streamUrl: "https://stream.zeno.fm/n6b5yh5y8ptvv",
    website: "https://www.exafm.com/",
    country: "Mexico",
    countryCode: "MX",
    language: "Spanish",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.exafm.com/favicon.ico",
  },

  // Spain (ES)
  {
    id: "los40-spain",
    name: "Los 40 España",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40AAC.aac",
    website: "https://los40.com/",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://los40.com/favicon.ico",
  },
  {
    id: "cadena-ser",
    name: "Cadena SER",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASERAAC.aac",
    website: "https://cadenaser.com/",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    genre: "Talk, News",
    bitrate: 128,
    favicon: "https://cadenaser.com/favicon.ico",
  },
  {
    id: "cadena-100",
    name: "Cadena 100",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENA100AAC.aac",
    website: "https://www.cadena100.es/",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.cadena100.es/favicon.ico",
  },

  // Italy (IT)
  {
    id: "radio-italia",
    name: "Radio Italia",
    streamUrl: "https://icecast.radioitalia.it/radioitaliaonly.mp3",
    website: "https://www.radioitalia.it/",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    genre: "Italian Pop",
    bitrate: 128,
    favicon: "https://www.radioitalia.it/favicon.ico",
  },
  {
    id: "radio-deejay",
    name: "Radio Deejay",
    streamUrl: "https://streamcdnb3-4c4b867c89244861ac216426883d1ad0.msvdn.net/webradio/deejay.aac",
    website: "https://www.radio.deejay.it/",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.deejay.it/favicon.ico",
  },
  {
    id: "rtl-1025",
    name: "RTL 102.5",
    streamUrl: "https://streamingv2.shoutcast.com/rtl-1025",
    website: "https://www.rtl.it/",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.rtl.it/favicon.ico",
  },

  // Netherlands (NL)
  {
    id: "radio-538-nl",
    name: "Radio 538",
    streamUrl: "https://21253.live.streamtheworld.com/RADIO538.mp3",
    website: "https://www.radio538.nl/",
    country: "Netherlands",
    countryCode: "NL",
    language: "Dutch",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.radio538.nl/favicon.ico",
  },
  {
    id: "npo-radio-2",
    name: "NPO Radio 2",
    streamUrl: "https://icecast.omroep.nl/radio2-bb-mp3",
    website: "https://www.nporadio2.nl/",
    country: "Netherlands",
    countryCode: "NL",
    language: "Dutch",
    genre: "Pop, Dutch",
    bitrate: 128,
    favicon: "https://www.nporadio2.nl/favicon.ico",
  },
  {
    id: "qmusic-nl",
    name: "Qmusic NL",
    streamUrl: "https://21253.live.streamtheworld.com/QMUSIC.mp3",
    website: "https://www.qmusic.nl/",
    country: "Netherlands",
    countryCode: "NL",
    language: "Dutch",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.qmusic.nl/favicon.ico",
  },

  // Sweden (SE)
  {
    id: "sr-p3",
    name: "SR P3",
    streamUrl: "https://sverigesradio.se/topsy/direkt/164-hi-mp3.m3u",
    website: "https://sverigesradio.se/p3",
    country: "Sweden",
    countryCode: "SE",
    language: "Swedish",
    genre: "Pop, Youth",
    bitrate: 192,
    favicon: "https://sverigesradio.se/favicon.ico",
  },
  {
    id: "nrj-sweden",
    name: "NRJ Sweden",
    streamUrl: "https://icecast.nrj.se/nrj_se",
    website: "https://www.nrj.se/",
    country: "Sweden",
    countryCode: "SE",
    language: "Swedish",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.nrj.se/favicon.ico",
  },

  // Belgium (BE)
  {
    id: "studio-brussel",
    name: "Studio Brussel",
    streamUrl: "https://icecast.vrtcdn.be/stubru-high.mp3",
    website: "https://www.vrt.be/",
    country: "Belgium",
    countryCode: "BE",
    language: "Dutch",
    genre: "Alternative, Youth",
    bitrate: 320,
    favicon: "https://www.stubru.be/favicon.ico",
  },
  {
    id: "qmusic-belgium",
    name: "Qmusic Belgium",
    streamUrl: "https://icecast-qmusic.dpgmedia.net/qmusic.mp3",
    website: "https://www.qmusic.be/",
    country: "Belgium",
    countryCode: "BE",
    language: "Dutch",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.qmusic.be/favicon.ico",
  },

  // Russia (RU)
  {
    id: "europa-plus",
    name: "Europa Plus",
    streamUrl: "https://ep128.hostingradio.ru:8030/ep128",
    website: "https://www.europaplus.ru/",
    country: "Russia",
    countryCode: "RU",
    language: "Russian",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.europaplus.ru/favicon.ico",
  },
  {
    id: "russkoe-radio",
    name: "Russkoe Radio",
    streamUrl: "https://rusradio.hostingradio.ru/rusradio128.mp3",
    website: "https://rusradio.ru/",
    country: "Russia",
    countryCode: "RU",
    language: "Russian",
    genre: "Russian Pop",
    bitrate: 128,
    favicon: "https://rusradio.ru/favicon.ico",
  },

  // South Korea (KR)
  {
    id: "kbs-cool-fm",
    name: "KBS Cool FM",
    streamUrl: "https://stream.kbs.co.kr/2coolmfm.m3u8",
    website: "https://world.kbs.co.kr/",
    country: "South Korea",
    countryCode: "KR",
    language: "Korean",
    genre: "K-Pop, Contemporary",
    bitrate: 128,
    favicon: "https://world.kbs.co.kr/favicon.ico",
  },
  {
    id: "mbc-fm4u",
    name: "MBC FM4U",
    streamUrl: "https://stream.imbc.com/fm4u_m3u8",
    website: "https://www.imbc.com/",
    country: "South Korea",
    countryCode: "KR",
    language: "Korean",
    genre: "K-Pop, Music",
    bitrate: 128,
    favicon: "https://www.imbc.com/favicon.ico",
  },

  // China (CN)
  {
    id: "cnr-music",
    name: "CNR Music Radio",
    streamUrl: "https://lhttp.qingting.fm/live/339/64k.mp3",
    website: "http://www.cnr.cn/",
    country: "China",
    countryCode: "CN",
    language: "Chinese",
    genre: "Pop, Music",
    bitrate: 64,
    favicon: "http://www.cnr.cn/favicon.ico",
  },
  {
    id: "cri-music",
    name: "China Radio International",
    streamUrl: "https://lhttp.qingting.fm/live/4908/64k.mp3",
    website: "http://english.cri.cn/",
    country: "China",
    countryCode: "CN",
    language: "Chinese, English",
    genre: "International",
    bitrate: 64,
    favicon: "http://english.cri.cn/favicon.ico",
  },

  // Argentina (AR)
  {
    id: "radio-mitre",
    name: "Radio Mitre",
    streamUrl: "https://live-radio01.mediahubaustralia.com/MITRE/aac/",
    website: "https://www.radiomitre.cienradios.com/",
    country: "Argentina",
    countryCode: "AR",
    language: "Spanish",
    genre: "Talk, News",
    bitrate: 128,
    favicon: "https://www.radiomitre.com.ar/favicon.ico",
  },
  {
    id: "la-100-ar",
    name: "La 100",
    streamUrl: "https://live-radio01.mediahubaustralia.com/LA100/aac/",
    website: "https://www.la100.com/",
    country: "Argentina",
    countryCode: "AR",
    language: "Spanish",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.la100.com/favicon.ico",
  },

  // Poland (PL)
  {
    id: "rmf-fm",
    name: "RMF FM",
    streamUrl: "https://rs6-krk2.rmfstream.pl/rmf_fm",
    website: "https://www.rmf.fm/",
    country: "Poland",
    countryCode: "PL",
    language: "Polish",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.rmf.fm/favicon.ico",
  },
  {
    id: "radio-zet",
    name: "Radio Zet",
    streamUrl: "https://n-4-1.dcs.redcdn.pl/sc/o2/Eurozet/live/audio.livx",
    website: "https://www.radiozet.pl/",
    country: "Poland",
    countryCode: "PL",
    language: "Polish",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.radiozet.pl/favicon.ico",
  },

  // Portugal (PT)
  {
    id: "rfm-portugal",
    name: "RFM",
    streamUrl: "https://21933.live.streamtheworld.com/RFMPORTUGAL.mp3",
    website: "https://www.rfm.pt/",
    country: "Portugal",
    countryCode: "PT",
    language: "Portuguese",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.rfm.pt/favicon.ico",
  },

  // Switzerland (CH)
  {
    id: "srf-3",
    name: "SRF 3",
    streamUrl: "https://stream.srg-ssr.ch/m/drs3/mp3_128",
    website: "https://www.srf.ch/",
    country: "Switzerland",
    countryCode: "CH",
    language: "German",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.srf.ch/favicon.ico",
  },

  // Norway (NO)
  {
    id: "nrk-p3",
    name: "NRK P3",
    streamUrl: "https://lyd.nrk.no/nrk_radio_p3_aac_h",
    website: "https://radio.nrk.no/",
    country: "Norway",
    countryCode: "NO",
    language: "Norwegian",
    genre: "Pop, Youth",
    bitrate: 192,
    favicon: "https://radio.nrk.no/favicon.ico",
  },

  // Denmark (DK)
  {
    id: "dr-p3",
    name: "DR P3",
    streamUrl: "https://live-icy.dr.dk/A/A05H.mp3",
    website: "https://www.dr.dk/",
    country: "Denmark",
    countryCode: "DK",
    language: "Danish",
    genre: "Pop, Youth",
    bitrate: 192,
    favicon: "https://www.dr.dk/favicon.ico",
  },

  // Finland (FI)
  {
    id: "ylex",
    name: "YleX",
    streamUrl: "https://icecast.live.yle.fi/radio/ylex.aac",
    website: "https://areena.yle.fi/",
    country: "Finland",
    countryCode: "FI",
    language: "Finnish",
    genre: "Pop, Alternative",
    bitrate: 128,
    favicon: "https://areena.yle.fi/favicon.ico",
  },

  // Greece (GR)
  {
    id: "era-hellas",
    name: "ERA Hellenic Broadcasting",
    streamUrl: "https://stream.radiojar.com/era-sport-aac",
    website: "https://www.hrad.gr/",
    country: "Greece",
    countryCode: "GR",
    language: "Greek",
    genre: "Greek Pop",
    bitrate: 128,
    favicon: "https://www.hrad.gr/favicon.ico",
  },

  // Turkey (TR)
  {
    id: "kral-fm",
    name: "Kral FM",
    streamUrl: "https://dygedge.radyotvonline.net/kralfm/playlist.m3u8",
    website: "https://www.kralmuzik.com.tr/",
    country: "Turkey",
    countryCode: "TR",
    language: "Turkish",
    genre: "Turkish Pop",
    bitrate: 128,
    favicon: "https://www.kralmuzik.com.tr/favicon.ico",
  },
  {
    id: "trt-radyo",
    name: "TRT Radyo",
    streamUrl: "https://trtradyo.mediatriple.net/trtradyo3.mp3",
    website: "https://www.trt.net.tr/",
    country: "Turkey",
    countryCode: "TR",
    language: "Turkish",
    genre: "Turkish Music",
    bitrate: 128,
    favicon: "https://www.trt.net.tr/favicon.ico",
  },

  // Israel (IL)
  {
    id: "galgalatz",
    name: "Galgalatz",
    streamUrl: "https://glzwizz.glz.co.il/glz.mp3",
    website: "https://glz.co.il/",
    country: "Israel",
    countryCode: "IL",
    language: "Hebrew",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://glz.co.il/favicon.ico",
  },

  // South Africa (ZA)
  {
    id: "metro-fm-za",
    name: "Metro FM",
    streamUrl: "https://icecast.vrt.be/metrofm-live.mp3",
    website: "https://www.metrofm.co.za/",
    country: "South Africa",
    countryCode: "ZA",
    language: "English",
    genre: "Urban, R&B",
    bitrate: 128,
    favicon: "https://www.metrofm.co.za/favicon.ico",
  },
  {
    id: "5fm-za",
    name: "5FM",
    streamUrl: "https://icecast.vrt.be/5fm-live.mp3",
    website: "https://www.5fm.co.za/",
    country: "South Africa",
    countryCode: "ZA",
    language: "English",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.5fm.co.za/favicon.ico",
  },

  // Nigeria (NG)
  {
    id: "cool-fm-lagos",
    name: "Cool FM Lagos",
    streamUrl: "https://stream.zeno.fm/xn4t9u6q3zzuv",
    website: "https://www.coolfm.ng/",
    country: "Nigeria",
    countryCode: "NG",
    language: "English",
    genre: "Pop, Afrobeats",
    bitrate: 128,
    favicon: "https://www.coolfm.ng/favicon.ico",
  },

  // Kenya (KE)
  {
    id: "homeboyz-radio",
    name: "Homeboyz Radio",
    streamUrl: "https://stream.zeno.fm/1a2bc3d4e5fghi",
    website: "https://www.homeboyzradio.co.ke/",
    country: "Kenya",
    countryCode: "KE",
    language: "English, Swahili",
    genre: "Urban, Hip Hop",
    bitrate: 128,
    favicon: "https://www.homeboyzradio.co.ke/favicon.ico",
  },

  // Egypt (EG)
  {
    id: "nogoum-fm",
    name: "Nogoum FM",
    streamUrl: "https://stream.radiojar.com/nogoum-fm",
    website: "https://nogoum.fm/",
    country: "Egypt",
    countryCode: "EG",
    language: "Arabic",
    genre: "Arabic Pop",
    bitrate: 128,
    favicon: "https://nogoum.fm/favicon.ico",
  },

  // UAE (AE)
  {
    id: "dubai-92",
    name: "Dubai 92",
    streamUrl: "https://stream.radiojar.com/dubai92.aac",
    website: "https://www.dubai92.com/",
    country: "UAE",
    countryCode: "AE",
    language: "English",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.dubai92.com/favicon.ico",
  },
  {
    id: "virgin-radio-dubai",
    name: "Virgin Radio Dubai",
    streamUrl: "https://stream.radiojar.com/virgin-radio-dubai.aac",
    website: "https://virginradiodubai.com/",
    country: "UAE",
    countryCode: "AE",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://virginradiodubai.com/favicon.ico",
  },

  // Indonesia (ID)
  {
    id: "prambors-fm",
    name: "Prambors FM",
    streamUrl: "https://streams.pfrn.co.id/prambors",
    website: "https://www.pramborsfm.com/",
    country: "Indonesia",
    countryCode: "ID",
    language: "Indonesian",
    genre: "Pop, Youth",
    bitrate: 128,
    favicon: "https://www.pramborsfm.com/favicon.ico",
  },
  {
    id: "rri-pro-2",
    name: "RRI Pro 2",
    streamUrl: "https://stream.rri.co.id/pro2jakarta",
    website: "https://rri.co.id/",
    country: "Indonesia",
    countryCode: "ID",
    language: "Indonesian",
    genre: "Pop, Music",
    bitrate: 128,
    favicon: "https://rri.co.id/favicon.ico",
  },

  // Thailand (TH)
  {
    id: "fat-radio",
    name: "Fat Radio",
    streamUrl: "https://stream.zeno.fm/dfn2y3h9n8zuv",
    website: "https://fatradio.fm/",
    country: "Thailand",
    countryCode: "TH",
    language: "Thai",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://fatradio.fm/favicon.ico",
  },

  // Philippines (PH)
  {
    id: "mor-philippines",
    name: "MOR Philippines",
    streamUrl: "https://stream.zeno.fm/xyzabc123456",
    website: "https://mor.abs-cbn.com/",
    country: "Philippines",
    countryCode: "PH",
    language: "Filipino, English",
    genre: "Pop, OPM",
    bitrate: 128,
    favicon: "https://mor.abs-cbn.com/favicon.ico",
  },

  // Vietnam (VN)
  {
    id: "vov-music",
    name: "Voice of Vietnam",
    streamUrl: "https://stream.vov.vn/vov1.mp3",
    website: "https://vov.vn/",
    country: "Vietnam",
    countryCode: "VN",
    language: "Vietnamese",
    genre: "Vietnamese Music",
    bitrate: 128,
    favicon: "https://vov.vn/favicon.ico",
  },

  // New Zealand (NZ)
  {
    id: "rnz-national",
    name: "RNZ National",
    streamUrl: "https://rnz-streaming.kerv.tech/RNZNational.mp3",
    website: "https://www.rnz.co.nz/",
    country: "New Zealand",
    countryCode: "NZ",
    language: "English",
    genre: "Talk, News",
    bitrate: 128,
    favicon: "https://www.rnz.co.nz/favicon.ico",
  },
  {
    id: "the-edge-nz",
    name: "The Edge NZ",
    streamUrl: "https://ais-nzme.streamguys1.com/nz_002/playlist.m3u8",
    website: "https://www.theedge.co.nz/",
    country: "New Zealand",
    countryCode: "NZ",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://www.theedge.co.nz/favicon.ico",
  },

  // Chile (CL)
  {
    id: "radio-cooperativa",
    name: "Radio Cooperativa",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/COOPERATIVAAAC.aac",
    website: "https://www.cooperativa.cl/",
    country: "Chile",
    countryCode: "CL",
    language: "Spanish",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://www.cooperativa.cl/favicon.ico",
  },

  // Colombia (CO)
  {
    id: "la-mega-co",
    name: "La Mega Colombia",
    streamUrl: "https://stream.zeno.fm/7hq4dxqx3zzuv",
    website: "https://www.lamega.com.co/",
    country: "Colombia",
    countryCode: "CO",
    language: "Spanish",
    genre: "Pop, Latin",
    bitrate: 128,
    favicon: "https://www.lamega.com.co/favicon.ico",
  },
  {
    id: "caracol-radio",
    name: "Caracol Radio",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/CARACOL_COLOMBIAAAC.aac",
    website: "https://caracol.com.co/",
    country: "Colombia",
    countryCode: "CO",
    language: "Spanish",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://caracol.com.co/favicon.ico",
  },

  // Peru (PE)
  {
    id: "radio-capital-pe",
    name: "Radio Capital",
    streamUrl: "https://stream.zeno.fm/capital-peru",
    website: "https://www.radiocapitalperu.com.pe/",
    country: "Peru",
    countryCode: "PE",
    language: "Spanish",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://www.radiocapitalperu.com.pe/favicon.ico",
  },

  // Czechia (CZ)
  {
    id: "radiozurnal",
    name: "Radiožurnál",
    streamUrl: "https://icecast6.play.cz/cro1-128.mp3",
    website: "https://www.rozhlas.cz/",
    country: "Czechia",
    countryCode: "CZ",
    language: "Czech",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://www.rozhlas.cz/favicon.ico",
  },

  // Hungary (HU)
  {
    id: "radio-1-hu",
    name: "Rádió 1",
    streamUrl: "https://stream.radio1.hu/high.mp3",
    website: "https://www.radio1.hu/",
    country: "Hungary",
    countryCode: "HU",
    language: "Hungarian",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.radio1.hu/favicon.ico",
  },

  // Romania (RO)
  {
    id: "radio-zu",
    name: "Radio ZU",
    streamUrl: "https://live4.radiozu.ro:8443/radiozu.aacp",
    website: "https://www.radiozu.ro/",
    country: "Romania",
    countryCode: "RO",
    language: "Romanian",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.radiozu.ro/favicon.ico",
  },

  // Slovakia (SK)
  {
    id: "radio-expres",
    name: "Rádio Expres",
    streamUrl: "https://icecast.stv.livebox.sk/radioexpres_128.mp3",
    website: "https://www.expres.sk/",
    country: "Slovakia",
    countryCode: "SK",
    language: "Slovak",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.expres.sk/favicon.ico",
  },

  // Slovenia (SI)
  {
    id: "val-202",
    name: "Val 202",
    streamUrl: "https://mp3.rtvslo.si/val202",
    website: "https://www.rtvslo.si/",
    country: "Slovenia",
    countryCode: "SI",
    language: "Slovenian",
    genre: "Pop, Youth",
    bitrate: 128,
    favicon: "https://www.rtvslo.si/favicon.ico",
  },

  // Ireland (IE)
  {
    id: "rte-2fm",
    name: "RTÉ 2FM",
    streamUrl: "https://icecast2.rte.ie/radio2fm",
    website: "https://www.rte.ie/",
    country: "Ireland",
    countryCode: "IE",
    language: "English",
    genre: "Pop, Youth",
    bitrate: 160,
    favicon: "https://www.rte.ie/favicon.ico",
  },

  // Iceland (IS)
  {
    id: "ruv-ras-2",
    name: "RÚV Rás 2",
    streamUrl: "https://icecast.ruv.is/ras2/128.mp3",
    website: "https://www.ruv.is/",
    country: "Iceland",
    countryCode: "IS",
    language: "Icelandic",
    genre: "Pop, Music",
    bitrate: 128,
    favicon: "https://www.ruv.is/favicon.ico",
  },

  // Luxembourg (LU)
  {
    id: "rtl-luxembourg",
    name: "RTL Radio Luxembourg",
    streamUrl: "https://rtl-radio-rtl.ice.infomaniak.ch/rtl-radio-rtl.mp3",
    website: "https://www.rtl.lu/",
    country: "Luxembourg",
    countryCode: "LU",
    language: "French, German",
    genre: "Pop, Talk",
    bitrate: 128,
    favicon: "https://www.rtl.lu/favicon.ico",
  },

  // Lithuania (LT)
  {
    id: "lrt-radijas",
    name: "LRT Radijas",
    streamUrl: "https://radijas.lrt.lt/stream",
    website: "https://www.lrt.lt/",
    country: "Lithuania",
    countryCode: "LT",
    language: "Lithuanian",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://www.lrt.lt/favicon.ico",
  },

  // Latvia (LV)
  {
    id: "latvijas-radio",
    name: "Latvijas Radio",
    streamUrl: "https://lr1mp3hq.latvijasradio.lv/lr1mp3.mp3",
    website: "https://www.latvijasradio.lv/",
    country: "Latvia",
    countryCode: "LV",
    language: "Latvian",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://www.latvijasradio.lv/favicon.ico",
  },

  // Estonia (EE)
  {
    id: "vikerraadio",
    name: "Vikerraadio",
    streamUrl: "https://icecast.err.ee/vikerraadio.mp3",
    website: "https://vikerraadio.err.ee/",
    country: "Estonia",
    countryCode: "EE",
    language: "Estonian",
    genre: "Talk, Music",
    bitrate: 192,
    favicon: "https://vikerraadio.err.ee/favicon.ico",
  },

  // Bangladesh (BD)
  {
    id: "radio-foorti",
    name: "Radio Foorti",
    streamUrl: "https://stream.zeno.fm/4vhybx9q3zzuv",
    website: "https://www.radiofoorti.com/",
    country: "Bangladesh",
    countryCode: "BD",
    language: "Bengali",
    genre: "Pop, Bangla",
    bitrate: 128,
    favicon: "https://www.radiofoorti.com/favicon.ico",
  },
  {
    id: "bangladesh-betar",
    name: "Bangladesh Betar",
    streamUrl: "https://stream.zeno.fm/bd-betar-stream",
    website: "http://www.bbc.gov.bd/",
    country: "Bangladesh",
    countryCode: "BD",
    language: "Bengali",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "http://www.bbc.gov.bd/favicon.ico",
  },

  // Pakistan (PK)
  {
    id: "fm-100-pakistan",
    name: "FM 100 Pakistan",
    streamUrl: "https://stream.zeno.fm/fm100-pakistan",
    website: "https://www.fm100pakistan.com/",
    country: "Pakistan",
    countryCode: "PK",
    language: "Urdu",
    genre: "Pop, Pakistani",
    bitrate: 128,
    favicon: "https://www.fm100pakistan.com/favicon.ico",
  },

  // Nepal (NP)
  {
    id: "radio-kantipur",
    name: "Radio Kantipur",
    streamUrl: "https://stream.radiokantipur.com/live.mp3",
    website: "https://radiokantipur.com/",
    country: "Nepal",
    countryCode: "NP",
    language: "Nepali",
    genre: "Pop, Nepali",
    bitrate: 128,
    favicon: "https://radiokantipur.com/favicon.ico",
  },

  // Sri Lanka (LK)
  {
    id: "sirasa-fm",
    name: "Sirasa FM",
    streamUrl: "https://stream.zeno.fm/sirasa-fm-stream",
    website: "https://www.sirasafm.lk/",
    country: "Sri Lanka",
    countryCode: "LK",
    language: "Sinhala",
    genre: "Pop, Sinhala",
    bitrate: 128,
    favicon: "https://www.sirasafm.lk/favicon.ico",
  },

  // Saudi Arabia (SA)
  {
    id: "mbc-fm-sa",
    name: "MBC FM",
    streamUrl: "https://stream.zeno.fm/mbc-fm-stream",
    website: "https://www.mbc.net/",
    country: "Saudi Arabia",
    countryCode: "SA",
    language: "Arabic",
    genre: "Arabic Pop",
    bitrate: 128,
    favicon: "https://www.mbc.net/favicon.ico",
  },

  // Iran (IR)
  {
    id: "irib-radio",
    name: "IRIB Radio",
    streamUrl: "https://stream.irib.ir/javan.mp3",
    website: "https://radio.irib.ir/",
    country: "Iran",
    countryCode: "IR",
    language: "Persian",
    genre: "Persian Music",
    bitrate: 128,
    favicon: "https://radio.irib.ir/favicon.ico",
  },

  // Iraq (IQ)
  {
    id: "radio-sawa",
    name: "Radio Sawa",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_SAWA_IRAAQ.mp3",
    website: "https://www.radiosawa.com/",
    country: "Iraq",
    countryCode: "IQ",
    language: "Arabic",
    genre: "Arabic Pop",
    bitrate: 128,
    favicon: "https://www.radiosawa.com/favicon.ico",
  },

  // Morocco (MA)
  {
    id: "medi-1-radio",
    name: "Medi 1 Radio",
    streamUrl: "https://streaming1.medi1.com:8000/medi1.aac",
    website: "https://www.medi1.com/",
    country: "Morocco",
    countryCode: "MA",
    language: "Arabic, French",
    genre: "Arabic Pop, Talk",
    bitrate: 128,
    favicon: "https://www.medi1.com/favicon.ico",
  },

  // Algeria (DZ)
  {
    id: "radio-algerienne",
    name: "Radio Algérienne",
    streamUrl: "https://stream.radioalgerie.dz/chaine1",
    website: "https://www.radioalgerie.dz/",
    country: "Algeria",
    countryCode: "DZ",
    language: "Arabic, French",
    genre: "Arabic Music",
    bitrate: 128,
    favicon: "https://www.radioalgerie.dz/favicon.ico",
  },

  // Tunisia (TN)
  {
    id: "rtci-tunisia",
    name: "RTCI",
    streamUrl: "https://stream.radiojar.com/rtci-tunisia",
    website: "https://www.rtci.tn/",
    country: "Tunisia",
    countryCode: "TN",
    language: "Arabic, French",
    genre: "International",
    bitrate: 128,
    favicon: "https://www.rtci.tn/favicon.ico",
  },

  // Belarus (BY)
  {
    id: "radio-belarus",
    name: "Radio Belarus",
    streamUrl: "https://stream.zeno.fm/radio-belarus-stream",
    website: "https://www.tvr.by/",
    country: "Belarus",
    countryCode: "BY",
    language: "Belarusian, Russian",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://www.tvr.by/favicon.ico",
  },

  // Kazakhstan (KZ)
  {
    id: "qazaq-radiosy",
    name: "Qazaq Radiosy",
    streamUrl: "https://stream.zeno.fm/qazaq-radiosy-stream",
    website: "https://qazaqradio.kz/",
    country: "Kazakhstan",
    countryCode: "KZ",
    language: "Kazakh, Russian",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://qazaqradio.kz/favicon.ico",
  },

  // Uzbekistan (UZ)
  {
    id: "uzbekiston-radio",
    name: "O'zbekiston Radio",
    streamUrl: "https://stream.zeno.fm/uzbekiston-radio-stream",
    website: "https://uza.uz/",
    country: "Uzbekistan",
    countryCode: "UZ",
    language: "Uzbek, Russian",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://uza.uz/favicon.ico",
  },

  // Azerbaijan (AZ)
  {
    id: "ictimai-radio",
    name: "Ictimai Radio",
    streamUrl: "https://stream.zeno.fm/ictimai-radio-stream",
    website: "https://www.ictimai.az/",
    country: "Azerbaijan",
    countryCode: "AZ",
    language: "Azerbaijani",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://www.ictimai.az/favicon.ico",
  },

  // Armenia (AM)
  {
    id: "public-radio-armenia",
    name: "Public Radio of Armenia",
    streamUrl: "https://stream.zeno.fm/public-radio-armenia-stream",
    website: "https://www.armradio.am/",
    country: "Armenia",
    countryCode: "AM",
    language: "Armenian",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://www.armradio.am/favicon.ico",
  },

  // Malta (MT)
  {
    id: "one-radio-malta",
    name: "One Radio Malta",
    streamUrl: "https://stream.zeno.fm/one-radio-malta-stream",
    website: "https://www.one.com.mt/",
    country: "Malta",
    countryCode: "MT",
    language: "English, Maltese",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.one.com.mt/favicon.ico",
  },

  // Cyprus (CY)
  {
    id: "cybc-radio",
    name: "CyBC Radio (RIK)",
    streamUrl: "https://stream.cybc.com.cy/rik1",
    website: "https://www.cybc.com.cy/",
    country: "Cyprus",
    countryCode: "CY",
    language: "Greek",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://www.cybc.com.cy/favicon.ico",
  },
];

export function getCuratedStationsByCountry(countryCode: string): CuratedRadioStation[] {
  return CURATED_RADIO_STATIONS.filter(
    (station) => station.countryCode.toUpperCase() === countryCode.toUpperCase()
  );
}

export function getAllCuratedStations(): CuratedRadioStation[] {
  return CURATED_RADIO_STATIONS;
}

export function getCuratedCountries(): { countryCode: string; country: string; stationCount: number }[] {
  const countryMap = new Map<string, { country: string; count: number }>();
  
  for (const station of CURATED_RADIO_STATIONS) {
    const existing = countryMap.get(station.countryCode);
    if (existing) {
      existing.count++;
    } else {
      countryMap.set(station.countryCode, { country: station.country, count: 1 });
    }
  }
  
  return Array.from(countryMap.entries()).map(([countryCode, { country, count }]) => ({
    countryCode,
    country,
    stationCount: count,
  })).sort((a, b) => b.stationCount - a.stationCount);
}

export function searchCuratedStations(query: string): CuratedRadioStation[] {
  const lowerQuery = query.toLowerCase();
  return CURATED_RADIO_STATIONS.filter(
    (station) =>
      station.name.toLowerCase().includes(lowerQuery) ||
      station.country.toLowerCase().includes(lowerQuery) ||
      station.genre.toLowerCase().includes(lowerQuery) ||
      station.language.toLowerCase().includes(lowerQuery)
  );
}
