export interface CuratedRadioStation {
  id: string;
  name: string;
  streamUrl: string;
  website: string;
  country: string;
  countryCode: string;
  language: string;
  genre: string;
  bitrate: number;
  favicon: string;
}

export const CURATED_RADIO_STATIONS: CuratedRadioStation[] = [
  // ============================================
  // TOP PRIORITY: ARTIST RADIOS (Most Popular First)
  // ============================================

  // Arijit Singh
  {
    id: "arijitsingh",
    name: "arijitsingh",
    streamUrl: "https://drive.uber.radio/uber/bollywoodaruitsingh/icecast.audio",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/arijitsingh.jpg",
  },

  // Kishore Kumar
  {
    id: "kishorekumarradio",
    name: "kishorekumarradio",
    streamUrl: "https://stream.zeno.fm/0ghtfp8ztm0uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/kishorekumarradio.jpg",
  },

  // Lata Mangeshkar
  {
    id: "hits-of-lata-mangeshkar",
    name: "Hits Of Lata Mangeshkar",
    streamUrl: "http://stream.zeno.fm/g95zm67prfhvv",
    website: "http://www.hitsofbollywood.com/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "latamangeshkarradio",
    name: "latamangeshkarradio",
    streamUrl: "https://stream.zeno.fm/87xam8pf7tzuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/latamangeshkarradio.jpg",
  },

  // Mohammed Rafi
  {
    id: "mohammed-rafi",
    name: "Mohammed Rafi",
    streamUrl: "https://stream.zeno.fm/6yqvumgfxtzuv",
    website: "https://zeno.fm/radio/mohammed-rafi/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "rafi-hit-songs",
    name: "Rafi hit songs",
    streamUrl: "https://stream.zeno.fm/0zkr7x8ztm0uv",
    website: "http://www.hitsofbollywood.com/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "classic hits 60s 70a 80s",
    bitrate: 128,
    favicon: "",
  },

  // Shreya Ghoshal
  {
    id: "bollywood-shreya-ghoshal",
    name: "Bollywood Shreya Ghoshal",
    streamUrl: "https://drive.uber.radio/uber/bollywoodshreyaghosal/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/shreya-ghoshal-radio.jpg",
  },

  // Sonu Nigam
  {
    id: "bollywood-sonu-nigam",
    name: "Bollywood Sonu Nigam",
    streamUrl: "https://streaming.exclusive.radio/uber/bollywoodsonunigam/icecast.audio",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "",
  },

  // Alka Yagnik
  {
    id: "bollywood-alka-yagnik",
    name: "Bollywood Alka Yagnik",
    streamUrl: "https://drive.uber.radio/uber/bollywoodalkayagnik/icecast.audio",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "",
  },

  // Udit Narayan
  {
    id: "bollywood-udit-narayan",
    name: "Bollywood Udit Narayan",
    streamUrl: "https://drive.uber.radio/uber/bollywooduditnarayan/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/udit-narayan-radio.jpg",
  },

  // Asha Bhosle
  {
    id: "bollywood-asha-bhosle",
    name: "Bollywood Asha Bhosle",
    streamUrl: "https://drive.uber.radio/uber/bollywoodashabhosle/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/asha-bhosle-radio.jpg",
  },

  // Pritam
  {
    id: "bollywood-pritam",
    name: "Bollywood Pritam",
    streamUrl: "https://drive.uber.radio/uber/bollywoodpritam/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/pritam-radio.jpg",
  },

  // Vishal Shekhar
  {
    id: "bollywood-vishal-shekhar",
    name: "Bollywood Vishal Shekhar",
    streamUrl: "https://drive.uber.radio/uber/bollywoodvishalshekhar/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/vishal-shekhar-radio.jpg",
  },

  // Amit Trivedi
  {
    id: "bollywood-amit-trivedi",
    name: "Bollywood Amit Trivedi",
    streamUrl: "https://drive.uber.radio/uber/bollywoodamittrivedi/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/amit-trivedi-radio.jpg",
  },

  // Neha Kakkar
  {
    id: "bollywood-neha-kakkar",
    name: "Bollywood Neha Kakkar",
    streamUrl: "https://drive.uber.radio/uber/bollywoodneharkakkar/icecast.audio",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "",
  },

  // Armaan Malik
  {
    id: "bollywood-armaan-malik",
    name: "Bollywood Armaan Malik",
    streamUrl: "https://drive.uber.radio/uber/bollywoodarmaanmalik/icecast.audio",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "",
  },

  // Atif Aslam
  {
    id: "bollywood-atif-aslam",
    name: "Bollywood Atif Aslam",
    streamUrl: "https://drive.uber.radio/uber/bollywoodatifaslam/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/atif-aslam-radio.jpg",
  },

  // Badshah
  {
    id: "bollywood-badshah",
    name: "Bollywood Badshah",
    streamUrl: "https://drive.uber.radio/uber/bollywoodbadshah/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/badshah-radio.jpg",
  },

  // Honey Singh
  {
    id: "bollywood-honey-singh",
    name: "Bollywood Yo Yo Honey Singh",
    streamUrl: "https://drive.uber.radio/uber/bollywoodhoneysingh/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/yo-yo-honey-singh-radio.jpg",
  },

  // Shah Rukh Khan
  {
    id: "bollywood-shah-rukh-khan",
    name: "Bollywood Shah Rukh Khan Hits",
    streamUrl: "https://drive.uber.radio/uber/bollywoodsrkhits/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/srk-radio.jpg",
  },

  // Punjabi / Harrdy Sandhu
  {
    id: "radio-hungama-punjabi-hits",
    name: "Radio Hungama Punjabi Hits",
    streamUrl: "http://103.16.47.70:9888/",
    website: "https://hungama.com/",
    country: "India",
    countryCode: "IN",
    language: "punjabi",
    genre: "Punjabi Hits",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/punjabi-radio.jpg",
  },

  // Other Popular Artists
  {
    id: "bollywood-sunidhi-chauhan",
    name: "Bollywood Sunidhi Chauhan",
    streamUrl: "https://drive.uber.radio/uber/bollywoodsunidhichauhan/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/sunidhi-chauhan-radio.jpg",
  },
  {
    id: "bollywood-jubin-nautiyal",
    name: "Bollywood Jubin Nautiyal",
    streamUrl: "https://drive.uber.radio/uber/bollywoodjubinnautiyal/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/Jubin-Nautiyal-radio.jpg",
  },
  {
    id: "bollywood-darshan-raval",
    name: "Bollywood Darshan Raval",
    streamUrl: "https://drive.uber.radio/uber/bollywooddarshanraval/icecast.audio",
    website: "https://bollywood.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Artist Radio",
    bitrate: 128,
    favicon: "https://indiaradio.in/wp-content/uploads/2024/01/darshan-raval-radio.jpg",
  },

  // South Indian Artists
  {
    id: "ilayaraja-radio",
    name: "Ilayaraja Radio",
    streamUrl: "https://psrlive2.listenon.in/ir?ah=0e81749e37789e5fb8c290926ce87e3f",
    website: "https://southradios.com/",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "tamil cinema music,tamil music",
    bitrate: 64,
    favicon: "https://southradios.com/assets/images/logo/logo90.webp",
  },
  {
    id: "ilayaraja-lite-radio",
    name: "Ilayaraja Lite Radio",
    streamUrl: "https://psrlive2.listenon.in/irlite?ah=0e81749e37789e5fb8c290926ce87e3f",
    website: "https://southradios.com/",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "tamil cinema music,tamil music",
    bitrate: 64,
    favicon: "https://southradios.com/assets/images/logo/logo90.webp",
  },
  {
    id: "ilayaraja-super-beats-radio",
    name: "Ilayaraja Super Beats Radio",
    streamUrl: "https://psrlive2.listenon.in/irbeat?ah=0e81749e37789e5fb8c290926ce87e3f",
    website: "https://southradios.com/",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "tamil cinema music,tamil music",
    bitrate: 64,
    favicon: "https://southradios.com/assets/images/logo/logo90.webp",
  },
  {
    id: "kj-yesudas-malayalam-radio",
    name: "KJ Yesudas Malayalam radio",
    streamUrl: "https://stream.zeno.fm/9x1sw687nf9uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "malayalam",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/03/Yesudas-Radio.jpg",
  },
  {
    id: "ks-chitra",
    name: "KS CHITRA",
    streamUrl: "https://stream.zeno.fm/aad4e51qz7zuv",
    website: "https://liveradios.in/ks-chitra-radio.html",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "chitra,south india,tamil",
    bitrate: 128,
    favicon: "https://liveradios.in/wp-content/uploads/output-onlinepngtools-1-150x150.png",
  },
  {
    id: "kschitraradio",
    name: "ks-chitra-radio",
    streamUrl: "https://stream.zeno.fm/aad4e51qz7zuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://liveradios.in/wp-content/uploads/ks-chitra.jpg",
  },
  {
    id: "kannadasan-radio",
    name: "Kannadasan Radio",
    streamUrl: "https://psrlive2.listenon.in/kavi?station=kaviyarasarradio",
    website: "https://www.tamilradios.com/kaviyarasar-radio",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "india,kannadasan,kaviarasar,tamil,tamil nadu",
    bitrate: 64,
    favicon: "",
  },

  // ============================================
  // SECOND TIER: MAJOR FM STATIONS
  // ============================================

  // Radio Mirchi
  {
    id: "radio-mirchi-hindi",
    name: "Radio Mirchi Hindi",
    streamUrl: "https://eu8.fastcast4u.com/proxy/clyedupq/stream",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Commercial FM Stations",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/radio-mirchi-hindi-fm.jpg",
  },
  {
    id: "mirchi-top-20",
    name: "Mirchi Top 20",
    streamUrl: "https://drive.uber.radio/uber/bollywoodnow/icecast.audio",
    website: "http://mirchi.in/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "bollywood,hindi,mirchi,pop",
    bitrate: 128,
    favicon: "http://mirchi.in/favicon-196x196.png",
  },
  {
    id: "mirchi-love",
    name: "Mirchi Love",
    streamUrl: "https://drive.uber.radio/uber/bollywoodlove/icecast.audio",
    website: "http://mirchi.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "india,love,mirchi,pop,romantic",
    bitrate: 128,
    favicon: "http://mirchi.in/favicon-196x196.png",
  },
  {
    id: "filmy-mirchi",
    name: "Filmy Mirchi",
    streamUrl: "https://stream.zeno.fm/6n6ewddtad0uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Commercial FM Stations",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/filmy-mirchi-hindi.jpg",
  },
  {
    id: "mirchi-one-896-qatar",
    name: "Mirchi One 89.6 Qatar",
    streamUrl: "https://streams.radio.co/s8d06d0298/listen",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Commercial FM Stations",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/mirchi-one-qatar.jpg",
  },
  {
    id: "radio-mirchi-usa",
    name: "Radio Mirchi USA",
    streamUrl: "https://streams.radio.co/s8d06d0298/listen",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Commercial FM Stations",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/06/radio-mirchi-usa-radio.jpg",
  },

  // Radio City
  {
    id: "radio-city-hindi",
    name: "Radio City Hindi",
    streamUrl: "http://prclive4.listenon.in/Hindi",
    website: "https://www.radiocity.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "bollywood,hindi,pop",
    bitrate: 128,
    favicon: "https://static.mytuner.mobi/media/tvos_radios/vZNzLXx52E.png",
  },
  {
    id: "radio-city-hiphop",
    name: "Radio City Hip-Hop",
    streamUrl: "http://prclive1.listenon.in:9960/",
    website: "https://www.radiocity.in/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "hip hop,india",
    bitrate: 128,
    favicon: "",
  },

  // BIG FM
  {
    id: "big-927-fm",
    name: "BIG 92.7 FM",
    streamUrl: "https://stream.zeno.fm/dbstwo3dvhhtv",
    website: "https://bigfmindia.com/",
    country: "India",
    countryCode: "IN",
    language: "hindi,kashmiri,urdu",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://bigfmindia.com/wp-content/themes/big-fm/assets/images/favicon.png",
  },
  {
    id: "bigfmtamil",
    name: "big-fm-tamil",
    streamUrl: "https://stream.zeno.fm/r2gn1pgm4qruv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://liveradios.in/wp-content/uploads/bigfm.jpg",
  },

  // FM Rainbow
  {
    id: "fmrainbowvijayawada",
    name: "fmrainbowvijayawada",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio174/playlist.m3u8",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "telugu",
    genre: "Telugu",
    bitrate: 126,
    favicon: "https://radiosindia.com/images/fmrainbow.jpg",
  },

  // Fever FM
  {
    id: "fever-104-fm",
    name: "Fever 104 FM",
    streamUrl: "https://radio.canstream.co.uk:8115/live.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Commercial FM Stations",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/08/fever-fm-107_3.jpg",
  },

  // ============================================
  // THIRD TIER: BOLLYWOOD GENRE STATIONS
  // ============================================
  {
    id: "bollywoodmix",
    name: "bollywoodmix",
    streamUrl: "https://drive.uber.radio/uber/bollywoodmix/icecast.audio",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/bollywoodradios.jpg",
  },
  {
    id: "bombay-beats-radio",
    name: "Bombay Beats Radio",
    streamUrl: "https://strmreg.1.fm/bombaybeats_mobile_mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 192,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/1fm-bombay-beats-radio.jpg",
  },
  {
    id: "bombaybeats",
    name: "BombayBeats",
    streamUrl: "http://strm112.1.fm/bombaybeats_mobile_mp3",
    website: "http://strm112.1.fm/bombaybeats_mobile_mp3",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "music",
    bitrate: 192,
    favicon: "",
  },
  {
    id: "hits-of-bollywood",
    name: "Hits Of Bollywood",
    streamUrl: "http://stream.zeno.fm/8ty8szwpwfeuv",
    website: "http://www.hitsofbollywood.com/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "bollywood,desi,hindi,india",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "new-hits-of-bollywood",
    name: "New Hits Of Bollywood",
    streamUrl: "https://stream.zeno.fm/rqqps6cbe3quv",
    website: "http://www.hitsofbollywood.com/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "namaste-bollywood",
    name: "Namaste Bollywood",
    streamUrl: "https://stream.zeno.fm/cqak4ap7by8uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/08/namaste-bollywood.jpg",
  },
  {
    id: "mixify-bollywood",
    name: "Mixify Bollywood",
    streamUrl: "https://server.mixify.in/listen/listen/radio.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 192,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/11/mixify-radio.jpg",
  },
  {
    id: "mixify-hindi-hits",
    name: "MixiFy Hindi Hits",
    streamUrl: "https://server.mixify.in/listen/new_hits/radio.mp3",
    website: "http://www.mixify.in/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "bollywood",
    bitrate: 192,
    favicon: "",
  },
  {
    id: "mohabbat-radio",
    name: "Mohabbat Radio",
    streamUrl: "https://stream.zeno.fm/t2ekq8zsgtzuv",
    website: "https://www.mohabbatradio.com/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "radio-hungama-bollywood-dil-se",
    name: "Radio Hungama Bollywood Dil Se",
    streamUrl: "https://stream.zeno.fm/143d7gty24zuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/02/bollywood-dilse.jpg",
  },
  {
    id: "bolly-1029-fm",
    name: "Bolly 102.9 FM",
    streamUrl: "https://ice6.securenetsystems.net/INTRADIO?type=.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 32,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/bolly-102-9-fm-radio.jpg",
  },
  {
    id: "radio-manpasand",
    name: "Radio Manpasand",
    streamUrl: "https://c5.radioboss.fm:18125/stream",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 256,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/08/radio-manpasand-hindi.jpg",
  },
  {
    id: "radio-namkin",
    name: "Radio Namkin",
    streamUrl: "https://stream.zeno.fm/yg1qhsbaqv5tv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/radio-namkin.jpg",
  },
  {
    id: "radio-badal",
    name: "Radio Badal",
    streamUrl: "https://stream.zeno.fm/nhrtcxg09u8uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/radio-badal-fm.jpg",
  },
  {
    id: "radiobaingan",
    name: "radiobaingan",
    streamUrl: "https://stream.zeno.fm/eyxg23ky4x8uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/radiobaingan.jpg",
  },
  {
    id: "tinder-radio",
    name: "Tinder Radio",
    streamUrl: "https://drive.uber.radio/er/bollywood/icecast.audio",
    website: "https://streaming.exclusive.radio/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "bollywood,hindi,love songs,romantic",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "np-24-radio",
    name: "NP 24 Radio",
    streamUrl: "https://stream.zeno.fm/8wk1s0pt008uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/08/np24-radio.jpg",
  },
  {
    id: "my-radio-dj",
    name: "MY RADIO DJ",
    streamUrl: "http://stream.zeno.fm/84h97t3ewg0uv",
    website: "http://zeno.fm/myradiodj",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "http://zeno.fm/favicon.ico",
  },
  {
    id: "tune-india-radio",
    name: "Tune India Radio",
    streamUrl: "https://s2.radio.co/se5e166e2f/listen#.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 96,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/09/tune-india-radio.jpg",
  },
  {
    id: "west-indian-vibes-radio",
    name: "West Indian Vibes Radio",
    streamUrl: "https://s6.citrus3.com:8396/stream",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/10/west-Indian-Vibes.jpg",
  },
  {
    id: "madhur-sangeet-radio",
    name: "Madhur Sangeet Radio",
    streamUrl: "https://stream.zeno.fm/yv2k0dp18vzuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/08/madhur-sangeet-radio.jpg",
  },
  {
    id: "rad",
    name: "rad",
    streamUrl: "https://drive.uber.radio/uber/bollywoodlove/icecast.audio",
    website: "http://mirchi.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "radio-905-fm",
    name: "Radio 90.5 FM",
    streamUrl: "https://ice42.securenetsystems.net/CR90",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 32,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/09/radio-90.5-fm.jpg",
  },
  {
    id: "radio-active-904-fm",
    name: "Radio Active 90.4 FM",
    streamUrl: "https://stream.zeno.fm/xwhhyc5nyk8uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/radio-active-90-4-fm.jpg",
  },
  {
    id: "radio-jagriti-904-fm",
    name: "Radio Jagriti 90.4 FM",
    streamUrl: "https://stream.zeno.fm/kgdue4hmffhvv",
    website: "http://radiojagriti.radio12345.com/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 128,
    favicon: "https://cdn.onlineradiobox.com/img/l/2/88622.v7.png",
  },

  // ============================================
  // RETRO & CLASSIC BOLLYWOOD
  // ============================================
  {
    id: "60sforever",
    name: "60sforever",
    streamUrl: "https://stream.zeno.fm/btrks671ynhvv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/60sforever.jpg",
  },
  {
    id: "90sonceagainradio",
    name: "90sonceagainradio",
    streamUrl: "https://stream.zeno.fm/rm4i9pdex3cuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/90sonceagainradio.jpg",
  },
  {
    id: "bollywood-90s-radio",
    name: "bollywood 90s radio",
    streamUrl: "https://stream.zeno.fm/rm4i9pdex3cuv",
    website: "https://www.radioindia.in/radio-retro-bollywood-90s",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "music",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "radio-bollywood-90s",
    name: "RADIO BOLLYWOOD 90s",
    streamUrl: "https://stream.zeno.fm/rm4i9pdex3cuv",
    website: "https://www.radioindia.in/radio-retro-bollywood-90s",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://static.mytuner.mobi/media/tvos_radios/9fKKkfbJKE.png",
  },
  {
    id: "radio-retro-bollywood",
    name: "Radio Retro Bollywood",
    streamUrl: "https://stream.zeno.fm/v2zfmxef798uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/06/radio-retro-bollywood.jpg",
  },
  {
    id: "radio-retro-bollywood-90s",
    name: "Radio Retro Bollywood 90s",
    streamUrl: "https://stream-143.zeno.fm/fdgs82xkzhhvv",
    website: "https://radioretrobollywood.com/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "bollywood,hindi bollywood",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "bollywood-classic-songs-",
    name: "Bollywood classic songs ",
    streamUrl: "https://stream.zeno.fm/60ef4p33vxquv",
    website: "https://www.radioindia.in/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "music",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "bollywood-gaane-purane",
    name: "Bollywood Gaane Purane",
    streamUrl: "https://stream.zeno.fm/6n6ewddtad0uv",
    website: "https://gaanepurane.my-free.website/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://mytuner.global.ssl.fastly.net/media/tvos_radios/ppqbgfej6skx.jpeg",
  },
  {
    id: "radio-bollywood-gaane-purane",
    name: "Radio Bollywood Gaane Purane",
    streamUrl: "https://stream.zeno.fm/6n6ewddtad0uv",
    website: "https://gaanepurane.my-free.website/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://mytuner.global.ssl.fastly.net/media/tvos_radios/ppqbgfej6skx.jpeg",
  },
  {
    id: "hindi-retro",
    name: "Hindi Retro",
    streamUrl: "https://stream.zeno.fm/v2zfmxef798uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/05/mirchi-retro-hindi.jpg",
  },
  {
    id: "hindi-gold-radio",
    name: "Hindi Gold Radio",
    streamUrl: "https://azuracast.vibesounds.in:8010/radio.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/07/hindi-gold-radio.jpg",
  },
  {
    id: "mixify-evergreen-hits",
    name: "MixiFy Evergreen Hits",
    streamUrl: "https://server.mixify.in:8010/",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 192,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/12/mixiFy-evergreen-hits.jpg",
  },
  {
    id: "goldenvoiceradio",
    name: "goldenvoiceradio",
    streamUrl: "https://stream.zeno.fm/s3sqemewrg0uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/goldenvoicefm.jpg",
  },
  {
    id: "lyca-gold",
    name: "Lyca Gold",
    streamUrl: "https://listen-lycaradio.sharp-stream.com/1035.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 192,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/09/lyca-gold-radio.jpg",
  },
  {
    id: "old-monk-radio",
    name: "Old Monk Radio",
    streamUrl: "https://stream.zeno.fm/pr0zc64zdy8uv",
    website: "https://zeno.fm/old-mong-radio/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 128,
    favicon: "https://zeno.fm/static/icons/apple-icon-120x120.png",
  },
  {
    id: "himal-hindi-classic-radio",
    name: "Himal Hindi Classic Radio",
    streamUrl: "https://streaming.webhostnepal.com/8012/stream",
    website: "https://liveradios.in/hindi-classic-radio.html",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Retro & Classic Bollywood",
    bitrate: 64,
    favicon: "",
  },
  {
    id: "free-fm-80s-india",
    name: "Free FM 80´s India",
    streamUrl: "https://freefm80.radioca.st/",
    website: "http://www.freefmworld.com/",
    country: "India",
    countryCode: "IN",
    language: "#english,#spanish",
    genre: "#80s,#freefm",
    bitrate: 320,
    favicon: "https://lh4.googleusercontent.com/acjVH3-jt6Rup86sTS16ZbClPjcB-xcVHsr-0RxPZplbCCgvPbb9WKSj2XdpcTdOCe_wzLfv9uktiQIJKkKgYc4lajlD5qKO6rSJl18sDC9yIehJREvzmK2zj9jc3V-n=w1280",
  },
  {
    id: "free-fm-bombay",
    name: "Free FM Bombay",
    streamUrl: "https://rocafmadrid.radioca.st/",
    website: "http://freefmradio.net/",
    country: "India",
    countryCode: "IN",
    language: "english,spanish",
    genre: "#free,#freefm,1980s,2000s,70 80 hits,80,80's,80s soft rock,90's,pop en español",
    bitrate: 320,
    favicon: "",
  },
  {
    id: "free-fm-top-100-india",
    name: "Free FM Top 100 India",
    streamUrl: "https://stream.zeno.fm/a5h7vfret68uv",
    website: "http://www.freefmworld.com/",
    country: "India",
    countryCode: "IN",
    language: "english,hindi",
    genre: "#freefm,#top100,top 40,top hits,top40",
    bitrate: 128,
    favicon: "https://cdn.instant.audio/images/logos/emisora-org-es/free-top-100.png",
  },
  {
    id: "gazal-radio-london",
    name: "Gazal Radio London",
    streamUrl: "https://streaming.webhostnepal.com/8018/stream",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Bollywood & Hindi Hits",
    bitrate: 64,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/10/gazal-radio-london-uk.png",
  },

  // Goldy Network
  {
    id: "goldy-blast",
    name: "Goldy Blast",
    streamUrl: "https://stream.zeno.fm/d0rwvvwa6p8uv",
    website: "https://zeno.fm/goldy-bhal/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Goldy Network",
    bitrate: 128,
    favicon: "https://cdn.onlineradiobox.com/img/l/2/101562.v2.png",
  },
  {
    id: "goldy-cool",
    name: "Goldy Cool",
    streamUrl: "https://stream.zeno.fm/3k1fb86tfm8uv",
    website: "https://zeno.fm/goldy-cool/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Goldy Network",
    bitrate: 128,
    favicon: "https://imgproxy.zenomedia.com/insecure/fit/500/500/ce/0/plain/https://proxy.zeno.fm/content/stations/agxzfnplbm8tc3RhdHNyMgsSCkF1dGhDbGllbnQYgIDQ16Ll_QkMCxIOU3RhdGlvblByb2ZpbGUYgIDQz-qz9QkMogEEemVubw/image/%3Fresize=500x500&v=1",
  },
  {
    id: "goldy-evergreen",
    name: "Goldy Evergreen",
    streamUrl: "https://stream.zeno.fm/n2fd0edh9k8uv",
    website: "https://zeno.fm/goldy-fm/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Goldy Network",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "goldy-garba",
    name: "Goldy Garba",
    streamUrl: "https://stream.zeno.fm/n0zkr7wa6p8uv",
    website: "https://zeno.fm/goldy-garba/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Goldy Network",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "goldy-mukesh",
    name: "Goldy Mukesh",
    streamUrl: "https://stream.zeno.fm/t39watus1p8uv",
    website: "https://zeno.fm/goldy-mukesh/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "bollywood,hindu,oldies",
    bitrate: 128,
    favicon: "https://zeno.fm/static/icons/apple-icon-120x120.png",
  },

  // ============================================
  // TAMIL & SOUTH INDIAN STATIONS
  // ============================================
  {
    id: "tamil-80s-radio",
    name: "Tamil 80's Radio",
    streamUrl: "https://psrlive2.listenon.in/80?station=tamil80shitsradio",
    website: "https://www.tamilradios.com/tamil-80s-radio",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 64,
    favicon: "https://www.tamilradios.com/assets/img/radio-logos/tamil-80s-radio.jpg",
  },
  {
    id: "894-tamil-fm",
    name: "89.4 Tamil FM",
    streamUrl: "https://centova.aarenworld.com/proxy/894tamilfm/stream",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/02/tamil-fm-894.jpg",
  },
  {
    id: "90s-tamil-melodies",
    name: "90's Tamil Melodies",
    streamUrl: "https://stream.zeno.fm/tqnws2eafwzuv.aac",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/12/90-tamil-melody.jpg",
  },
  {
    id: "evergreentamilradio",
    name: "evergreen-tamil-radio",
    streamUrl: "https://stream.zeno.fm/2fhh49f3zf8uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://liveradios.in/wp-content/uploads/evergreen-tamil-radio.jpg",
  },
  {
    id: "cityfmtamil",
    name: "cityfmtamil",
    streamUrl: "https://stream.zeno.fm/r4znzpvskchvv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/cityfmtamil.jpg",
  },
  {
    id: "britishindiantamilradio",
    name: "britishindiantamilradio",
    streamUrl: "https://hello.citrus3.com:2020/stream/britishindiantamilradio",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://radiosindia.com/images/britishindian.jpg",
  },
  {
    id: "nellai-fm",
    name: "Nellai FM",
    streamUrl: "https://stream.zenolive.com/5nu139840tzuv.aac",
    website: "https://tamilradios.net/nellai-tamil-fm/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "nellaitamilfm",
    name: "nellai-tamil-fm",
    streamUrl: "https://stream.zeno.fm/5nu139840tzuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://liveradios.in/wp-content/uploads/nellai-tamil-fm.jpg",
  },
  {
    id: "suntamilradio",
    name: "sun-tamil-radio",
    streamUrl: "https://stream.zeno.fm/yavek61461zuv.aac",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://liveradios.in/wp-content/uploads/suntamilradio.jpg",
  },
  {
    id: "tamillatesthitsradio",
    name: "tamil-latest-hits-radio",
    streamUrl: "https://stream.zeno.fm/dkxftg6k7tzuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://liveradios.in/wp-content/uploads/tamillatesthits.jpg",
  },
  {
    id: "tamil-old-hits-fm",
    name: "Tamil Old Hits FM",
    streamUrl: "https://a9oldhits-a9media.radioca.st/stream",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2024/01/a9-old-hits.jpg",
  },
  {
    id: "tamil-panpalai-gold",
    name: "Tamil Panpalai Gold",
    streamUrl: "https://tamilpanpalai.radioca.st/ind",
    website: "https://liveradios.in/tamil-panpalai.html",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "panpalai,south india,tamil",
    bitrate: 64,
    favicon: "",
  },
  {
    id: "sooriyan-fm",
    name: "Sooriyan FM",
    streamUrl: "https://radio.lotustechnologieslk.net:8006/;stream.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/01/Sooriyan_FM_tamil.jpg",
  },
  {
    id: "sahara-fm-tamil",
    name: "Sahara FM Tamil",
    streamUrl: "https://azuracast.vibesounds.in:8000/radio.mp3",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/12/sahara-fm.jpg",
  },
  {
    id: "radio-paramankurichi-tamil",
    name: "Radio Paramankurichi Tamil",
    streamUrl: "https://vpmurugun.radioca.st/stream",
    website: "https://www.radioparamankurichi.in/",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "Tamil & South Indian",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "kalai-fmtamil",
    name: "Kalai Fm-TAMIL",
    streamUrl: "https://stream.zenolive.com/2vghnwshsqzuv.aac",
    website: "http://kalaifm.in/",
    country: "India",
    countryCode: "IN",
    language: "tamil",
    genre: "entertainment,fun,live,online",
    bitrate: 128,
    favicon: "",
  },

  // ============================================
  // TELUGU STATIONS
  // ============================================
  {
    id: "ap-9-fm",
    name: "ap 9 FM",
    streamUrl: "https://stream.ap9fm.in/radio/8000/radio.mp3",
    website: "https://onlineradiofm.in/stations/ap-9-fm-telugu",
    country: "India",
    countryCode: "IN",
    language: "telugu",
    genre: "pop",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "london-telugu-radio",
    name: "London Telugu Radio",
    streamUrl: "https://c8.radioboss.fm/stream/33",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "classical",
    bitrate: 128,
    favicon: "",
  },

  // ============================================
  // MALAYALAM STATIONS
  // ============================================
  {
    id: "air-kochi-fm",
    name: "Air Kochi FM",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio045/chunklist.m3u8",
    website: "https://kochifm.blogspot.com/",
    country: "India",
    countryCode: "IN",
    language: "malayalam",
    genre: "Malayalam",
    bitrate: 128,
    favicon: "https://kochifm.blogspot.com/favicon.ico",
  },
  {
    id: "radio-malayalam-986-fm",
    name: "Radio Malayalam 98.6 FM",
    streamUrl: "https://stream.zeno.fm/512rbf1e3qzuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "malayalam",
    genre: "Malayalam",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2022/03/qatar-malayalam-986-fm.jpg",
  },

  // ============================================
  // KANNADA STATIONS
  // ============================================
  {
    id: "kannadahits",
    name: "kannadahits",
    streamUrl: "https://stream.zeno.fm/68snnbug8rhvv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "kannada",
    genre: "Kannada",
    bitrate: 128,
    favicon: "https://radiosindia.com/https://radiosindia.com/images/kannadahits.jpg",
  },
  {
    id: "madhur-tarang-kannada",
    name: "Madhur Tarang Kannada",
    streamUrl: "https://stream.zenolive.com/v0gde6udfg8uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "kannada",
    genre: "Kannada",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2022/01/madhur-tarang-kannada.jpg",
  },
  {
    id: "radio-amr-kannada",
    name: "Radio AMR Kannada",
    streamUrl: "https://stream.zenolive.com/7g8axtgtsg0uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "kannada",
    genre: "Kannada",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2022/01/amr.jpg",
  },
  {
    id: "sakkath-radio-kannada",
    name: "Sakkath Radio Kannada",
    streamUrl: "https://stream.zeno.fm/fcsk9ryerd0uv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "kannada",
    genre: "Kannada",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2022/01/sakkath-radio-kannada.jpg",
  },

  // ============================================
  // REGIONAL HINDI STATIONS
  // ============================================
  {
    id: "agra-radio",
    name: "Agra Radio",
    streamUrl: "https://stream.zeno.fm/m1krtxpk11zuv",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Regional Hindi",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/07/agra-radio-hindi.jpg",
  },
  {
    id: "ajmer-radio",
    name: "Ajmer Radio",
    streamUrl: "https://stream.zeno.fm/yftb93nbay8uv",
    website: "https://zeno.fm/ajmer-radio/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Regional Hindi",
    bitrate: 128,
    favicon: "https://zeno.fm/favicon.ico",
  },
  {
    id: "radio-rang",
    name: "Radio Rang",
    streamUrl: "http://stream.zeno.fm/44r9x09cqchvv",
    website: "https://radiorang.com/",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "bhojpuri radio,deoria,hindi",
    bitrate: 128,
    favicon: "https://cdn3.dan.com/assets/icons/touch-icon-iphone-retina-bdd5112764b4900705e85f7845ca32c42ae1bbefea7e6da068d8c85973fa199c.png",
  },

  // ============================================
  // DEVOTIONAL STATIONS
  // ============================================
  {
    id: "classic-radio-bhakti-sangeet",
    name: "Classic Radio Bhakti Sangeet",
    streamUrl: "https://stream.zeno.fm/epylmeu4zf7vv",
    website: "https://www.radioindia.in/classic-radio-bhakti-sangeet",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Devotional",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "bhajans-radio-guyana",
    name: "Bhajans Radio Guyana",
    streamUrl: "https://s5.citrus3.com:8148/stream",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "Devotional",
    bitrate: 128,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2023/07/bhajan-radio-guyana.jpg",
  },
  {
    id: "bhakti-sagar-durga-maa",
    name: "bhakti Sagar durga maa",
    streamUrl: "https://stream.zeno.fm/syu0rdutvxhvv",
    website: "https://stream.zeno.fm/syu0rdutvxhvv",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "bhakti sagar durga maa",
    bitrate: 128,
    favicon: "https://firebasestorage.googleapis.com/v0/b/radiogalaxy-580f4.appspot.com/o/images%2FIMG_20241003_181756353.jpg?alt=media&token=175d1625-9225-4539-99d0-56481348eb18",
  },
  {
    id: "radio-krishna-",
    name: "Radio Krishna ",
    streamUrl: "https://millenniumhits.out.airtime.pro:8000/millenniumhits_a?fbclid=IwAR0qP_F8RgDCq3gX8g7U8Dmm_uZedtPrqxCf8iIDAW5Jcd5ktA0XMs6BJu4",
    website: "https://radio.garden/listen/2b-radio-krishna/sxb6cxJs",
    country: "India",
    countryCode: "IN",
    language: "hindi",
    genre: "hindu",
    bitrate: 48,
    favicon: "https://radio.garden/public/icons/ios/ios-appicon-152-152.png",
  },
  {
    id: "hand-of-jesus-bangla",
    name: "Hand Of Jesus - BANGLA",
    streamUrl: "https://dc1.serverse.com/proxy/hojbengali/stream",
    website: "https://handofjesus.in/radio/christian-radio-bangla.php",
    country: "India",
    countryCode: "IN",
    language: "bangla",
    genre: "christian",
    bitrate: 64,
    favicon: "",
  },
  {
    id: "hand-of-jesus-nepali",
    name: "Hand Of Jesus - NEPALI",
    streamUrl: "https://dc1.serverse.com/proxy/hojnepali/stream",
    website: "https://handofjesus.in/radio/christian-radio-nepali.php",
    country: "India",
    countryCode: "IN",
    language: "nepali",
    genre: "christian",
    bitrate: 64,
    favicon: "",
  },

  // ============================================
  // OTHER REGIONAL STATIONS
  // ============================================
  {
    id: "bhojpuri-songs-",
    name: "Bhojpuri Songs ",
    streamUrl: "https://stream.zeno.fm/yz0ncx9gha0uv",
    website: "http://www.bhojapuri.com/",
    country: "India",
    countryCode: "IN",
    language: "bhojpuri",
    genre: "bhojpuri",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "radio-kesari-900-fm",
    name: "Radio Kesari 90.0 FM",
    streamUrl: "https://stream.zeno.fm/7yhq985hnxhvv",
    website: "https://radiokesari.com/",
    country: "India",
    countryCode: "IN",
    language: "bhojpuri",
    genre: "bhojpuri",
    bitrate: 128,
    favicon: "",
  },
  {
    id: "hot-now-bangla",
    name: "Hot Now Bangla",
    streamUrl: "https://stream.radiotreetal.com/listen",
    website: "",
    country: "India",
    countryCode: "IN",
    language: "bangla",
    genre: "Bengali",
    bitrate: 48,
    favicon: "https://onlineradiohub.com/wp-content/uploads/2024/02/hot-now-bangla-fm.jpg",
  },
];

export function getCuratedStationsByCountry(countryCode: string): CuratedRadioStation[] {
  return CURATED_RADIO_STATIONS.filter(
    (station) => station.countryCode.toUpperCase() === countryCode.toUpperCase()
  );
}

export function getAllCuratedStations(): CuratedRadioStation[] {
  return CURATED_RADIO_STATIONS;
}

export function getCuratedCountries(): { countryCode: string; country: string; stationCount: number }[] {
  const countryMap = new Map<string, { country: string; count: number }>();
  
  for (const station of CURATED_RADIO_STATIONS) {
    const existing = countryMap.get(station.countryCode);
    if (existing) {
      existing.count++;
    } else {
      countryMap.set(station.countryCode, { country: station.country, count: 1 });
    }
  }
  
  return Array.from(countryMap.entries()).map(([countryCode, { country, count }]) => ({
    countryCode,
    country,
    stationCount: count,
  })).sort((a, b) => b.stationCount - a.stationCount);
}

export function searchCuratedStations(query: string): CuratedRadioStation[] {
  const lowerQuery = query.toLowerCase();
  return CURATED_RADIO_STATIONS.filter(
    (station) =>
      station.name.toLowerCase().includes(lowerQuery) ||
      station.country.toLowerCase().includes(lowerQuery) ||
      station.genre.toLowerCase().includes(lowerQuery) ||
      station.language.toLowerCase().includes(lowerQuery)
  );
}
