export interface CuratedRadioStation {
  id: string;
  name: string;
  streamUrl: string;
  website: string;
  country: string;
  countryCode: string;
  language: string;
  genre: string;
  bitrate: number;
  favicon: string;
}

export const CURATED_RADIO_STATIONS: CuratedRadioStation[] = [
  // India (IN) - Verified URLs
  {
    id: "air-vividh-bharati",
    name: "All India Radio - Vividh Bharati",
    streamUrl: "https://vividhbharati-lh.akamaihd.net/i/vividhbharati_1@507811/index_1_a-p.m3u8?sd=10&rebase=on",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Music",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "air-fm-rainbow",
    name: "All India Radio - FM Rainbow",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio002/playlist.m3u8",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Contemporary, Pop",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "air-fm-gold",
    name: "All India Radio - FM Gold",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio003/playlist.m3u8",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Golden Hits, Retro",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "air-raagam",
    name: "All India Radio - Raagam",
    streamUrl: "https://air.pc.cdn.bitgravity.com/air/live/pbaudio004/playlist.m3u8",
    website: "https://akashvani.gov.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Classical, Indian Classical",
    bitrate: 128,
    favicon: "https://akashvani.gov.in/images/logo.png",
  },
  {
    id: "radio-mirchi-983",
    name: "Radio Mirchi 98.3 FM",
    streamUrl: "http://radios.crabdance.com:8002/1",
    website: "https://mirchi.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Pop",
    bitrate: 36,
    favicon: "https://mirchi.in/favicon.ico",
  },
  {
    id: "radio-city-911",
    name: "Radio City 91.1 FM",
    streamUrl: "https://prclive1.listenon.in/Hindi",
    website: "https://www.radiocity.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Music",
    bitrate: 128,
    favicon: "https://www.radiocity.in/favicon.ico",
  },
  {
    id: "red-fm-935",
    name: "Red FM 93.5",
    streamUrl: "https://prclive1.listenon.in/redfm",
    website: "https://www.redfmindia.in/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Pop",
    bitrate: 128,
    favicon: "https://www.redfmindia.in/favicon.ico",
  },
  {
    id: "big-fm-927",
    name: "Big FM 92.7",
    streamUrl: "https://prclive1.listenon.in/bigfm",
    website: "https://bigfmindia.com/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Bollywood, Hits",
    bitrate: 128,
    favicon: "https://bigfmindia.com/favicon.ico",
  },
  {
    id: "fever-fm-104",
    name: "Fever FM 104",
    streamUrl: "https://prclive1.listenon.in/fever",
    website: "https://www.fever.fm/",
    country: "India",
    countryCode: "IN",
    language: "Hindi",
    genre: "Contemporary, Pop",
    bitrate: 128,
    favicon: "https://www.fever.fm/favicon.ico",
  },
  {
    id: "radio-one-943",
    name: "Radio One 94.3 FM",
    streamUrl: "https://prclive1.listenon.in/radioone",
    website: "https://www.radioone.fm/",
    country: "India",
    countryCode: "IN",
    language: "English",
    genre: "English, Urban",
    bitrate: 128,
    favicon: "https://www.radioone.fm/favicon.ico",
  },

  // United States (US) - Verified URLs
  {
    id: "kexp-seattle",
    name: "KEXP 90.3 FM Seattle",
    streamUrl: "https://kexp.streamguys1.com/kexp160.aac",
    website: "https://www.kexp.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Alternative, Indie",
    bitrate: 160,
    favicon: "https://www.kexp.org/favicon.ico",
  },
  {
    id: "kexp-seattle-64",
    name: "KEXP Seattle (Low)",
    streamUrl: "https://kexp.streamguys1.com/kexp64.aac",
    website: "https://www.kexp.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Alternative, Indie",
    bitrate: 64,
    favicon: "https://www.kexp.org/favicon.ico",
  },
  {
    id: "kcrw-la",
    name: "KCRW Los Angeles",
    streamUrl: "https://kcrw.streamguys1.com/kcrw_192k_mp3_on_air",
    website: "https://www.kcrw.com/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Eclectic, Alternative",
    bitrate: 192,
    favicon: "https://www.kcrw.com/favicon.ico",
  },
  {
    id: "wxpn-philly",
    name: "WXPN Philadelphia",
    streamUrl: "https://wxpn-ice.streamguys1.com/xpn-mp3-hi",
    website: "https://xpn.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "AAA, Americana",
    bitrate: 128,
    favicon: "https://xpn.org/favicon.ico",
  },
  {
    id: "wfmu-jersey",
    name: "WFMU",
    streamUrl: "https://stream0.wfmu.org/freeform-128k",
    website: "https://wfmu.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Freeform, Eclectic",
    bitrate: 128,
    favicon: "https://wfmu.org/favicon.ico",
  },
  {
    id: "wnyc-fm",
    name: "WNYC New York",
    streamUrl: "https://fm939.wnyc.org/wnycfm",
    website: "https://www.wnyc.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "Public Radio, Talk",
    bitrate: 128,
    favicon: "https://www.wnyc.org/favicon.ico",
  },
  {
    id: "wamu-dc",
    name: "WAMU 88.5 Washington DC",
    streamUrl: "https://hd1.wamu.org/",
    website: "https://www.wamu.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "NPR, Public Radio",
    bitrate: 128,
    favicon: "https://www.wamu.org/favicon.ico",
  },
  {
    id: "npr-live",
    name: "NPR News Live",
    streamUrl: "https://npr-ice.streamguys1.com/live.mp3",
    website: "https://www.npr.org/",
    country: "United States",
    countryCode: "US",
    language: "English",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://www.npr.org/favicon.ico",
  },

  // United Kingdom (GB) - Verified URLs
  {
    id: "bbc-radio-1",
    name: "BBC Radio 1",
    streamUrl: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "bbc-radio-2",
    name: "BBC Radio 2",
    streamUrl: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Adult Contemporary",
    bitrate: 128,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "bbc-radio-3",
    name: "BBC Radio 3",
    streamUrl: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_three",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Classical, Jazz",
    bitrate: 128,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "bbc-radio-4",
    name: "BBC Radio 4",
    streamUrl: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Talk, News",
    bitrate: 128,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "bbc-1xtra",
    name: "BBC Radio 1Xtra",
    streamUrl: "http://stream.live.vc.bbcmedia.co.uk/bbc_1xtra",
    website: "https://www.bbc.co.uk/sounds/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Urban, Hip Hop",
    bitrate: 128,
    favicon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    id: "capital-fm-uk",
    name: "Capital FM",
    streamUrl: "http://media-ice.musicradio.com/CapitalMP3",
    website: "https://www.globalplayer.com/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://www.capitalfm.com/favicon.ico",
  },
  {
    id: "capital-uk-national",
    name: "Capital UK National",
    streamUrl: "http://vis.media-ice.musicradio.com/CapitalUK",
    website: "https://www.globalplayer.com/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://www.capitalfm.com/favicon.ico",
  },
  {
    id: "kiss-fm-uk",
    name: "Kiss FM UK",
    streamUrl: "http://media-ice.musicradio.com/KissMP3",
    website: "https://www.globalplayer.com/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Dance, Electronic",
    bitrate: 128,
    favicon: "https://www.kissfm.com/favicon.ico",
  },
  {
    id: "absolute-radio-uk",
    name: "Absolute Radio",
    streamUrl: "https://ais-sa3.cdnstream1.com/2569_128.mp3",
    website: "https://absoluteradio.co.uk/",
    country: "United Kingdom",
    countryCode: "GB",
    language: "English",
    genre: "Rock, Alternative",
    bitrate: 128,
    favicon: "https://absoluteradio.co.uk/favicon.ico",
  },

  // France (FR) - Verified URLs
  {
    id: "france-inter",
    name: "France Inter",
    streamUrl: "https://icecast.radiofrance.fr/franceinter-midfi.mp3",
    website: "https://www.radiofrance.fr/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Talk, Music",
    bitrate: 128,
    favicon: "https://www.radiofrance.fr/favicon.ico",
  },
  {
    id: "france-inter-hifi",
    name: "France Inter (Hi-Fi)",
    streamUrl: "https://icecast.radiofrance.fr/franceinter-hifi.aac",
    website: "https://www.radiofrance.fr/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Talk, Music",
    bitrate: 192,
    favicon: "https://www.radiofrance.fr/favicon.ico",
  },
  {
    id: "nrj-france",
    name: "NRJ France",
    streamUrl: "http://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3",
    website: "https://www.nrj.fr/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.nrj.fr/favicon.ico",
  },
  {
    id: "france-musique",
    name: "France Musique",
    streamUrl: "https://icecast.radiofrance.fr/francemusique-midfi.mp3",
    website: "https://www.radiofrance.fr/francemusique/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Classical, Jazz",
    bitrate: 128,
    favicon: "https://www.radiofrance.fr/favicon.ico",
  },
  {
    id: "fip-france",
    name: "FIP",
    streamUrl: "https://icecast.radiofrance.fr/fip-midfi.mp3",
    website: "https://www.radiofrance.fr/fip",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Eclectic, World",
    bitrate: 128,
    favicon: "https://www.radiofrance.fr/favicon.ico",
  },
  {
    id: "cherie-fm",
    name: "Chérie FM",
    streamUrl: "http://cdn.nrjaudio.fm/audio1/fr/30201/mp3_128.mp3",
    website: "https://www.cheriefm.fr/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Pop, Love Songs",
    bitrate: 128,
    favicon: "https://www.cheriefm.fr/favicon.ico",
  },
  {
    id: "nostalgie-france",
    name: "Nostalgie",
    streamUrl: "http://cdn.nrjaudio.fm/audio1/fr/30601/mp3_128.mp3",
    website: "https://www.nostalgie.fr/",
    country: "France",
    countryCode: "FR",
    language: "French",
    genre: "Oldies, Retro",
    bitrate: 128,
    favicon: "https://www.nostalgie.fr/favicon.ico",
  },

  // Germany (DE) - Verified URLs
  {
    id: "1live-wdr",
    name: "1LIVE WDR",
    streamUrl: "https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3",
    website: "https://www1.wdr.de/radio/1live/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www1.wdr.de/favicon.ico",
  },
  {
    id: "antenne-bayern",
    name: "Antenne Bayern",
    streamUrl: "https://stream.antenne.de/antenne",
    website: "https://www.antenne.de/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.antenne.de/favicon.ico",
  },
  {
    id: "ndr2-germany",
    name: "NDR 2",
    streamUrl: "https://icecast.ndr.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3",
    website: "https://www.ndr.de/ndr2/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Rock",
    bitrate: 128,
    favicon: "https://www.ndr.de/favicon.ico",
  },
  {
    id: "bayern3",
    name: "Bayern 3",
    streamUrl: "https://streams.br.de/bayern3_2.m3u",
    website: "https://www.br.de/radio/bayern3/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.br.de/favicon.ico",
  },
  {
    id: "dlf-kultur",
    name: "Deutschlandfunk Kultur",
    streamUrl: "https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3",
    website: "https://www.deutschlandfunkkultur.de/",
    country: "Germany",
    countryCode: "DE",
    language: "German",
    genre: "Culture, Music",
    bitrate: 128,
    favicon: "https://www.deutschlandfunkkultur.de/favicon.ico",
  },

  // Netherlands (NL) - Verified URLs
  {
    id: "npo-radio-2",
    name: "NPO Radio 2",
    streamUrl: "http://icecast.omroep.nl/radio2-bb-mp3",
    website: "https://www.nporadio2.nl/",
    country: "Netherlands",
    countryCode: "NL",
    language: "Dutch",
    genre: "Pop, Dutch",
    bitrate: 192,
    favicon: "https://www.nporadio2.nl/favicon.ico",
  },
  {
    id: "npo-radio-2-aac",
    name: "NPO Radio 2 (AAC)",
    streamUrl: "http://icecast.omroep.nl/radio2-bb-aac",
    website: "https://www.nporadio2.nl/",
    country: "Netherlands",
    countryCode: "NL",
    language: "Dutch",
    genre: "Pop, Dutch",
    bitrate: 64,
    favicon: "https://www.nporadio2.nl/favicon.ico",
  },
  {
    id: "radio-538-nl",
    name: "Radio 538",
    streamUrl: "https://21253.live.streamtheworld.com/RADIO538.mp3",
    website: "https://www.radio538.nl/",
    country: "Netherlands",
    countryCode: "NL",
    language: "Dutch",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.radio538.nl/favicon.ico",
  },
  {
    id: "qmusic-nl",
    name: "Qmusic NL",
    streamUrl: "https://21253.live.streamtheworld.com/QMUSIC.mp3",
    website: "https://www.qmusic.nl/",
    country: "Netherlands",
    countryCode: "NL",
    language: "Dutch",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.qmusic.nl/favicon.ico",
  },

  // Australia (AU) - Verified URLs
  {
    id: "triple-j-abc",
    name: "triple j",
    streamUrl: "https://live-radio01.mediahubaustralia.com/2TJW/mp3/",
    website: "https://www.abc.net.au/triplej/",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    genre: "Alternative, Youth",
    bitrate: 128,
    favicon: "https://www.abc.net.au/favicon.ico",
  },
  {
    id: "abc-classic",
    name: "ABC Classic",
    streamUrl: "https://live-radio01.mediahubaustralia.com/CLYW/mp3/",
    website: "https://www.abc.net.au/classic/",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    genre: "Classical",
    bitrate: 128,
    favicon: "https://www.abc.net.au/favicon.ico",
  },
  {
    id: "abc-radio-national",
    name: "ABC Radio National",
    streamUrl: "https://live-radio01.mediahubaustralia.com/2RNW/mp3/",
    website: "https://www.abc.net.au/radionational/",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    genre: "Talk, News",
    bitrate: 128,
    favicon: "https://www.abc.net.au/favicon.ico",
  },

  // Canada (CA) - Verified URLs
  {
    id: "cbc-music",
    name: "CBC Music",
    streamUrl: "https://cbcliveradio-lh.akamaihd.net/i/CBCMUSIC_OTT@311823/master.m3u8",
    website: "https://www.cbc.ca/listen/live-radio",
    country: "Canada",
    countryCode: "CA",
    language: "English",
    genre: "Eclectic, Canadian",
    bitrate: 128,
    favicon: "https://www.cbc.ca/favicon.ico",
  },
  {
    id: "virgin-radio-toronto",
    name: "Virgin Radio Toronto",
    streamUrl: "https://18233.live.streamtheworld.com/CKFMFM.mp3",
    website: "https://www.iheartradio.ca/",
    country: "Canada",
    countryCode: "CA",
    language: "English",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://www.iheartradio.ca/favicon.ico",
  },
  {
    id: "102-1-the-edge",
    name: "102.1 The Edge",
    streamUrl: "https://18393.live.streamtheworld.com/CFNYFM.mp3",
    website: "https://www.theedge.ca/",
    country: "Canada",
    countryCode: "CA",
    language: "English",
    genre: "Alternative Rock",
    bitrate: 128,
    favicon: "https://www.theedge.ca/favicon.ico",
  },

  // Spain (ES) - Verified URLs
  {
    id: "los40-spain",
    name: "Los 40 España",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40AAC.aac",
    website: "https://los40.com/",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    genre: "Pop, Top 40",
    bitrate: 128,
    favicon: "https://los40.com/favicon.ico",
  },
  {
    id: "cadena-ser",
    name: "Cadena SER",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASERAAC.aac",
    website: "https://cadenaser.com/",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    genre: "Talk, News",
    bitrate: 128,
    favicon: "https://cadenaser.com/favicon.ico",
  },
  {
    id: "cadena-100",
    name: "Cadena 100",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENA100AAC.aac",
    website: "https://www.cadena100.es/",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.cadena100.es/favicon.ico",
  },

  // Italy (IT) - Verified URLs
  {
    id: "radio-italia",
    name: "Radio Italia",
    streamUrl: "https://icecast.radioitalia.it/radioitaliaonly.mp3",
    website: "https://www.radioitalia.it/",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    genre: "Italian Pop",
    bitrate: 128,
    favicon: "https://www.radioitalia.it/favicon.ico",
  },
  {
    id: "radio-deejay",
    name: "Radio Deejay",
    streamUrl: "https://streamcdnb3-4c4b867c89244861ac216426883d1ad0.msvdn.net/webradio/deejay.aac",
    website: "https://www.radio.deejay.it/",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.deejay.it/favicon.ico",
  },
  {
    id: "rtl-1025",
    name: "RTL 102.5",
    streamUrl: "https://streamingv2.shoutcast.com/rtl-1025",
    website: "https://www.rtl.it/",
    country: "Italy",
    countryCode: "IT",
    language: "Italian",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.rtl.it/favicon.ico",
  },

  // Belgium (BE) - Verified URLs
  {
    id: "studio-brussel",
    name: "Studio Brussel",
    streamUrl: "https://icecast.vrtcdn.be/stubru-high.mp3",
    website: "https://www.vrt.be/",
    country: "Belgium",
    countryCode: "BE",
    language: "Dutch",
    genre: "Alternative, Youth",
    bitrate: 320,
    favicon: "https://www.stubru.be/favicon.ico",
  },
  {
    id: "qmusic-belgium",
    name: "Qmusic Belgium",
    streamUrl: "https://icecast-qmusic.dpgmedia.net/qmusic.mp3",
    website: "https://www.qmusic.be/",
    country: "Belgium",
    countryCode: "BE",
    language: "Dutch",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.qmusic.be/favicon.ico",
  },

  // Russia (RU) - Verified URLs
  {
    id: "europa-plus",
    name: "Europa Plus",
    streamUrl: "https://ep128.hostingradio.ru:8030/ep128",
    website: "https://www.europaplus.ru/",
    country: "Russia",
    countryCode: "RU",
    language: "Russian",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.europaplus.ru/favicon.ico",
  },
  {
    id: "russkoe-radio",
    name: "Russkoe Radio",
    streamUrl: "https://rusradio.hostingradio.ru/rusradio128.mp3",
    website: "https://rusradio.ru/",
    country: "Russia",
    countryCode: "RU",
    language: "Russian",
    genre: "Russian Pop",
    bitrate: 128,
    favicon: "https://rusradio.ru/favicon.ico",
  },

  // Poland (PL) - Verified URLs
  {
    id: "rmf-fm",
    name: "RMF FM",
    streamUrl: "https://rs6-krk2.rmfstream.pl/rmf_fm",
    website: "https://www.rmf.fm/",
    country: "Poland",
    countryCode: "PL",
    language: "Polish",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.rmf.fm/favicon.ico",
  },
  {
    id: "radio-zet",
    name: "Radio Zet",
    streamUrl: "https://n-4-1.dcs.redcdn.pl/sc/o2/Eurozet/live/audio.livx",
    website: "https://www.radiozet.pl/",
    country: "Poland",
    countryCode: "PL",
    language: "Polish",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.radiozet.pl/favicon.ico",
  },

  // Switzerland (CH) - Verified URLs
  {
    id: "srf-3",
    name: "SRF 3",
    streamUrl: "https://stream.srg-ssr.ch/m/drs3/mp3_128",
    website: "https://www.srf.ch/",
    country: "Switzerland",
    countryCode: "CH",
    language: "German",
    genre: "Pop, Contemporary",
    bitrate: 128,
    favicon: "https://www.srf.ch/favicon.ico",
  },

  // Norway (NO) - Verified URLs
  {
    id: "nrk-p3",
    name: "NRK P3",
    streamUrl: "https://lyd.nrk.no/nrk_radio_p3_aac_h",
    website: "https://radio.nrk.no/",
    country: "Norway",
    countryCode: "NO",
    language: "Norwegian",
    genre: "Pop, Youth",
    bitrate: 192,
    favicon: "https://radio.nrk.no/favicon.ico",
  },

  // Denmark (DK) - Verified URLs
  {
    id: "dr-p3",
    name: "DR P3",
    streamUrl: "https://live-icy.dr.dk/A/A05H.mp3",
    website: "https://www.dr.dk/",
    country: "Denmark",
    countryCode: "DK",
    language: "Danish",
    genre: "Pop, Youth",
    bitrate: 192,
    favicon: "https://www.dr.dk/favicon.ico",
  },

  // Finland (FI) - Verified URLs
  {
    id: "ylex",
    name: "YleX",
    streamUrl: "https://icecast.live.yle.fi/radio/ylex.aac",
    website: "https://areena.yle.fi/",
    country: "Finland",
    countryCode: "FI",
    language: "Finnish",
    genre: "Pop, Alternative",
    bitrate: 128,
    favicon: "https://areena.yle.fi/favicon.ico",
  },

  // Ireland (IE) - Verified URLs
  {
    id: "rte-2fm",
    name: "RTÉ 2FM",
    streamUrl: "https://icecast2.rte.ie/radio2fm",
    website: "https://www.rte.ie/",
    country: "Ireland",
    countryCode: "IE",
    language: "English",
    genre: "Pop, Youth",
    bitrate: 160,
    favicon: "https://www.rte.ie/favicon.ico",
  },

  // Iceland (IS) - Verified URLs
  {
    id: "ruv-ras-2",
    name: "RÚV Rás 2",
    streamUrl: "https://icecast.ruv.is/ras2/128.mp3",
    website: "https://www.ruv.is/",
    country: "Iceland",
    countryCode: "IS",
    language: "Icelandic",
    genre: "Pop, Music",
    bitrate: 128,
    favicon: "https://www.ruv.is/favicon.ico",
  },

  // Estonia (EE) - Verified URLs
  {
    id: "vikerraadio",
    name: "Vikerraadio",
    streamUrl: "https://icecast.err.ee/vikerraadio.mp3",
    website: "https://vikerraadio.err.ee/",
    country: "Estonia",
    countryCode: "EE",
    language: "Estonian",
    genre: "Talk, Music",
    bitrate: 192,
    favicon: "https://vikerraadio.err.ee/favicon.ico",
  },

  // Latvia (LV) - Verified URLs
  {
    id: "latvijas-radio",
    name: "Latvijas Radio",
    streamUrl: "https://lr1mp3hq.latvijasradio.lv/lr1mp3.mp3",
    website: "https://www.latvijasradio.lv/",
    country: "Latvia",
    countryCode: "LV",
    language: "Latvian",
    genre: "Public Radio",
    bitrate: 128,
    favicon: "https://www.latvijasradio.lv/favicon.ico",
  },

  // Romania (RO) - Verified URLs
  {
    id: "radio-zu",
    name: "Radio ZU",
    streamUrl: "https://live4.radiozu.ro:8443/radiozu.aacp",
    website: "https://www.radiozu.ro/",
    country: "Romania",
    countryCode: "RO",
    language: "Romanian",
    genre: "Pop, Dance",
    bitrate: 128,
    favicon: "https://www.radiozu.ro/favicon.ico",
  },

  // Czechia (CZ) - Verified URLs
  {
    id: "radiozurnal",
    name: "Radiožurnál",
    streamUrl: "https://icecast6.play.cz/cro1-128.mp3",
    website: "https://www.rozhlas.cz/",
    country: "Czechia",
    countryCode: "CZ",
    language: "Czech",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://www.rozhlas.cz/favicon.ico",
  },

  // Hungary (HU) - Verified URLs
  {
    id: "radio-1-hu",
    name: "Rádió 1",
    streamUrl: "https://stream.radio1.hu/high.mp3",
    website: "https://www.radio1.hu/",
    country: "Hungary",
    countryCode: "HU",
    language: "Hungarian",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.radio1.hu/favicon.ico",
  },

  // Slovakia (SK) - Verified URLs
  {
    id: "radio-expres",
    name: "Rádio Expres",
    streamUrl: "https://icecast.stv.livebox.sk/radioexpres_128.mp3",
    website: "https://www.expres.sk/",
    country: "Slovakia",
    countryCode: "SK",
    language: "Slovak",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.expres.sk/favicon.ico",
  },

  // Slovenia (SI) - Verified URLs
  {
    id: "val-202",
    name: "Val 202",
    streamUrl: "https://mp3.rtvslo.si/val202",
    website: "https://www.rtvslo.si/",
    country: "Slovenia",
    countryCode: "SI",
    language: "Slovenian",
    genre: "Pop, Youth",
    bitrate: 128,
    favicon: "https://www.rtvslo.si/favicon.ico",
  },

  // Mexico (MX) - Verified URLs
  {
    id: "los40-mexico",
    name: "Los 40 México",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_MEXICOAAC.aac",
    website: "https://los40.com.mx/",
    country: "Mexico",
    countryCode: "MX",
    language: "Spanish",
    genre: "Pop, Latin",
    bitrate: 128,
    favicon: "https://los40.com.mx/favicon.ico",
  },

  // Colombia (CO) - Verified URLs
  {
    id: "caracol-radio",
    name: "Caracol Radio",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/CARACOL_COLOMBIAAAC.aac",
    website: "https://caracol.com.co/",
    country: "Colombia",
    countryCode: "CO",
    language: "Spanish",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://caracol.com.co/favicon.ico",
  },

  // Chile (CL) - Verified URLs
  {
    id: "radio-cooperativa",
    name: "Radio Cooperativa",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/COOPERATIVAAAC.aac",
    website: "https://www.cooperativa.cl/",
    country: "Chile",
    countryCode: "CL",
    language: "Spanish",
    genre: "News, Talk",
    bitrate: 128,
    favicon: "https://www.cooperativa.cl/favicon.ico",
  },

  // Portugal (PT) - Verified URLs
  {
    id: "rfm-portugal",
    name: "RFM",
    streamUrl: "https://21933.live.streamtheworld.com/RFMPORTUGAL.mp3",
    website: "https://www.rfm.pt/",
    country: "Portugal",
    countryCode: "PT",
    language: "Portuguese",
    genre: "Pop, Hits",
    bitrate: 128,
    favicon: "https://www.rfm.pt/favicon.ico",
  },

  // Morocco (MA) - Verified URLs
  {
    id: "medi-1-radio",
    name: "Medi 1 Radio",
    streamUrl: "https://streaming1.medi1.com:8000/medi1.aac",
    website: "https://www.medi1.com/",
    country: "Morocco",
    countryCode: "MA",
    language: "Arabic, French",
    genre: "Arabic Pop, Talk",
    bitrate: 128,
    favicon: "https://www.medi1.com/favicon.ico",
  },

  // Iraq (IQ) - Verified URLs
  {
    id: "radio-sawa",
    name: "Radio Sawa",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_SAWA_IRAAQ.mp3",
    website: "https://www.radiosawa.com/",
    country: "Iraq",
    countryCode: "IQ",
    language: "Arabic",
    genre: "Arabic Pop",
    bitrate: 128,
    favicon: "https://www.radiosawa.com/favicon.ico",
  },
];

export function getCuratedStationsByCountry(countryCode: string): CuratedRadioStation[] {
  return CURATED_RADIO_STATIONS.filter(
    (station) => station.countryCode.toUpperCase() === countryCode.toUpperCase()
  );
}

export function getAllCuratedStations(): CuratedRadioStation[] {
  return CURATED_RADIO_STATIONS;
}

export function getCuratedCountries(): { countryCode: string; country: string; stationCount: number }[] {
  const countryMap = new Map<string, { country: string; count: number }>();
  
  for (const station of CURATED_RADIO_STATIONS) {
    const existing = countryMap.get(station.countryCode);
    if (existing) {
      existing.count++;
    } else {
      countryMap.set(station.countryCode, { country: station.country, count: 1 });
    }
  }
  
  return Array.from(countryMap.entries()).map(([countryCode, { country, count }]) => ({
    countryCode,
    country,
    stationCount: count,
  })).sort((a, b) => b.stationCount - a.stationCount);
}

export function searchCuratedStations(query: string): CuratedRadioStation[] {
  const lowerQuery = query.toLowerCase();
  return CURATED_RADIO_STATIONS.filter(
    (station) =>
      station.name.toLowerCase().includes(lowerQuery) ||
      station.country.toLowerCase().includes(lowerQuery) ||
      station.genre.toLowerCase().includes(lowerQuery) ||
      station.language.toLowerCase().includes(lowerQuery)
  );
}
