export interface CuratedStation {
  name: string;
  searchTerms: string[];
}

export const CURATED_STATIONS: Record<string, CuratedStation[]> = {
  IN: [
    { name: 'Radio Mirchi', searchTerms: ['radio mirchi', 'mirchi 98.3'] },
    { name: 'Red FM', searchTerms: ['red fm', '93.5 red'] },
    { name: 'Radio City', searchTerms: ['radio city', '91.1 fm'] },
    { name: 'Big FM', searchTerms: ['big fm', '92.7 big'] },
    { name: 'Fever FM', searchTerms: ['fever fm', 'fever 104'] },
    { name: 'All India Radio', searchTerms: ['all india radio', 'air', 'akashvani'] },
    { name: 'Vividh Bharati', searchTerms: ['vividh bharati'] },
    { name: 'Radio One', searchTerms: ['radio one 94.3'] },
    { name: 'AIR FM Gold', searchTerms: ['air fm gold', 'fm gold'] },
    { name: 'AIR FM Rainbow', searchTerms: ['air rainbow', 'fm rainbow'] },
    { name: 'Radio Nasha', searchTerms: ['radio nasha'] },
    { name: 'Ishq FM', searchTerms: ['ishq fm'] },
    { name: 'Bollywood Radio', searchTerms: ['bollywood', 'hindi songs'] },
    { name: 'Punjabi Radio', searchTerms: ['punjabi radio', 'air punjabi'] },
    { name: 'Tamil FM', searchTerms: ['tamil fm', 'suryan fm'] },
    { name: 'Telugu Radio', searchTerms: ['telugu radio', 'radio telugu'] },
    { name: 'Malayalam Radio', searchTerms: ['malayalam radio', 'radio mango'] },
    { name: 'Kannada Radio', searchTerms: ['kannada radio', 'radio mirchi kannada'] },
    { name: 'Marathi Radio', searchTerms: ['marathi radio', 'radio mirchi marathi'] },
    { name: 'Bengali Radio', searchTerms: ['bengali radio', 'radio mirchi bangla'] },
  ],
  US: [
    { name: 'iHeartRadio', searchTerms: ['iheartradio', 'iheart'] },
    { name: 'NPR', searchTerms: ['npr', 'national public radio'] },
    { name: 'Kiss FM', searchTerms: ['kiss fm', 'kiis fm'] },
    { name: 'Hot 97', searchTerms: ['hot 97', 'hot97'] },
    { name: 'Power 105', searchTerms: ['power 105'] },
    { name: 'Z100', searchTerms: ['z100', 'whtz'] },
    { name: 'KEXP', searchTerms: ['kexp'] },
    { name: 'WNYC', searchTerms: ['wnyc'] },
    { name: 'KROQ', searchTerms: ['kroq'] },
    { name: 'KCRW', searchTerms: ['kcrw'] },
    { name: 'SiriusXM Hits', searchTerms: ['siriusxm', 'sirius hits'] },
    { name: 'Classic Rock', searchTerms: ['classic rock', 'rock radio'] },
    { name: 'Country Music', searchTerms: ['country radio', 'country music'] },
    { name: 'Hip Hop', searchTerms: ['hip hop radio', 'rap radio'] },
    { name: 'Jazz FM', searchTerms: ['jazz fm', 'smooth jazz'] },
    { name: 'Classical Radio', searchTerms: ['classical radio', 'wqxr'] },
    { name: 'ESPN Radio', searchTerms: ['espn radio'] },
    { name: 'CBS Radio', searchTerms: ['cbs radio'] },
    { name: 'Bloomberg Radio', searchTerms: ['bloomberg radio'] },
    { name: 'BBC World Service', searchTerms: ['bbc world service'] },
  ],
  GB: [
    { name: 'BBC Radio 1', searchTerms: ['bbc radio 1'] },
    { name: 'BBC Radio 2', searchTerms: ['bbc radio 2'] },
    { name: 'BBC Radio 3', searchTerms: ['bbc radio 3'] },
    { name: 'BBC Radio 4', searchTerms: ['bbc radio 4'] },
    { name: 'BBC Radio 5', searchTerms: ['bbc radio 5 live'] },
    { name: 'BBC Radio 6 Music', searchTerms: ['bbc 6 music', 'bbc radio 6'] },
    { name: 'Capital FM', searchTerms: ['capital fm', 'capital radio'] },
    { name: 'Heart FM', searchTerms: ['heart fm', 'heart radio'] },
    { name: 'Kiss FM UK', searchTerms: ['kiss fm uk', 'kiss fresh'] },
    { name: 'Classic FM', searchTerms: ['classic fm'] },
    { name: 'Absolute Radio', searchTerms: ['absolute radio'] },
    { name: 'LBC', searchTerms: ['lbc radio', 'lbc 97.3'] },
    { name: 'talkSPORT', searchTerms: ['talksport'] },
    { name: 'Smooth Radio', searchTerms: ['smooth radio'] },
    { name: 'Radio X', searchTerms: ['radio x'] },
    { name: 'Magic FM', searchTerms: ['magic fm', 'magic radio'] },
    { name: 'Virgin Radio', searchTerms: ['virgin radio uk'] },
    { name: 'Planet Rock', searchTerms: ['planet rock'] },
    { name: 'Jazz FM UK', searchTerms: ['jazz fm uk'] },
    { name: 'Scala Radio', searchTerms: ['scala radio'] },
  ],
  DE: [
    { name: 'Bayern 3', searchTerms: ['bayern 3', 'br3'] },
    { name: 'SWR3', searchTerms: ['swr3', 'swr 3'] },
    { name: 'WDR 2', searchTerms: ['wdr 2', 'wdr2'] },
    { name: '1Live', searchTerms: ['1live', 'einslive'] },
    { name: 'NDR 2', searchTerms: ['ndr 2', 'ndr2'] },
    { name: 'Antenne Bayern', searchTerms: ['antenne bayern'] },
    { name: 'Radio Hamburg', searchTerms: ['radio hamburg'] },
    { name: 'Radio FFH', searchTerms: ['radio ffh', 'ffh'] },
    { name: 'HR3', searchTerms: ['hr3', 'hr 3'] },
    { name: 'MDR Jump', searchTerms: ['mdr jump'] },
    { name: 'Deutschlandfunk', searchTerms: ['deutschlandfunk'] },
    { name: 'Radio Bob', searchTerms: ['radio bob'] },
    { name: 'Klassik Radio', searchTerms: ['klassik radio'] },
    { name: 'Sunshine Live', searchTerms: ['sunshine live'] },
    { name: 'bigFM', searchTerms: ['bigfm', 'big fm germany'] },
    { name: 'Energy Berlin', searchTerms: ['energy berlin'] },
    { name: 'RTL Radio', searchTerms: ['rtl radio'] },
    { name: 'Rock Antenne', searchTerms: ['rock antenne'] },
    { name: 'Radio 7', searchTerms: ['radio 7'] },
    { name: 'RPR1', searchTerms: ['rpr1'] },
  ],
  FR: [
    { name: 'NRJ', searchTerms: ['nrj', 'nrj france'] },
    { name: 'RTL', searchTerms: ['rtl france', 'rtl radio'] },
    { name: 'Europe 1', searchTerms: ['europe 1'] },
    { name: 'France Inter', searchTerms: ['france inter'] },
    { name: 'France Info', searchTerms: ['france info', 'franceinfo'] },
    { name: 'France Culture', searchTerms: ['france culture'] },
    { name: 'France Musique', searchTerms: ['france musique'] },
    { name: 'RFM', searchTerms: ['rfm france'] },
    { name: 'Skyrock', searchTerms: ['skyrock'] },
    { name: 'Fun Radio', searchTerms: ['fun radio'] },
    { name: 'Virgin Radio France', searchTerms: ['virgin radio france'] },
    { name: 'Nostalgie', searchTerms: ['nostalgie france'] },
    { name: 'Cherie FM', searchTerms: ['cherie fm'] },
    { name: 'RMC', searchTerms: ['rmc radio'] },
    { name: 'RTL2', searchTerms: ['rtl2 france'] },
    { name: 'Radio Nova', searchTerms: ['radio nova'] },
    { name: 'FIP', searchTerms: ['fip radio'] },
    { name: 'Mouv', searchTerms: ['mouv radio'] },
    { name: 'Radio Classique', searchTerms: ['radio classique'] },
    { name: 'TSF Jazz', searchTerms: ['tsf jazz'] },
  ],
  JP: [
    { name: 'NHK Radio', searchTerms: ['nhk radio', 'nhk world'] },
    { name: 'J-Wave', searchTerms: ['j-wave', 'jwave'] },
    { name: 'Tokyo FM', searchTerms: ['tokyo fm'] },
    { name: 'InterFM', searchTerms: ['interfm', 'inter fm'] },
    { name: 'Nippon Broadcasting', searchTerms: ['nippon broadcasting'] },
    { name: 'TBS Radio', searchTerms: ['tbs radio'] },
    { name: 'FM Yokohama', searchTerms: ['fm yokohama'] },
    { name: 'Bay FM', searchTerms: ['bay fm'] },
    { name: 'NACK5', searchTerms: ['nack5'] },
    { name: 'FM802', searchTerms: ['fm802'] },
    { name: 'ZIP-FM', searchTerms: ['zip-fm', 'zipfm'] },
    { name: 'Cross FM', searchTerms: ['cross fm'] },
    { name: 'FM North Wave', searchTerms: ['fm north wave'] },
    { name: 'Alpha Station', searchTerms: ['alpha station'] },
    { name: 'Radio Nippon', searchTerms: ['radio nippon'] },
    { name: 'J-Pop Radio', searchTerms: ['j-pop', 'jpop radio'] },
    { name: 'Anime Radio', searchTerms: ['anime radio'] },
    { name: 'Asia Dream', searchTerms: ['asia dream radio'] },
    { name: 'Radio Neo', searchTerms: ['radio neo'] },
    { name: 'FM Aichi', searchTerms: ['fm aichi'] },
  ],
  BR: [
    { name: 'Jovem Pan', searchTerms: ['jovem pan'] },
    { name: 'Band FM', searchTerms: ['band fm', 'radio bandeirantes'] },
    { name: 'Mix FM', searchTerms: ['mix fm brasil'] },
    { name: 'Globo FM', searchTerms: ['globo fm', 'radio globo'] },
    { name: 'Transamérica', searchTerms: ['transamerica'] },
    { name: 'Nativa FM', searchTerms: ['nativa fm'] },
    { name: 'Antena 1', searchTerms: ['antena 1'] },
    { name: 'Kiss FM Brasil', searchTerms: ['kiss fm brasil'] },
    { name: 'Alpha FM', searchTerms: ['alpha fm brasil'] },
    { name: 'CBN', searchTerms: ['cbn radio'] },
    { name: 'BandNews FM', searchTerms: ['bandnews fm'] },
    { name: 'Eldorado FM', searchTerms: ['eldorado fm'] },
    { name: 'Cidade FM', searchTerms: ['cidade fm'] },
    { name: 'Tupi FM', searchTerms: ['tupi fm'] },
    { name: 'Nova Brasil FM', searchTerms: ['nova brasil'] },
    { name: 'Energia 97 FM', searchTerms: ['energia 97'] },
    { name: 'Gazeta FM', searchTerms: ['gazeta fm'] },
    { name: 'Metropolitana FM', searchTerms: ['metropolitana fm'] },
    { name: 'Rádio Disney', searchTerms: ['radio disney brasil'] },
    { name: 'Rede Aleluia', searchTerms: ['rede aleluia'] },
  ],
  AU: [
    { name: 'Triple J', searchTerms: ['triple j', 'abc triple j'] },
    { name: 'ABC Radio', searchTerms: ['abc radio', 'abc news radio'] },
    { name: 'KIIS FM', searchTerms: ['kiis fm', 'kiis 106.5'] },
    { name: 'Nova FM', searchTerms: ['nova fm', 'nova 96.9'] },
    { name: 'Smooth FM', searchTerms: ['smooth fm australia'] },
    { name: '2GB', searchTerms: ['2gb', '2gb sydney'] },
    { name: '3AW', searchTerms: ['3aw', '3aw melbourne'] },
    { name: 'Triple M', searchTerms: ['triple m'] },
    { name: 'Mix FM', searchTerms: ['mix fm australia'] },
    { name: 'Gold FM', searchTerms: ['gold fm australia'] },
    { name: 'Hit Network', searchTerms: ['hit network', 'hit fm'] },
    { name: 'Fox FM', searchTerms: ['fox fm'] },
    { name: 'WSFM', searchTerms: ['wsfm'] },
    { name: 'Edge Radio', searchTerms: ['edge radio'] },
    { name: 'FBi Radio', searchTerms: ['fbi radio'] },
    { name: 'Double J', searchTerms: ['double j'] },
    { name: 'RN', searchTerms: ['radio national', 'abc rn'] },
    { name: 'Classic FM Australia', searchTerms: ['abc classic'] },
    { name: 'SBS Radio', searchTerms: ['sbs radio'] },
    { name: 'JJJ Unearthed', searchTerms: ['unearthed'] },
  ],
  CA: [
    { name: 'CBC Radio One', searchTerms: ['cbc radio one', 'cbc radio'] },
    { name: 'CBC Music', searchTerms: ['cbc music', 'cbc radio 2'] },
    { name: 'Virgin Radio', searchTerms: ['virgin radio canada'] },
    { name: 'CHUM FM', searchTerms: ['chum fm'] },
    { name: 'Kiss 92.5', searchTerms: ['kiss 92.5', 'kiss fm toronto'] },
    { name: 'CFNY Edge', searchTerms: ['cfny', 'edge 102'] },
    { name: 'Q107', searchTerms: ['q107'] },
    { name: 'CFRB', searchTerms: ['cfrb', 'newstalk 1010'] },
    { name: 'CJAD', searchTerms: ['cjad'] },
    { name: 'CKOI', searchTerms: ['ckoi'] },
    { name: 'Rouge FM', searchTerms: ['rouge fm'] },
    { name: 'NRJ Canada', searchTerms: ['nrj canada'] },
    { name: 'The Beat', searchTerms: ['the beat 92.5'] },
    { name: 'CFOX', searchTerms: ['cfox'] },
    { name: 'The Peak', searchTerms: ['the peak vancouver'] },
    { name: 'CHEZ 106', searchTerms: ['chez 106'] },
    { name: 'Jack FM', searchTerms: ['jack fm canada'] },
    { name: 'Indie88', searchTerms: ['indie88'] },
    { name: 'boom 97.3', searchTerms: ['boom 97.3'] },
    { name: 'Classical 96.3 FM', searchTerms: ['classical 96.3'] },
  ],
  ES: [
    { name: 'Cadena SER', searchTerms: ['cadena ser'] },
    { name: 'Los 40', searchTerms: ['los 40', 'los cuarenta'] },
    { name: 'COPE', searchTerms: ['cope radio'] },
    { name: 'Onda Cero', searchTerms: ['onda cero'] },
    { name: 'RNE', searchTerms: ['rne', 'radio nacional'] },
    { name: 'Radio 3', searchTerms: ['radio 3 rne'] },
    { name: 'Cadena Dial', searchTerms: ['cadena dial'] },
    { name: 'Cadena 100', searchTerms: ['cadena 100'] },
    { name: 'Europa FM', searchTerms: ['europa fm spain'] },
    { name: 'Rock FM', searchTerms: ['rock fm spain'] },
    { name: 'Kiss FM Spain', searchTerms: ['kiss fm spain'] },
    { name: 'Máxima FM', searchTerms: ['maxima fm'] },
    { name: 'Melodía FM', searchTerms: ['melodia fm'] },
    { name: 'RAC1', searchTerms: ['rac1'] },
    { name: 'Catalunya Radio', searchTerms: ['catalunya radio'] },
    { name: 'esRadio', searchTerms: ['esradio'] },
    { name: 'Radio Marca', searchTerms: ['radio marca'] },
    { name: 'Hit FM', searchTerms: ['hit fm spain'] },
    { name: 'Flaixbac', searchTerms: ['flaixbac'] },
    { name: 'Radio Clásica', searchTerms: ['radio clasica rne'] },
  ],
  MX: [
    { name: 'Los 40 México', searchTerms: ['los 40 mexico'] },
    { name: 'Exa FM', searchTerms: ['exa fm'] },
    { name: 'La Mejor FM', searchTerms: ['la mejor fm'] },
    { name: 'Alfa Radio', searchTerms: ['alfa radio mexico'] },
    { name: 'Beat 100.9', searchTerms: ['beat 100.9'] },
    { name: 'Mix FM', searchTerms: ['mix fm mexico'] },
    { name: 'Radio Fórmula', searchTerms: ['radio formula'] },
    { name: 'W Radio', searchTerms: ['w radio mexico'] },
    { name: 'MVS Radio', searchTerms: ['mvs radio'] },
    { name: 'Radio Centro', searchTerms: ['radio centro'] },
    { name: 'Imagen Radio', searchTerms: ['imagen radio'] },
    { name: 'Radio UNAM', searchTerms: ['radio unam'] },
    { name: 'Horizonte', searchTerms: ['horizonte 107.9'] },
    { name: 'Reactor 105.7', searchTerms: ['reactor 105.7'] },
    { name: 'Ibero 90.9', searchTerms: ['ibero 90.9'] },
    { name: 'Rock 101', searchTerms: ['rock 101 mexico'] },
    { name: 'La Z', searchTerms: ['la z fm'] },
    { name: 'Ke Buena', searchTerms: ['ke buena'] },
    { name: 'Radio Disney México', searchTerms: ['radio disney mexico'] },
    { name: 'Universal Stereo', searchTerms: ['universal stereo'] },
  ],
  IT: [
    { name: 'RAI Radio 1', searchTerms: ['rai radio 1'] },
    { name: 'RAI Radio 2', searchTerms: ['rai radio 2'] },
    { name: 'RAI Radio 3', searchTerms: ['rai radio 3'] },
    { name: 'Radio Deejay', searchTerms: ['radio deejay', 'deejay'] },
    { name: 'RTL 102.5', searchTerms: ['rtl 102.5', 'rtl italy'] },
    { name: 'Radio Italia', searchTerms: ['radio italia'] },
    { name: 'RDS', searchTerms: ['rds radio', 'rds 100'] },
    { name: 'Radio 105', searchTerms: ['radio 105'] },
    { name: 'Virgin Radio Italy', searchTerms: ['virgin radio italy'] },
    { name: 'Radio Capital', searchTerms: ['radio capital italy'] },
    { name: 'm2o', searchTerms: ['m2o', 'm2o radio'] },
    { name: 'Radio Kiss Kiss', searchTerms: ['radio kiss kiss'] },
    { name: 'Radio 24', searchTerms: ['radio 24'] },
    { name: 'Radio Monte Carlo', searchTerms: ['radio monte carlo italy'] },
    { name: 'Radio Subasio', searchTerms: ['radio subasio'] },
    { name: 'Radio Freccia', searchTerms: ['radio freccia'] },
    { name: 'Radio Bruno', searchTerms: ['radio bruno'] },
    { name: 'Radio Zeta', searchTerms: ['radio zeta'] },
    { name: 'Latte Miele', searchTerms: ['latte miele'] },
    { name: 'Radio Maria Italy', searchTerms: ['radio maria italy'] },
  ],
  RU: [
    { name: 'Radio Mayak', searchTerms: ['radio mayak', 'маяк'] },
    { name: 'Europa Plus', searchTerms: ['europa plus', 'европа плюс'] },
    { name: 'Russian Radio', searchTerms: ['russian radio', 'русское радио'] },
    { name: 'Radio Rossii', searchTerms: ['radio rossii', 'радио россии'] },
    { name: 'Avtoradio', searchTerms: ['avtoradio', 'авторадио'] },
    { name: 'Retro FM', searchTerms: ['retro fm russia', 'ретро фм'] },
    { name: 'Love Radio', searchTerms: ['love radio', 'лав радио'] },
    { name: 'Radio Energy', searchTerms: ['radio energy russia', 'energy fm'] },
    { name: 'Nashe Radio', searchTerms: ['nashe radio', 'наше радио'] },
    { name: 'Radio Chanson', searchTerms: ['radio chanson', 'радио шансон'] },
    { name: 'Radio Maximum', searchTerms: ['radio maximum', 'максимум'] },
    { name: 'DFM', searchTerms: ['dfm russia', 'dfm'] },
    { name: 'Hit FM Russia', searchTerms: ['hit fm russia'] },
    { name: 'Radio Dacha', searchTerms: ['radio dacha', 'радио дача'] },
    { name: 'Business FM', searchTerms: ['business fm russia'] },
    { name: 'Echo of Moscow', searchTerms: ['echo of moscow', 'эхо москвы'] },
    { name: 'Silver Rain', searchTerms: ['silver rain', 'серебряный дождь'] },
    { name: 'Vesti FM', searchTerms: ['vesti fm', 'вести фм'] },
    { name: 'Comedy Radio', searchTerms: ['comedy radio'] },
    { name: 'Radio Jazz', searchTerms: ['radio jazz russia'] },
  ],
  CN: [
    { name: 'CNR China National Radio', searchTerms: ['cnr', 'china national radio'] },
    { name: 'China Radio International', searchTerms: ['cri', 'china radio international'] },
    { name: 'Beijing Radio', searchTerms: ['beijing radio', 'beijing fm'] },
    { name: 'Shanghai Radio', searchTerms: ['shanghai radio', 'shanghai fm'] },
    { name: 'Guangdong Radio', searchTerms: ['guangdong radio'] },
    { name: 'Hit FM China', searchTerms: ['hit fm china'] },
    { name: 'Music Radio', searchTerms: ['music radio china'] },
    { name: 'Easy FM', searchTerms: ['easy fm china'] },
    { name: 'China Plus', searchTerms: ['china plus'] },
    { name: 'CNR Music', searchTerms: ['cnr music'] },
    { name: 'CNR Business', searchTerms: ['cnr business radio'] },
    { name: 'Voice of China', searchTerms: ['voice of china'] },
    { name: 'Shenzhen Radio', searchTerms: ['shenzhen radio'] },
    { name: 'Tianjin Radio', searchTerms: ['tianjin radio'] },
    { name: 'Chongqing Radio', searchTerms: ['chongqing radio'] },
    { name: 'Zhejiang Radio', searchTerms: ['zhejiang radio'] },
    { name: 'Jiangsu Radio', searchTerms: ['jiangsu radio'] },
    { name: 'Phoenix Radio', searchTerms: ['phoenix radio'] },
    { name: 'Classic FM China', searchTerms: ['classic fm china'] },
    { name: 'My FM China', searchTerms: ['my fm china'] },
  ],
  KR: [
    { name: 'KBS Radio', searchTerms: ['kbs radio', 'kbs 1 radio'] },
    { name: 'KBS Cool FM', searchTerms: ['kbs cool fm'] },
    { name: 'MBC Radio', searchTerms: ['mbc radio', 'mbc fm'] },
    { name: 'SBS Power FM', searchTerms: ['sbs power fm'] },
    { name: 'SBS Love FM', searchTerms: ['sbs love fm'] },
    { name: 'EBS FM', searchTerms: ['ebs fm'] },
    { name: 'CBS Radio', searchTerms: ['cbs radio korea'] },
    { name: 'TBS eFM', searchTerms: ['tbs efm'] },
    { name: 'Arirang Radio', searchTerms: ['arirang radio'] },
    { name: 'FEBC Korea', searchTerms: ['febc korea'] },
    { name: 'YTN Radio', searchTerms: ['ytn radio'] },
    { name: 'KBS Classic FM', searchTerms: ['kbs classic fm'] },
    { name: 'MBC FM4U', searchTerms: ['mbc fm4u'] },
    { name: 'KBS 2 Radio', searchTerms: ['kbs 2 radio'] },
    { name: 'K-Pop Radio', searchTerms: ['k-pop radio', 'kpop radio'] },
    { name: 'Gugak FM', searchTerms: ['gugak fm'] },
    { name: 'BBS Radio', searchTerms: ['bbs radio korea'] },
    { name: 'WBS Radio', searchTerms: ['wbs radio'] },
    { name: 'TBN Korea', searchTerms: ['tbn korea'] },
    { name: 'AFN Korea', searchTerms: ['afn korea'] },
  ],
  NL: [
    { name: 'NPO Radio 1', searchTerms: ['npo radio 1'] },
    { name: 'NPO Radio 2', searchTerms: ['npo radio 2'] },
    { name: 'NPO 3FM', searchTerms: ['npo 3fm', '3fm'] },
    { name: 'Radio 538', searchTerms: ['radio 538', '538'] },
    { name: 'Q-music', searchTerms: ['qmusic', 'q-music netherlands'] },
    { name: 'Sky Radio', searchTerms: ['sky radio netherlands'] },
    { name: 'Radio Veronica', searchTerms: ['radio veronica'] },
    { name: 'Radio 10', searchTerms: ['radio 10 netherlands'] },
    { name: 'BNR Nieuwsradio', searchTerms: ['bnr nieuwsradio'] },
    { name: 'SLAM!', searchTerms: ['slam fm', 'slam radio'] },
    { name: 'Sublime FM', searchTerms: ['sublime fm'] },
    { name: 'FunX', searchTerms: ['funx'] },
    { name: 'NPO Radio 4', searchTerms: ['npo radio 4'] },
    { name: 'NPO Radio 5', searchTerms: ['npo radio 5'] },
    { name: '100% NL', searchTerms: ['100 nl', '100% nl'] },
    { name: 'Kink', searchTerms: ['kink fm'] },
    { name: 'Classic FM Netherlands', searchTerms: ['classic fm netherlands'] },
    { name: 'Arrow Classic Rock', searchTerms: ['arrow classic rock'] },
    { name: 'Joe FM Netherlands', searchTerms: ['joe fm netherlands'] },
    { name: 'Groot Nieuws Radio', searchTerms: ['groot nieuws radio'] },
  ],
  BE: [
    { name: 'VRT Radio 1', searchTerms: ['vrt radio 1', 'radio 1 belgium'] },
    { name: 'VRT Radio 2', searchTerms: ['vrt radio 2', 'radio 2 belgium'] },
    { name: 'Studio Brussel', searchTerms: ['studio brussel'] },
    { name: 'MNM', searchTerms: ['mnm radio'] },
    { name: 'Klara', searchTerms: ['klara radio'] },
    { name: 'Q-music Belgium', searchTerms: ['qmusic belgium'] },
    { name: 'Joe FM Belgium', searchTerms: ['joe fm belgium'] },
    { name: 'Nostalgie Belgium', searchTerms: ['nostalgie belgium'] },
    { name: 'NRJ Belgium', searchTerms: ['nrj belgium'] },
    { name: 'Classic 21', searchTerms: ['classic 21'] },
    { name: 'La Première', searchTerms: ['la premiere rtbf'] },
    { name: 'Vivacité', searchTerms: ['vivacite'] },
    { name: 'Musiq3', searchTerms: ['musiq3'] },
    { name: 'Pure FM', searchTerms: ['pure fm belgium'] },
    { name: 'Fun Radio Belgium', searchTerms: ['fun radio belgium'] },
    { name: 'Bel RTL', searchTerms: ['bel rtl'] },
    { name: 'Radio Contact', searchTerms: ['radio contact belgium'] },
    { name: 'Topradio', searchTerms: ['topradio'] },
    { name: 'VRT Nieuws', searchTerms: ['vrt nieuws'] },
    { name: 'Radio 1 RTBF', searchTerms: ['radio 1 rtbf'] },
  ],
  SE: [
    { name: 'Sveriges Radio P1', searchTerms: ['sr p1', 'sveriges radio p1'] },
    { name: 'Sveriges Radio P2', searchTerms: ['sr p2', 'sveriges radio p2'] },
    { name: 'Sveriges Radio P3', searchTerms: ['sr p3', 'sveriges radio p3'] },
    { name: 'Sveriges Radio P4', searchTerms: ['sr p4', 'sveriges radio p4'] },
    { name: 'Mix Megapol', searchTerms: ['mix megapol'] },
    { name: 'NRJ Sweden', searchTerms: ['nrj sweden'] },
    { name: 'Rix FM', searchTerms: ['rix fm'] },
    { name: 'Bandit Rock', searchTerms: ['bandit rock'] },
    { name: 'Lugna Favoriter', searchTerms: ['lugna favoriter'] },
    { name: 'Star FM Sweden', searchTerms: ['star fm sweden'] },
    { name: 'Rockklassiker', searchTerms: ['rockklassiker'] },
    { name: 'Vinyl FM', searchTerms: ['vinyl fm sweden'] },
    { name: 'Power Hit Radio', searchTerms: ['power hit radio'] },
    { name: 'Din Gata', searchTerms: ['din gata'] },
    { name: 'Retro FM Sweden', searchTerms: ['retro fm sweden'] },
    { name: 'Radio AF', searchTerms: ['radio af'] },
    { name: 'P5 STHLM', searchTerms: ['p5 sthlm'] },
    { name: 'Metropol', searchTerms: ['metropol sweden'] },
    { name: 'The Voice Sweden', searchTerms: ['the voice sweden'] },
    { name: 'Gold FM Sweden', searchTerms: ['gold fm sweden'] },
  ],
  NO: [
    { name: 'NRK P1', searchTerms: ['nrk p1'] },
    { name: 'NRK P2', searchTerms: ['nrk p2'] },
    { name: 'NRK P3', searchTerms: ['nrk p3'] },
    { name: 'P4 Norway', searchTerms: ['p4 norway', 'p4 radio'] },
    { name: 'Radio Norge', searchTerms: ['radio norge'] },
    { name: 'NRK mP3', searchTerms: ['nrk mp3'] },
    { name: 'NRK Klassisk', searchTerms: ['nrk klassisk'] },
    { name: 'NRK Jazz', searchTerms: ['nrk jazz'] },
    { name: 'P5 Hits', searchTerms: ['p5 hits'] },
    { name: 'Radio Rock', searchTerms: ['radio rock norway'] },
    { name: 'The Beat Norway', searchTerms: ['the beat norway'] },
    { name: 'Kiss FM Norway', searchTerms: ['kiss fm norway'] },
    { name: 'NRK Super', searchTerms: ['nrk super'] },
    { name: 'NRK Folkemusikk', searchTerms: ['nrk folkemusikk'] },
    { name: 'Radio Metro', searchTerms: ['radio metro norway'] },
    { name: 'P6 Rock', searchTerms: ['p6 rock'] },
    { name: 'P7 Klem', searchTerms: ['p7 klem'] },
    { name: 'P8 Pop', searchTerms: ['p8 pop'] },
    { name: 'P9 Retro', searchTerms: ['p9 retro'] },
    { name: 'NRK Nyheter', searchTerms: ['nrk nyheter'] },
  ],
  DK: [
    { name: 'DR P1', searchTerms: ['dr p1'] },
    { name: 'DR P2', searchTerms: ['dr p2'] },
    { name: 'DR P3', searchTerms: ['dr p3'] },
    { name: 'DR P4', searchTerms: ['dr p4'] },
    { name: 'DR P5', searchTerms: ['dr p5'] },
    { name: 'DR P6 Beat', searchTerms: ['dr p6 beat'] },
    { name: 'DR P8 Jazz', searchTerms: ['dr p8 jazz'] },
    { name: 'Nova FM Denmark', searchTerms: ['nova fm denmark'] },
    { name: 'The Voice Denmark', searchTerms: ['the voice denmark'] },
    { name: 'Radio Soft', searchTerms: ['radio soft'] },
    { name: 'Pop FM', searchTerms: ['pop fm denmark'] },
    { name: 'myROCK', searchTerms: ['myrock denmark'] },
    { name: 'Radio 100', searchTerms: ['radio 100 denmark'] },
    { name: 'Radio 4 Denmark', searchTerms: ['radio 4 denmark'] },
    { name: 'Radio24syv', searchTerms: ['radio24syv'] },
    { name: 'ANR Hit FM', searchTerms: ['anr hit fm'] },
    { name: 'Radio Viborg', searchTerms: ['radio viborg'] },
    { name: 'Radio Alfa', searchTerms: ['radio alfa denmark'] },
    { name: 'Klassisk DR', searchTerms: ['klassisk dr'] },
    { name: 'VLR', searchTerms: ['vlr radio'] },
  ],
  PL: [
    { name: 'Polskie Radio 1', searchTerms: ['polskie radio 1', 'jedynka'] },
    { name: 'Polskie Radio 2', searchTerms: ['polskie radio 2', 'dwójka'] },
    { name: 'Polskie Radio 3', searchTerms: ['polskie radio 3', 'trójka'] },
    { name: 'RMF FM', searchTerms: ['rmf fm'] },
    { name: 'Radio ZET', searchTerms: ['radio zet'] },
    { name: 'RMF Maxxx', searchTerms: ['rmf maxxx'] },
    { name: 'Eska Radio', searchTerms: ['eska radio'] },
    { name: 'Tok FM', searchTerms: ['tok fm'] },
    { name: 'Radio Maryja', searchTerms: ['radio maryja'] },
    { name: 'Radio Złote Przeboje', searchTerms: ['radio zlote przeboje'] },
    { name: 'Antyradio', searchTerms: ['antyradio'] },
    { name: 'Chillizet', searchTerms: ['chillizet'] },
    { name: 'Rock Radio', searchTerms: ['rock radio poland'] },
    { name: 'Radio Nowy Świat', searchTerms: ['radio nowy swiat'] },
    { name: 'Radio Plus', searchTerms: ['radio plus poland'] },
    { name: 'Radio Wawa', searchTerms: ['radio wawa'] },
    { name: 'Radio Eska Rock', searchTerms: ['eska rock'] },
    { name: 'RMF Classic', searchTerms: ['rmf classic'] },
    { name: 'VOX FM', searchTerms: ['vox fm poland'] },
    { name: 'Radio Pogoda', searchTerms: ['radio pogoda'] },
  ],
  PT: [
    { name: 'RTP Antena 1', searchTerms: ['antena 1 portugal'] },
    { name: 'RTP Antena 2', searchTerms: ['antena 2 portugal'] },
    { name: 'RTP Antena 3', searchTerms: ['antena 3 portugal'] },
    { name: 'RFM', searchTerms: ['rfm portugal'] },
    { name: 'Rádio Comercial', searchTerms: ['radio comercial'] },
    { name: 'Renascença', searchTerms: ['renascenca', 'radio renascenca'] },
    { name: 'TSF Rádio Notícias', searchTerms: ['tsf radio'] },
    { name: 'M80', searchTerms: ['m80 portugal'] },
    { name: 'Mega Hits', searchTerms: ['mega hits portugal'] },
    { name: 'Rádio Cidade', searchTerms: ['radio cidade portugal'] },
    { name: 'Smooth FM Portugal', searchTerms: ['smooth fm portugal'] },
    { name: 'Vodafone FM', searchTerms: ['vodafone fm'] },
    { name: 'Oxigénio', searchTerms: ['oxigenio radio'] },
    { name: 'Rádio Observador', searchTerms: ['radio observador'] },
    { name: 'Best Rock FM', searchTerms: ['best rock fm portugal'] },
    { name: 'Rádio Festival', searchTerms: ['radio festival portugal'] },
    { name: 'Rádio Sim', searchTerms: ['radio sim'] },
    { name: 'RUM', searchTerms: ['rum radio'] },
    { name: 'Radar', searchTerms: ['radar radio portugal'] },
    { name: 'Rádio Nostalgia', searchTerms: ['radio nostalgia portugal'] },
  ],
  AR: [
    { name: 'Radio Mitre', searchTerms: ['radio mitre'] },
    { name: 'La 100', searchTerms: ['la 100'] },
    { name: 'Radio Continental', searchTerms: ['radio continental argentina'] },
    { name: 'Metro 95.1', searchTerms: ['metro 95.1'] },
    { name: 'Rock & Pop', searchTerms: ['rock and pop argentina'] },
    { name: 'Los 40 Argentina', searchTerms: ['los 40 argentina'] },
    { name: 'Radio Disney Argentina', searchTerms: ['radio disney argentina'] },
    { name: 'Aspen 102.3', searchTerms: ['aspen 102.3'] },
    { name: 'Pop Radio', searchTerms: ['pop radio argentina'] },
    { name: 'Radio 10', searchTerms: ['radio 10 argentina'] },
    { name: 'Vorterix', searchTerms: ['vorterix'] },
    { name: 'Nacional Rock', searchTerms: ['nacional rock'] },
    { name: 'Radio Nacional', searchTerms: ['radio nacional argentina'] },
    { name: 'Radio Del Plata', searchTerms: ['radio del plata'] },
    { name: 'Blue FM', searchTerms: ['blue fm argentina'] },
    { name: 'Cadena 3', searchTerms: ['cadena 3'] },
    { name: 'FM Hit', searchTerms: ['fm hit argentina'] },
    { name: 'Vale 97.5', searchTerms: ['vale 97.5'] },
    { name: 'Radio Rivadavia', searchTerms: ['radio rivadavia'] },
    { name: 'La Red', searchTerms: ['la red argentina'] },
  ],
  CL: [
    { name: 'Radio Cooperativa', searchTerms: ['radio cooperativa'] },
    { name: 'Radio Bío-Bío', searchTerms: ['radio bio bio'] },
    { name: 'ADN Radio', searchTerms: ['adn radio chile'] },
    { name: 'Radio Agricultura', searchTerms: ['radio agricultura'] },
    { name: 'Los 40 Chile', searchTerms: ['los 40 chile'] },
    { name: 'Radio Corazón', searchTerms: ['radio corazon chile'] },
    { name: 'Rock & Pop Chile', searchTerms: ['rock and pop chile'] },
    { name: 'FM Dos', searchTerms: ['fm dos'] },
    { name: 'Radio Futuro', searchTerms: ['radio futuro chile'] },
    { name: 'Duna FM', searchTerms: ['duna fm'] },
    { name: 'Radio Activa', searchTerms: ['radio activa chile'] },
    { name: 'Oasis FM', searchTerms: ['oasis fm chile'] },
    { name: 'Radio Carolina', searchTerms: ['radio carolina chile'] },
    { name: 'Radio Universo', searchTerms: ['radio universo'] },
    { name: 'Radio Concierto', searchTerms: ['radio concierto'] },
    { name: 'Pudahuel FM', searchTerms: ['pudahuel fm'] },
    { name: 'Radio Zero', searchTerms: ['radio zero chile'] },
    { name: 'Play FM', searchTerms: ['play fm chile'] },
    { name: 'Radio Romántica', searchTerms: ['radio romantica chile'] },
    { name: 'Tele 13 Radio', searchTerms: ['tele 13 radio'] },
  ],
  CO: [
    { name: 'Caracol Radio', searchTerms: ['caracol radio'] },
    { name: 'RCN Radio', searchTerms: ['rcn radio'] },
    { name: 'La FM', searchTerms: ['la fm colombia'] },
    { name: 'Blu Radio', searchTerms: ['blu radio'] },
    { name: 'Los 40 Colombia', searchTerms: ['los 40 colombia'] },
    { name: 'La W Radio', searchTerms: ['la w radio'] },
    { name: 'Tropicana', searchTerms: ['tropicana colombia'] },
    { name: 'Olímpica Stereo', searchTerms: ['olimpica stereo'] },
    { name: 'La Mega', searchTerms: ['la mega colombia'] },
    { name: 'Radio Tiempo', searchTerms: ['radio tiempo'] },
    { name: 'Candela Stereo', searchTerms: ['candela stereo'] },
    { name: 'Vibra Bogotá', searchTerms: ['vibra bogota'] },
    { name: 'Radio Uno', searchTerms: ['radio uno colombia'] },
    { name: 'La Vallenata', searchTerms: ['la vallenata'] },
    { name: 'Radioacktiva', searchTerms: ['radioacktiva'] },
    { name: 'Los 40 Urban', searchTerms: ['los 40 urban colombia'] },
    { name: 'Bésame Radio', searchTerms: ['besame radio'] },
    { name: 'Radio Nacional de Colombia', searchTerms: ['radio nacional colombia'] },
    { name: 'Oxígeno FM', searchTerms: ['oxigeno fm colombia'] },
    { name: 'Radio Santa Fe', searchTerms: ['radio santa fe'] },
  ],
  ID: [
    { name: 'Prambors FM', searchTerms: ['prambors fm'] },
    { name: 'Hard Rock FM', searchTerms: ['hard rock fm indonesia'] },
    { name: 'Trax FM', searchTerms: ['trax fm'] },
    { name: 'Gen FM', searchTerms: ['gen fm'] },
    { name: 'I-Radio', searchTerms: ['i-radio indonesia'] },
    { name: 'Delta FM', searchTerms: ['delta fm jakarta'] },
    { name: 'Mustang FM', searchTerms: ['mustang fm'] },
    { name: 'Sonora FM', searchTerms: ['sonora fm'] },
    { name: 'Elshinta', searchTerms: ['elshinta'] },
    { name: 'RRI Pro 1', searchTerms: ['rri pro 1'] },
    { name: 'RRI Pro 2', searchTerms: ['rri pro 2'] },
    { name: 'RRI Pro 3', searchTerms: ['rri pro 3'] },
    { name: 'Jak FM', searchTerms: ['jak fm'] },
    { name: 'Smart FM', searchTerms: ['smart fm indonesia'] },
    { name: 'Bens Radio', searchTerms: ['bens radio'] },
    { name: 'Oz Radio', searchTerms: ['oz radio'] },
    { name: 'Kiss FM Indonesia', searchTerms: ['kiss fm indonesia'] },
    { name: 'Radio Dangdut', searchTerms: ['radio dangdut indonesia'] },
    { name: 'M Radio', searchTerms: ['m radio surabaya'] },
    { name: 'Motion FM', searchTerms: ['motion fm'] },
  ],
  TH: [
    { name: 'MCOT Radio', searchTerms: ['mcot radio'] },
    { name: 'FM 91 Trafficpro', searchTerms: ['fm 91 trafficpro'] },
    { name: 'Green Wave 106.5', searchTerms: ['green wave 106.5'] },
    { name: 'EFM 94', searchTerms: ['efm 94'] },
    { name: 'Cool FM', searchTerms: ['cool fm thailand'] },
    { name: 'Cat Radio', searchTerms: ['cat radio thailand'] },
    { name: 'Eazy FM', searchTerms: ['eazy fm thailand'] },
    { name: 'Get 102.5', searchTerms: ['get 102.5'] },
    { name: 'Virgin Hitz', searchTerms: ['virgin hitz'] },
    { name: 'Chill FM', searchTerms: ['chill fm thailand'] },
    { name: 'Seed 97.5', searchTerms: ['seed 97.5'] },
    { name: 'Red FM Thailand', searchTerms: ['red fm thailand'] },
    { name: 'Met 107', searchTerms: ['met 107'] },
    { name: 'Radio Thailand', searchTerms: ['radio thailand'] },
    { name: 'FM One', searchTerms: ['fm one thailand'] },
    { name: 'Active Radio', searchTerms: ['active radio thailand'] },
    { name: 'Banana FM', searchTerms: ['banana fm thailand'] },
    { name: 'Fat Radio', searchTerms: ['fat radio'] },
    { name: 'Smooth FM Thailand', searchTerms: ['smooth fm thailand'] },
    { name: 'Thai PBS Radio', searchTerms: ['thai pbs radio'] },
  ],
  PH: [
    { name: 'DZRH', searchTerms: ['dzrh'] },
    { name: 'DZMM', searchTerms: ['dzmm'] },
    { name: 'DWIZ', searchTerms: ['dwiz'] },
    { name: 'Monster Radio RX 93.1', searchTerms: ['monster radio rx 93.1'] },
    { name: 'Magic 89.9', searchTerms: ['magic 89.9'] },
    { name: 'Wave 89.1', searchTerms: ['wave 89.1'] },
    { name: 'Energy FM', searchTerms: ['energy fm philippines'] },
    { name: 'Love Radio', searchTerms: ['love radio philippines'] },
    { name: 'Wish 107.5', searchTerms: ['wish 107.5'] },
    { name: 'MOR 101.9', searchTerms: ['mor 101.9'] },
    { name: 'Yes FM', searchTerms: ['yes fm philippines'] },
    { name: '97.9 Home Radio', searchTerms: ['home radio 97.9'] },
    { name: 'iFM', searchTerms: ['ifm philippines'] },
    { name: 'Easy Rock', searchTerms: ['easy rock'] },
    { name: 'Barangay LS', searchTerms: ['barangay ls'] },
    { name: 'DWKB', searchTerms: ['dwkb'] },
    { name: 'Radyo5', searchTerms: ['radyo5'] },
    { name: 'DZBB', searchTerms: ['dzbb'] },
    { name: 'FM1', searchTerms: ['fm1 philippines'] },
    { name: 'K-Lite FM', searchTerms: ['k-lite fm'] },
  ],
  MY: [
    { name: 'Hitz FM', searchTerms: ['hitz fm malaysia'] },
    { name: 'Mix FM', searchTerms: ['mix fm malaysia'] },
    { name: 'Era FM', searchTerms: ['era fm'] },
    { name: 'Hot FM', searchTerms: ['hot fm malaysia'] },
    { name: 'Fly FM', searchTerms: ['fly fm'] },
    { name: 'Suria FM', searchTerms: ['suria fm'] },
    { name: 'Red FM Malaysia', searchTerms: ['red fm malaysia'] },
    { name: 'Lite FM', searchTerms: ['lite fm malaysia'] },
    { name: 'BFM 89.9', searchTerms: ['bfm 89.9'] },
    { name: 'Traxx FM', searchTerms: ['traxx fm'] },
    { name: 'Klasik Nasional', searchTerms: ['klasik nasional'] },
    { name: 'My FM', searchTerms: ['my fm malaysia'] },
    { name: '988 FM', searchTerms: ['988 fm'] },
    { name: 'One FM', searchTerms: ['one fm malaysia'] },
    { name: 'Capital FM Malaysia', searchTerms: ['capital fm malaysia'] },
    { name: 'Ai FM', searchTerms: ['ai fm'] },
    { name: 'Minnal FM', searchTerms: ['minnal fm'] },
    { name: 'THR Raaga', searchTerms: ['thr raaga'] },
    { name: 'Bernama Radio', searchTerms: ['bernama radio'] },
    { name: 'Nasional FM', searchTerms: ['nasional fm'] },
  ],
  SG: [
    { name: 'Class 95', searchTerms: ['class 95'] },
    { name: 'Gold 905', searchTerms: ['gold 905'] },
    { name: 'Kiss 92', searchTerms: ['kiss 92 singapore'] },
    { name: '987 FM', searchTerms: ['987 fm'] },
    { name: 'Lush 99.5', searchTerms: ['lush 99.5'] },
    { name: 'Symphony 924', searchTerms: ['symphony 924'] },
    { name: 'Power 98', searchTerms: ['power 98 singapore'] },
    { name: 'Love 97.2 FM', searchTerms: ['love 97.2 fm'] },
    { name: 'Yes 933', searchTerms: ['yes 933'] },
    { name: 'Capital 958', searchTerms: ['capital 958'] },
    { name: 'UFM 100.3', searchTerms: ['ufm 100.3'] },
    { name: 'Oli 96.8', searchTerms: ['oli 96.8'] },
    { name: 'Ria 89.7', searchTerms: ['ria 89.7'] },
    { name: 'Warna 94.2', searchTerms: ['warna 94.2'] },
    { name: 'ONE FM', searchTerms: ['one fm singapore'] },
    { name: 'CNA 938', searchTerms: ['cna 938'] },
    { name: 'So Drama', searchTerms: ['so drama'] },
    { name: 'Hot FM Singapore', searchTerms: ['hot fm singapore'] },
    { name: 'Radio 100.9', searchTerms: ['radio 100.9 singapore'] },
    { name: 'SPH Radio', searchTerms: ['sph radio'] },
  ],
  ZA: [
    { name: '5FM', searchTerms: ['5fm'] },
    { name: 'Metro FM', searchTerms: ['metro fm south africa'] },
    { name: 'Jacaranda FM', searchTerms: ['jacaranda fm'] },
    { name: 'Kaya FM', searchTerms: ['kaya fm'] },
    { name: '947', searchTerms: ['947 radio'] },
    { name: 'Good Hope FM', searchTerms: ['good hope fm'] },
    { name: 'East Coast Radio', searchTerms: ['east coast radio'] },
    { name: 'Heart FM', searchTerms: ['heart fm south africa'] },
    { name: 'KFM', searchTerms: ['kfm 94.5'] },
    { name: 'Cape Talk', searchTerms: ['cape talk'] },
    { name: '702', searchTerms: ['702 radio'] },
    { name: 'Classic FM South Africa', searchTerms: ['classic fm south africa'] },
    { name: 'Gagasi FM', searchTerms: ['gagasi fm'] },
    { name: 'Umhlobo Wenene', searchTerms: ['umhlobo wenene'] },
    { name: 'Ukhozi FM', searchTerms: ['ukhozi fm'] },
    { name: 'Lesedi FM', searchTerms: ['lesedi fm'] },
    { name: 'Thobela FM', searchTerms: ['thobela fm'] },
    { name: 'RSG', searchTerms: ['rsg radio'] },
    { name: 'SAfm', searchTerms: ['safm'] },
    { name: 'Power FM', searchTerms: ['power fm south africa'] },
  ],
  NG: [
    { name: 'Wazobia FM', searchTerms: ['wazobia fm'] },
    { name: 'Cool FM', searchTerms: ['cool fm nigeria'] },
    { name: 'Beat FM', searchTerms: ['beat fm nigeria'] },
    { name: 'City FM', searchTerms: ['city fm lagos'] },
    { name: 'Naija FM', searchTerms: ['naija fm'] },
    { name: 'Rhythm FM', searchTerms: ['rhythm fm nigeria'] },
    { name: 'Inspiration FM', searchTerms: ['inspiration fm'] },
    { name: 'Classic FM Nigeria', searchTerms: ['classic fm nigeria'] },
    { name: 'Soundcity Radio', searchTerms: ['soundcity radio'] },
    { name: 'Nigeria Info FM', searchTerms: ['nigeria info fm'] },
    { name: 'Ray Power', searchTerms: ['ray power'] },
    { name: 'Brila FM', searchTerms: ['brila fm'] },
    { name: 'Love FM Nigeria', searchTerms: ['love fm nigeria'] },
    { name: 'Traffic Radio', searchTerms: ['traffic radio nigeria'] },
    { name: 'Atlantic FM', searchTerms: ['atlantic fm nigeria'] },
    { name: 'Continental FM', searchTerms: ['continental fm nigeria'] },
    { name: 'Eko FM', searchTerms: ['eko fm'] },
    { name: 'Metro FM Nigeria', searchTerms: ['metro fm nigeria'] },
    { name: 'Raypower FM', searchTerms: ['raypower fm'] },
    { name: 'Hot FM Nigeria', searchTerms: ['hot fm nigeria'] },
  ],
  EG: [
    { name: 'Nile FM', searchTerms: ['nile fm'] },
    { name: 'Nogoum FM', searchTerms: ['nogoum fm'] },
    { name: 'Mega FM', searchTerms: ['mega fm egypt'] },
    { name: 'Shaabi FM', searchTerms: ['shaabi fm'] },
    { name: 'Radio Masr', searchTerms: ['radio masr'] },
    { name: 'Energy FM Egypt', searchTerms: ['energy fm egypt'] },
    { name: 'Radio Hits', searchTerms: ['radio hits egypt'] },
    { name: 'Al Nas', searchTerms: ['al nas radio'] },
    { name: 'Quran Radio Egypt', searchTerms: ['quran radio egypt'] },
    { name: 'Nagham FM', searchTerms: ['nagham fm'] },
    { name: 'Radio Cairo', searchTerms: ['radio cairo'] },
    { name: 'ERTU Radio', searchTerms: ['ertu radio'] },
    { name: 'El Gouna Radio', searchTerms: ['el gouna radio'] },
    { name: 'Mix FM Egypt', searchTerms: ['mix fm egypt'] },
    { name: 'Radio 9090', searchTerms: ['radio 9090'] },
    { name: 'Diwan FM', searchTerms: ['diwan fm'] },
    { name: 'Albait Baitak', searchTerms: ['albait baitak'] },
    { name: 'Radio Misr', searchTerms: ['radio misr'] },
    { name: 'Star Radio Egypt', searchTerms: ['star radio egypt'] },
    { name: 'Cairo Nights FM', searchTerms: ['cairo nights fm'] },
  ],
  AE: [
    { name: 'Virgin Radio Dubai', searchTerms: ['virgin radio dubai'] },
    { name: 'Dubai 92', searchTerms: ['dubai 92'] },
    { name: 'Dubai Eye', searchTerms: ['dubai eye'] },
    { name: 'Hit 96.7', searchTerms: ['hit 96.7'] },
    { name: 'Tag 91.1', searchTerms: ['tag 91.1'] },
    { name: 'Radio 1 UAE', searchTerms: ['radio 1 uae'] },
    { name: 'Radio 2 UAE', searchTerms: ['radio 2 uae'] },
    { name: 'Al Arabiya FM', searchTerms: ['al arabiya fm'] },
    { name: 'Emarat FM', searchTerms: ['emarat fm'] },
    { name: 'Al Khaleejiya', searchTerms: ['al khaleejiya'] },
    { name: 'Star FM UAE', searchTerms: ['star fm uae'] },
    { name: 'Asianet Radio', searchTerms: ['asianet radio'] },
    { name: 'City 101.6', searchTerms: ['city 101.6'] },
    { name: 'Suno FM', searchTerms: ['suno fm uae'] },
    { name: 'Capital Radio Dubai', searchTerms: ['capital radio dubai'] },
    { name: 'Abu Dhabi FM', searchTerms: ['abu dhabi fm'] },
    { name: 'Radio Shoma', searchTerms: ['radio shoma'] },
    { name: 'Pulse 95', searchTerms: ['pulse 95'] },
    { name: 'RJ FM', searchTerms: ['rj fm dubai'] },
    { name: 'Quran Kareem Radio', searchTerms: ['quran kareem radio'] },
  ],
  SA: [
    { name: 'Saudi Radio', searchTerms: ['saudi radio'] },
    { name: 'Rotana FM', searchTerms: ['rotana fm'] },
    { name: 'MBC FM', searchTerms: ['mbc fm'] },
    { name: 'Mix FM Saudi', searchTerms: ['mix fm saudi'] },
    { name: 'UFM Saudi', searchTerms: ['ufm saudi'] },
    { name: 'Panorama FM', searchTerms: ['panorama fm saudi'] },
    { name: 'Radio Sawa', searchTerms: ['radio sawa saudi'] },
    { name: 'Al Riyadh Radio', searchTerms: ['al riyadh radio'] },
    { name: 'Al Quran Radio', searchTerms: ['al quran radio saudi'] },
    { name: 'Jeddah FM', searchTerms: ['jeddah fm'] },
    { name: 'Al Midan Radio', searchTerms: ['al midan radio'] },
    { name: 'Saudi Sports Radio', searchTerms: ['saudi sports radio'] },
    { name: 'Alif Alif FM', searchTerms: ['alif alif fm'] },
    { name: 'Radio Nagham', searchTerms: ['radio nagham saudi'] },
    { name: 'Hit Radio Saudi', searchTerms: ['hit radio saudi'] },
    { name: 'Virgin Radio Saudi', searchTerms: ['virgin radio saudi'] },
    { name: 'Al Arabiya Radio', searchTerms: ['al arabiya radio saudi'] },
    { name: 'Tarab FM', searchTerms: ['tarab fm'] },
    { name: 'Saudi Youth Radio', searchTerms: ['saudi youth radio'] },
    { name: 'Al Sunnah Radio', searchTerms: ['al sunnah radio'] },
  ],
  PK: [
    { name: 'FM 101', searchTerms: ['fm 101 pakistan'] },
    { name: 'FM 103', searchTerms: ['fm 103 pakistan'] },
    { name: 'Radio Pakistan', searchTerms: ['radio pakistan'] },
    { name: 'City FM 89', searchTerms: ['city fm 89'] },
    { name: 'FM 91', searchTerms: ['fm 91 pakistan'] },
    { name: 'Samaa FM', searchTerms: ['samaa fm'] },
    { name: 'Mast FM 103', searchTerms: ['mast fm 103'] },
    { name: 'Hot FM 105', searchTerms: ['hot fm 105'] },
    { name: 'Power 99', searchTerms: ['power 99 pakistan'] },
    { name: 'Josh FM', searchTerms: ['josh fm'] },
    { name: 'Hum FM', searchTerms: ['hum fm'] },
    { name: 'Awaz FM', searchTerms: ['awaz fm'] },
    { name: 'Apna Karachi 107', searchTerms: ['apna karachi 107'] },
    { name: 'Sunrise FM', searchTerms: ['sunrise fm pakistan'] },
    { name: 'FM 100 Pakistan', searchTerms: ['fm 100 pakistan'] },
    { name: 'Radio One Pakistan', searchTerms: ['radio one pakistan'] },
    { name: 'FM 94.6', searchTerms: ['fm 94.6 pakistan'] },
    { name: 'FM 106.2', searchTerms: ['fm 106.2 pakistan'] },
    { name: 'Suno FM Pakistan', searchTerms: ['suno fm pakistan'] },
    { name: 'Lahore FM', searchTerms: ['lahore fm'] },
  ],
};

export const getCountriesWithCuratedStations = (): string[] => {
  return Object.keys(CURATED_STATIONS);
};

export const getCuratedStationsForCountry = (countryCode: string): CuratedStation[] => {
  return CURATED_STATIONS[countryCode.toUpperCase()] || [];
};
