import { Platform } from "react-native";

export type ThemeName = 
  | 'fluent' | 'fluentDark' | 'nightAmoled' | 'warmNeutral' | 'coolBlue'
  // Winamp themes
  | 'winampClassic' | 'winampModern' | 'bento' | 'bigBento' | 'mmd3' | 'topaz' | 'retroPixel' | 'alienGreen' | 'bubblegumPink' | 'milkdrop'
  // iTunes themes
  | 'itunesClassic' | 'itunesBrushedMetal' | 'itunesAqua'
  // iOS themes
  | 'iosWhite' | 'iosDark' | 'iosMinimal' | 'frostedGlass'
  // Windows Media Player themes
  | 'wmpClassic' | 'wmpBlue' | 'wmpSilver' | 'vistaAero' | 'aeroGlass' | 'vistaBlack'
  // Zune themes
  | 'zuneDark' | 'zuneBrown' | 'zuneRed'
  // Android Material themes
  | 'materialLight' | 'materialDark' | 'materialYou' | 'holoLight' | 'holoDark' | 'kitkatMusic' | 'jellyBeanMusic'
  // Samsung themes
  | 'samsungTouchWiz' | 'samsungNatureUX' | 'samsungGraceUX' | 'samsungOneUI' | 'samsungAmoled'
  // Third-party player themes
  | 'powerampDark' | 'powerampFlat' | 'powerampTransparent' | 'blackplayerDark' | 'blackplayerAmoled' | 'phonographMaterial'
  // Specialty themes
  | 'amoledBlack' | 'darkGlass' | 'carbonFiber' | 'silverMetallic' | 'midnight' | 'minimalMono';

interface ThemeSeed {
  primary: string;
  secondary: string;
  accent: string;
  text: string;
  textSecondary: string;
  backgroundRoot: string;
  backgroundDefault: string;
  surface: string;
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : { r: 0, g: 0, b: 0 };
}

function lighten(hex: string, amount: number): string {
  const { r, g, b } = hexToRgb(hex);
  const newR = Math.min(255, Math.round(r + (255 - r) * amount));
  const newG = Math.min(255, Math.round(g + (255 - g) * amount));
  const newB = Math.min(255, Math.round(b + (255 - b) * amount));
  return `#${newR.toString(16).padStart(2, '0')}${newG.toString(16).padStart(2, '0')}${newB.toString(16).padStart(2, '0')}`.toUpperCase();
}

function darken(hex: string, amount: number): string {
  const { r, g, b } = hexToRgb(hex);
  const newR = Math.max(0, Math.round(r * (1 - amount)));
  const newG = Math.max(0, Math.round(g * (1 - amount)));
  const newB = Math.max(0, Math.round(b * (1 - amount)));
  return `#${newR.toString(16).padStart(2, '0')}${newG.toString(16).padStart(2, '0')}${newB.toString(16).padStart(2, '0')}`.toUpperCase();
}

function generateDarkPalette(seed: ThemeSeed) {
  const { r, g, b } = hexToRgb(seed.primary);
  return {
    text: seed.text,
    textSecondary: seed.textSecondary,
    textTertiary: darken(seed.textSecondary, 0.3),
    buttonText: "#000000",
    tabIconDefault: darken(seed.textSecondary, 0.3),
    tabIconSelected: seed.primary,
    link: seed.primary,
    primary: seed.primary,
    primaryHover: lighten(seed.primary, 0.1),
    primaryPressed: darken(seed.primary, 0.1),
    primaryContainer: darken(seed.primary, 0.6),
    onPrimaryContainer: lighten(seed.primary, 0.8),
    secondary: seed.secondary,
    secondaryContainer: darken(seed.secondary, 0.7),
    onSecondaryContainer: lighten(seed.secondary, 0.85),
    tertiary: lighten(seed.secondary, 0.3),
    tertiaryContainer: darken(seed.accent, 0.65),
    onTertiaryContainer: lighten(seed.accent, 0.85),
    accent: seed.accent,
    backgroundRoot: seed.backgroundRoot,
    backgroundDefault: seed.backgroundDefault,
    backgroundSecondary: lighten(seed.backgroundDefault, 0.05),
    backgroundTertiary: lighten(seed.backgroundDefault, 0.1),
    surface: seed.surface,
    surfaceVariant: lighten(seed.surface, 0.05),
    surfaceContainerLowest: darken(seed.backgroundRoot, 0.3),
    surfaceContainerLow: seed.backgroundRoot,
    surfaceContainer: lighten(seed.surface, 0.08),
    surfaceContainerHigh: lighten(seed.surface, 0.12),
    surfaceContainerHighest: lighten(seed.surface, 0.16),
    outline: lighten(seed.surface, 0.2),
    outlineVariant: lighten(seed.surface, 0.1),
    stroke1: lighten(seed.surface, 0.2),
    stroke2: lighten(seed.surface, 0.1),
    recordButton: "#F97316",
    success: "#22C55E",
    warning: "#F59E0B",
    error: "#EF4444",
    errorContainer: "#93000A",
    onError: "#601410",
    onErrorContainer: "#FFDAD6",
    info: seed.primary,
    onPrimary: "#000000",
    onSecondary: "#000000",
    onSurface: seed.text,
    onSurfaceVariant: seed.textSecondary,
    inverseSurface: seed.text,
    inverseOnSurface: seed.backgroundRoot,
    inversePrimary: darken(seed.primary, 0.3),
    elevation1: `rgba(${r}, ${g}, ${b}, 0.03)`,
    elevation2: `rgba(${r}, ${g}, ${b}, 0.05)`,
    elevation3: `rgba(${r}, ${g}, ${b}, 0.08)`,
    scrim: "rgba(0, 0, 0, 0.7)",
    divider: lighten(seed.surface, 0.1),
    cardBackground: seed.surface,
    cardBorder: lighten(seed.surface, 0.1),
  };
}

function generateLightPalette(seed: ThemeSeed) {
  const { r, g, b } = hexToRgb(seed.primary);
  return {
    text: "#1C1C1E",
    textSecondary: "#5F6368",
    textTertiary: "#9AA0A6",
    buttonText: "#FFFFFF",
    tabIconDefault: "#9AA0A6",
    tabIconSelected: seed.primary,
    link: seed.primary,
    primary: seed.primary,
    primaryHover: darken(seed.primary, 0.1),
    primaryPressed: darken(seed.primary, 0.2),
    primaryContainer: lighten(seed.primary, 0.85),
    onPrimaryContainer: darken(seed.primary, 0.6),
    secondary: seed.secondary,
    secondaryContainer: lighten(seed.secondary, 0.85),
    onSecondaryContainer: darken(seed.secondary, 0.65),
    tertiary: lighten(seed.secondary, 0.3),
    tertiaryContainer: lighten(seed.accent, 0.85),
    onTertiaryContainer: darken(seed.accent, 0.65),
    accent: seed.accent,
    backgroundRoot: "#FFFFFF",
    backgroundDefault: "#F7F9FC",
    backgroundSecondary: "#EEF2F7",
    backgroundTertiary: "#E6EBF2",
    surface: "#FFFFFF",
    surfaceVariant: "#F2F5FA",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F7F9FC",
    surfaceContainer: "#EEF2F7",
    surfaceContainerHigh: "#E6EBF2",
    surfaceContainerHighest: "#E6EBF2",
    outline: "#CDD5DF",
    outlineVariant: "#E3E8EF",
    stroke1: "#CDD5DF",
    stroke2: "#E3E8EF",
    recordButton: "#F97316",
    success: "#1E8E3E",
    warning: "#E37400",
    error: "#C5221F",
    errorContainer: "#FFDAD6",
    onError: "#FFFFFF",
    onErrorContainer: "#410002",
    info: seed.primary,
    onPrimary: "#FFFFFF",
    onSecondary: "#FFFFFF",
    onSurface: "#1C1C1E",
    onSurfaceVariant: "#5F6368",
    inverseSurface: "#1C1C1E",
    inverseOnSurface: "#FFFFFF",
    inversePrimary: seed.primary,
    elevation1: `rgba(${r}, ${g}, ${b}, 0.02)`,
    elevation2: `rgba(${r}, ${g}, ${b}, 0.04)`,
    elevation3: `rgba(${r}, ${g}, ${b}, 0.06)`,
    scrim: "rgba(0, 0, 0, 0.4)",
    divider: "#E5E7EB",
    cardBackground: "#FFFFFF",
    cardBorder: "#E3E8EF",
  };
}

const darkSeeds: Record<string, ThemeSeed> = {
  // Winamp themes
  winampClassic: { primary: "#00FF00", secondary: "#66FF66", accent: "#00CC00", text: "#00FF00", textSecondary: "#66CC66", backgroundRoot: "#232323", backgroundDefault: "#2B2B2B", surface: "#2B2B2B" },
  winampModern: { primary: "#FF6600", secondary: "#FF9933", accent: "#CC5200", text: "#FFFFFF", textSecondary: "#CCCCCC", backgroundRoot: "#1A1A1A", backgroundDefault: "#242424", surface: "#242424" },
  bento: { primary: "#4A90D9", secondary: "#6BA5E7", accent: "#2E7BC7", text: "#E0E6ED", textSecondary: "#8899A6", backgroundRoot: "#1C2833", backgroundDefault: "#253341", surface: "#253341" },
  bigBento: { primary: "#5C9CE6", secondary: "#7DB3F0", accent: "#3D7CC7", text: "#F0F4F8", textSecondary: "#A0B0C0", backgroundRoot: "#141E28", backgroundDefault: "#1E2A36", surface: "#1E2A36" },
  mmd3: { primary: "#00BFFF", secondary: "#33CCFF", accent: "#0099CC", text: "#FFFFFF", textSecondary: "#B0C4DE", backgroundRoot: "#0D1117", backgroundDefault: "#161B22", surface: "#161B22" },
  topaz: { primary: "#FFD700", secondary: "#FFEB3B", accent: "#FFC107", text: "#FFFFFF", textSecondary: "#E0C070", backgroundRoot: "#1A1500", backgroundDefault: "#2A2200", surface: "#2A2200" },
  retroPixel: { primary: "#00FF00", secondary: "#33FF33", accent: "#00CC00", text: "#00FF00", textSecondary: "#00AA00", backgroundRoot: "#001100", backgroundDefault: "#002200", surface: "#002200" },
  alienGreen: { primary: "#39FF14", secondary: "#66FF44", accent: "#2ECC10", text: "#39FF14", textSecondary: "#66CC44", backgroundRoot: "#0A1A00", backgroundDefault: "#142800", surface: "#142800" },
  bubblegumPink: { primary: "#FF77AA", secondary: "#FF99BB", accent: "#FF5599", text: "#FFFFFF", textSecondary: "#FFCCDD", backgroundRoot: "#1A0A12", backgroundDefault: "#2D1420", surface: "#2D1420" },
  milkdrop: { primary: "#FF00FF", secondary: "#FF66FF", accent: "#CC00CC", text: "#FF00FF", textSecondary: "#CC66CC", backgroundRoot: "#0D000D", backgroundDefault: "#1A001A", surface: "#1A001A" },
  // iTunes themes
  itunesClassic: { primary: "#1DB954", secondary: "#1ED760", accent: "#18A449", text: "#FFFFFF", textSecondary: "#B3B3B3", backgroundRoot: "#121212", backgroundDefault: "#181818", surface: "#282828" },
  itunesBrushedMetal: { primary: "#0066CC", secondary: "#3399FF", accent: "#0055AA", text: "#333333", textSecondary: "#666666", backgroundRoot: "#C0C0C0", backgroundDefault: "#D4D4D4", surface: "#E8E8E8" },
  itunesAqua: { primary: "#007AFF", secondary: "#5AC8FA", accent: "#0062CC", text: "#FFFFFF", textSecondary: "#A0D0FF", backgroundRoot: "#0A4D8C", backgroundDefault: "#0D5FA3", surface: "#1A6FB8" },
  // iOS themes
  iosWhite: { primary: "#007AFF", secondary: "#5AC8FA", accent: "#0062CC", text: "#000000", textSecondary: "#8E8E93", backgroundRoot: "#FFFFFF", backgroundDefault: "#F2F2F7", surface: "#FFFFFF" },
  iosDark: { primary: "#0A84FF", secondary: "#64D2FF", accent: "#0062CC", text: "#FFFFFF", textSecondary: "#8E8E93", backgroundRoot: "#000000", backgroundDefault: "#1C1C1E", surface: "#2C2C2E" },
  iosMinimal: { primary: "#000000", secondary: "#3A3A3C", accent: "#1C1C1E", text: "#000000", textSecondary: "#8E8E93", backgroundRoot: "#FFFFFF", backgroundDefault: "#F2F2F7", surface: "#FFFFFF" },
  frostedGlass: { primary: "#007AFF", secondary: "#5AC8FA", accent: "#0062CC", text: "#FFFFFF", textSecondary: "#A0C8E8", backgroundRoot: "#1A1A2E", backgroundDefault: "#252542", surface: "#2D2D4A" },
  // Windows Media Player themes
  wmpClassic: { primary: "#0078D4", secondary: "#40A0FF", accent: "#0066B8", text: "#000000", textSecondary: "#666666", backgroundRoot: "#D4D0C8", backgroundDefault: "#ECE9D8", surface: "#FFFFFF" },
  wmpBlue: { primary: "#0078D7", secondary: "#1E90FF", accent: "#0063B1", text: "#FFFFFF", textSecondary: "#90C8F0", backgroundRoot: "#001A33", backgroundDefault: "#002850", surface: "#003366" },
  wmpSilver: { primary: "#0078D4", secondary: "#40A0FF", accent: "#0066B8", text: "#000000", textSecondary: "#555555", backgroundRoot: "#C0C0C0", backgroundDefault: "#D8D8D8", surface: "#E8E8E8" },
  vistaAero: { primary: "#00B4D8", secondary: "#48CAE4", accent: "#0096C7", text: "#FFFFFF", textSecondary: "#90E0EF", backgroundRoot: "#001219", backgroundDefault: "#001824", surface: "#002030" },
  aeroGlass: { primary: "#3399FF", secondary: "#66B2FF", accent: "#1A8CFF", text: "#FFFFFF", textSecondary: "#B0D4FF", backgroundRoot: "#1A2A40", backgroundDefault: "#243B55", surface: "#2E4A6A" },
  vistaBlack: { primary: "#0078D7", secondary: "#1E90FF", accent: "#0063B1", text: "#FFFFFF", textSecondary: "#A0C4E8", backgroundRoot: "#0A0A0A", backgroundDefault: "#141414", surface: "#1E1E1E" },
  // Zune themes
  zuneDark: { primary: "#8C0000", secondary: "#B33333", accent: "#660000", text: "#FFFFFF", textSecondary: "#AAAAAA", backgroundRoot: "#1A1A1A", backgroundDefault: "#222222", surface: "#2A2A2A" },
  zuneBrown: { primary: "#8B4513", secondary: "#A0522D", accent: "#6B3410", text: "#FFFFFF", textSecondary: "#C0A080", backgroundRoot: "#1A140E", backgroundDefault: "#2A2018", surface: "#3A2C20" },
  zuneRed: { primary: "#FF4500", secondary: "#FF6633", accent: "#CC3700", text: "#FFFFFF", textSecondary: "#FFAA80", backgroundRoot: "#1A0A00", backgroundDefault: "#2D1400", surface: "#401C00" },
  // Android Material themes
  materialLight: { primary: "#6200EE", secondary: "#03DAC6", accent: "#3700B3", text: "#000000", textSecondary: "#5F6368", backgroundRoot: "#FFFFFF", backgroundDefault: "#FAFAFA", surface: "#FFFFFF" },
  materialDark: { primary: "#BB86FC", secondary: "#03DAC6", accent: "#CF6679", text: "#FFFFFF", textSecondary: "#B0B0B0", backgroundRoot: "#121212", backgroundDefault: "#1E1E1E", surface: "#2D2D2D" },
  materialYou: { primary: "#D0BCFF", secondary: "#CCC2DC", accent: "#EFDECD", text: "#E6E1E5", textSecondary: "#CAC4D0", backgroundRoot: "#1C1B1F", backgroundDefault: "#2B2930", surface: "#332D41" },
  holoLight: { primary: "#33B5E5", secondary: "#99CC00", accent: "#0099CC", text: "#333333", textSecondary: "#666666", backgroundRoot: "#F3F3F3", backgroundDefault: "#FFFFFF", surface: "#FFFFFF" },
  holoDark: { primary: "#33B5E5", secondary: "#99CC00", accent: "#0099CC", text: "#FFFFFF", textSecondary: "#AAAAAA", backgroundRoot: "#000000", backgroundDefault: "#111111", surface: "#222222" },
  kitkatMusic: { primary: "#FF5722", secondary: "#FF8A65", accent: "#E64A19", text: "#FFFFFF", textSecondary: "#B0B0B0", backgroundRoot: "#212121", backgroundDefault: "#303030", surface: "#424242" },
  jellyBeanMusic: { primary: "#33B5E5", secondary: "#AA66CC", accent: "#99CC00", text: "#FFFFFF", textSecondary: "#B0B0B0", backgroundRoot: "#1A1A1A", backgroundDefault: "#262626", surface: "#333333" },
  // Samsung themes
  samsungTouchWiz: { primary: "#5FA5DA", secondary: "#7AB8E5", accent: "#3A8DC7", text: "#FFFFFF", textSecondary: "#B0C8E0", backgroundRoot: "#1C3A5A", backgroundDefault: "#264B6E", surface: "#305882" },
  samsungNatureUX: { primary: "#4CAF50", secondary: "#81C784", accent: "#388E3C", text: "#FFFFFF", textSecondary: "#A0CBA2", backgroundRoot: "#1A2F1C", backgroundDefault: "#254028", surface: "#2E5030" },
  samsungGraceUX: { primary: "#1565C0", secondary: "#42A5F5", accent: "#0D47A1", text: "#FFFFFF", textSecondary: "#90C8F8", backgroundRoot: "#0D1929", backgroundDefault: "#142538", surface: "#1A3148" },
  samsungOneUI: { primary: "#0381FE", secondary: "#5AAFFF", accent: "#0062CC", text: "#FFFFFF", textSecondary: "#AAAAAA", backgroundRoot: "#000000", backgroundDefault: "#121212", surface: "#1C1C1C" },
  samsungAmoled: { primary: "#4FC3F7", secondary: "#81D4FA", accent: "#29B6F6", text: "#FFFFFF", textSecondary: "#90CAF9", backgroundRoot: "#000000", backgroundDefault: "#000000", surface: "#0A0A0A" },
  // Third-party player themes
  powerampDark: { primary: "#FF6600", secondary: "#FF8533", accent: "#CC5200", text: "#FFFFFF", textSecondary: "#B0B0B0", backgroundRoot: "#101010", backgroundDefault: "#1A1A1A", surface: "#242424" },
  powerampFlat: { primary: "#00BCD4", secondary: "#4DD0E1", accent: "#0097A7", text: "#FFFFFF", textSecondary: "#80DEEA", backgroundRoot: "#263238", backgroundDefault: "#37474F", surface: "#455A64" },
  powerampTransparent: { primary: "#E91E63", secondary: "#F06292", accent: "#C2185B", text: "#FFFFFF", textSecondary: "#F8BBD9", backgroundRoot: "#1A0A10", backgroundDefault: "#2A1420", surface: "#3A1E30" },
  blackplayerDark: { primary: "#FF9800", secondary: "#FFB74D", accent: "#F57C00", text: "#FFFFFF", textSecondary: "#AAAAAA", backgroundRoot: "#121212", backgroundDefault: "#1E1E1E", surface: "#2A2A2A" },
  blackplayerAmoled: { primary: "#FF9800", secondary: "#FFB74D", accent: "#F57C00", text: "#FFFFFF", textSecondary: "#888888", backgroundRoot: "#000000", backgroundDefault: "#000000", surface: "#0D0D0D" },
  phonographMaterial: { primary: "#009688", secondary: "#4DB6AC", accent: "#00796B", text: "#FFFFFF", textSecondary: "#80CBC4", backgroundRoot: "#1A2A28", backgroundDefault: "#243836", surface: "#2E4644" },
  // Specialty themes
  amoledBlack: { primary: "#FFFFFF", secondary: "#E0E0E0", accent: "#CCCCCC", text: "#FFFFFF", textSecondary: "#888888", backgroundRoot: "#000000", backgroundDefault: "#000000", surface: "#0D0D0D" },
  darkGlass: { primary: "#87CEEB", secondary: "#ADD8E6", accent: "#5FB3D1", text: "#E0F0F8", textSecondary: "#A0C8D8", backgroundRoot: "#0A1520", backgroundDefault: "#142030", surface: "#1E2A40" },
  carbonFiber: { primary: "#808080", secondary: "#A0A0A0", accent: "#606060", text: "#FFFFFF", textSecondary: "#CCCCCC", backgroundRoot: "#121212", backgroundDefault: "#1E1E1E", surface: "#2A2A2A" },
  silverMetallic: { primary: "#C0C0C0", secondary: "#D4D4D4", accent: "#A8A8A8", text: "#FFFFFF", textSecondary: "#B8B8B8", backgroundRoot: "#1A1A1F", backgroundDefault: "#25252B", surface: "#303038" },
  midnight: { primary: "#6366F1", secondary: "#818CF8", accent: "#4F46E5", text: "#E0E7FF", textSecondary: "#A5B4FC", backgroundRoot: "#0F0F23", backgroundDefault: "#1A1A33", surface: "#252545" },
  minimalMono: { primary: "#FFFFFF", secondary: "#CCCCCC", accent: "#999999", text: "#FFFFFF", textSecondary: "#777777", backgroundRoot: "#0A0A0A", backgroundDefault: "#141414", surface: "#1E1E1E" },
};

const lightSeeds: Record<string, ThemeSeed> = {
  itunesBrushedMetal: { primary: "#0066CC", secondary: "#3399FF", accent: "#0055AA", text: "#333333", textSecondary: "#666666", backgroundRoot: "#C0C0C0", backgroundDefault: "#D4D4D4", surface: "#E8E8E8" },
  iosWhite: { primary: "#007AFF", secondary: "#5AC8FA", accent: "#0062CC", text: "#000000", textSecondary: "#8E8E93", backgroundRoot: "#FFFFFF", backgroundDefault: "#F2F2F7", surface: "#FFFFFF" },
  iosMinimal: { primary: "#000000", secondary: "#3A3A3C", accent: "#1C1C1E", text: "#000000", textSecondary: "#8E8E93", backgroundRoot: "#FFFFFF", backgroundDefault: "#F2F2F7", surface: "#FFFFFF" },
  wmpClassic: { primary: "#0078D4", secondary: "#40A0FF", accent: "#0066B8", text: "#000000", textSecondary: "#666666", backgroundRoot: "#D4D0C8", backgroundDefault: "#ECE9D8", surface: "#FFFFFF" },
  wmpSilver: { primary: "#0078D4", secondary: "#40A0FF", accent: "#0066B8", text: "#000000", textSecondary: "#555555", backgroundRoot: "#C0C0C0", backgroundDefault: "#D8D8D8", surface: "#E8E8E8" },
  materialLight: { primary: "#6200EE", secondary: "#03DAC6", accent: "#3700B3", text: "#000000", textSecondary: "#5F6368", backgroundRoot: "#FFFFFF", backgroundDefault: "#FAFAFA", surface: "#FFFFFF" },
  holoLight: { primary: "#33B5E5", secondary: "#99CC00", accent: "#0099CC", text: "#333333", textSecondary: "#666666", backgroundRoot: "#F3F3F3", backgroundDefault: "#FFFFFF", surface: "#FFFFFF" },
};

function generateLightPaletteFromSeed(seed: ThemeSeed) {
  const { r, g, b } = hexToRgb(seed.primary);
  return {
    text: seed.text,
    textSecondary: seed.textSecondary,
    textTertiary: lighten(seed.textSecondary, 0.3),
    buttonText: "#FFFFFF",
    tabIconDefault: seed.textSecondary,
    tabIconSelected: seed.primary,
    link: seed.primary,
    primary: seed.primary,
    primaryHover: darken(seed.primary, 0.1),
    primaryPressed: darken(seed.primary, 0.2),
    primaryContainer: lighten(seed.primary, 0.85),
    onPrimaryContainer: darken(seed.primary, 0.6),
    secondary: seed.secondary,
    secondaryContainer: lighten(seed.secondary, 0.85),
    onSecondaryContainer: darken(seed.secondary, 0.65),
    tertiary: lighten(seed.secondary, 0.3),
    tertiaryContainer: lighten(seed.accent, 0.85),
    onTertiaryContainer: darken(seed.accent, 0.65),
    accent: seed.accent,
    backgroundRoot: seed.backgroundRoot,
    backgroundDefault: seed.backgroundDefault,
    backgroundSecondary: darken(seed.backgroundDefault, 0.05),
    backgroundTertiary: darken(seed.backgroundDefault, 0.1),
    surface: seed.surface,
    surfaceVariant: darken(seed.surface, 0.03),
    surfaceContainerLowest: seed.surface,
    surfaceContainerLow: seed.backgroundDefault,
    surfaceContainer: darken(seed.backgroundDefault, 0.05),
    surfaceContainerHigh: darken(seed.backgroundDefault, 0.1),
    surfaceContainerHighest: darken(seed.backgroundDefault, 0.15),
    outline: darken(seed.surface, 0.2),
    outlineVariant: darken(seed.surface, 0.1),
    stroke1: darken(seed.surface, 0.2),
    stroke2: darken(seed.surface, 0.1),
    recordButton: "#F97316",
    success: "#1E8E3E",
    warning: "#E37400",
    error: "#C5221F",
    errorContainer: "#FFDAD6",
    onError: "#FFFFFF",
    onErrorContainer: "#410002",
    info: seed.primary,
    onPrimary: "#FFFFFF",
    onSecondary: "#FFFFFF",
    onSurface: seed.text,
    onSurfaceVariant: seed.textSecondary,
    inverseSurface: "#1C1C1E",
    inverseOnSurface: "#FFFFFF",
    inversePrimary: seed.primary,
    elevation1: `rgba(${r}, ${g}, ${b}, 0.02)`,
    elevation2: `rgba(${r}, ${g}, ${b}, 0.04)`,
    elevation3: `rgba(${r}, ${g}, ${b}, 0.06)`,
    scrim: "rgba(0, 0, 0, 0.4)",
    divider: darken(seed.surface, 0.1),
    cardBackground: seed.surface,
    cardBorder: darken(seed.surface, 0.1),
  };
}

export const ThemeColors: Record<ThemeName, { light: ReturnType<typeof generateLightPalette>; dark: ReturnType<typeof generateDarkPalette> }> = {
  fluent: {
    light: {
      text: "#242424",
      textSecondary: "#616161",
      textTertiary: "#8A8A8A",
      buttonText: "#FFFFFF",
      tabIconDefault: "#8A8A8A",
      tabIconSelected: "#0078D4",
      link: "#0078D4",
      primary: "#0078D4",
      primaryHover: "#106EBE",
      primaryPressed: "#005A9E",
      primaryContainer: "#D3E4FA",
      onPrimaryContainer: "#00315B",
      secondary: "#5C85D6",
      secondaryContainer: "#DEE6F7",
      onSecondaryContainer: "#1A365A",
      tertiary: "#A7BCE8",
      tertiaryContainer: "#E8EEF9",
      onTertiaryContainer: "#2D4A6E",
      accent: "#0078D4",
      backgroundRoot: "#FFFFFF",
      backgroundDefault: "#FAFAFA",
      backgroundSecondary: "#F5F5F5",
      backgroundTertiary: "#EFEFEF",
      surface: "#FFFFFF",
      surfaceVariant: "#F5F5F5",
      surfaceContainerLowest: "#FFFFFF",
      surfaceContainerLow: "#FAFAFA",
      surfaceContainer: "#F5F5F5",
      surfaceContainerHigh: "#EFEFEF",
      surfaceContainerHighest: "#E8E8E8",
      outline: "#E0E0E0",
      outlineVariant: "#D1D1D1",
      stroke1: "#E0E0E0",
      stroke2: "#D1D1D1",
      recordButton: "#F97316",
      success: "#107C10",
      warning: "#FFB900",
      error: "#D13438",
      errorContainer: "#FDECEA",
      onError: "#FFFFFF",
      onErrorContainer: "#410E0B",
      info: "#0078D4",
      onPrimary: "#FFFFFF",
      onSecondary: "#FFFFFF",
      onSurface: "#242424",
      onSurfaceVariant: "#616161",
      inverseSurface: "#242424",
      inverseOnSurface: "#FFFFFF",
      inversePrimary: "#2899F5",
      elevation1: "rgba(0, 0, 0, 0.02)",
      elevation2: "rgba(0, 0, 0, 0.04)",
      elevation3: "rgba(0, 0, 0, 0.06)",
      scrim: "rgba(0, 0, 0, 0.4)",
      divider: "#E0E0E0",
      cardBackground: "#FFFFFF",
      cardBorder: "#E0E0E0",
    },
    dark: {
      text: "#FFFFFF",
      textSecondary: "#D6D6D6",
      textTertiary: "#ADADAD",
      buttonText: "#FFFFFF",
      tabIconDefault: "#ADADAD",
      tabIconSelected: "#2899F5",
      link: "#2899F5",
      primary: "#2899F5",
      primaryHover: "#3AA0F3",
      primaryPressed: "#0078D4",
      primaryContainer: "#00315B",
      onPrimaryContainer: "#D3E4FA",
      secondary: "#6FA2F8",
      secondaryContainer: "#1A365A",
      onSecondaryContainer: "#DEE6F7",
      tertiary: "#9BBBF9",
      tertiaryContainer: "#2D4A6E",
      onTertiaryContainer: "#E8EEF9",
      accent: "#2899F5",
      backgroundRoot: "#1B1B1B",
      backgroundDefault: "#202020",
      backgroundSecondary: "#292929",
      backgroundTertiary: "#333333",
      surface: "#292929",
      surfaceVariant: "#333333",
      surfaceContainerLowest: "#1B1B1B",
      surfaceContainerLow: "#202020",
      surfaceContainer: "#292929",
      surfaceContainerHigh: "#333333",
      surfaceContainerHighest: "#3D3D3D",
      outline: "#3D3D3D",
      outlineVariant: "#4D4D4D",
      stroke1: "#3D3D3D",
      stroke2: "#4D4D4D",
      recordButton: "#F97316",
      success: "#107C10",
      warning: "#FFB900",
      error: "#D13438",
      errorContainer: "#93000A",
      onError: "#601410",
      onErrorContainer: "#FFDAD6",
      info: "#2899F5",
      onPrimary: "#FFFFFF",
      onSecondary: "#FFFFFF",
      onSurface: "#FFFFFF",
      onSurfaceVariant: "#D6D6D6",
      inverseSurface: "#FFFFFF",
      inverseOnSurface: "#1B1B1B",
      inversePrimary: "#0078D4",
      elevation1: "rgba(0, 0, 0, 0.03)",
      elevation2: "rgba(0, 0, 0, 0.05)",
      elevation3: "rgba(0, 0, 0, 0.08)",
      scrim: "rgba(0, 0, 0, 0.6)",
      divider: "#3D3D3D",
      cardBackground: "#292929",
      cardBorder: "#3D3D3D",
    },
  },
  fluentDark: {
    light: generateLightPalette({ primary: "#4285F4", secondary: "#6FA2F8", accent: "#5C9DFF", text: "#1C1C1E", textSecondary: "#5F6368", backgroundRoot: "#FFFFFF", backgroundDefault: "#F7F9FC", surface: "#FFFFFF" }),
    dark: {
      text: "#E8EAED",
      textSecondary: "#9AA0A6",
      textTertiary: "#6B7280",
      buttonText: "#FFFFFF",
      tabIconDefault: "#6B7280",
      tabIconSelected: "#4285F4",
      link: "#4285F4",
      primary: "#4285F4",
      primaryHover: "#5A9BF5",
      primaryPressed: "#3578E5",
      primaryContainer: "#1A3A6B",
      onPrimaryContainer: "#B3D1FF",
      secondary: "#6FA2F8",
      secondaryContainer: "#1E3A5C",
      onSecondaryContainer: "#C4DCFF",
      tertiary: "#9BBBF9",
      tertiaryContainer: "#2A4060",
      onTertiaryContainer: "#D0E4FF",
      accent: "#5C9DFF",
      backgroundRoot: "#121416",
      backgroundDefault: "#1A1D21",
      backgroundSecondary: "#1E2124",
      backgroundTertiary: "#25292E",
      surface: "#1E2124",
      surfaceVariant: "#25292E",
      surfaceContainerLowest: "#121416",
      surfaceContainerLow: "#1A1D21",
      surfaceContainer: "#2A2F35",
      surfaceContainerHigh: "#323840",
      surfaceContainerHighest: "#323840",
      outline: "#3D444D",
      outlineVariant: "#2D3238",
      stroke1: "#3D444D",
      stroke2: "#2D3238",
      recordButton: "#F97316",
      success: "#34A853",
      warning: "#F9AB00",
      error: "#EA4335",
      errorContainer: "#93000A",
      onError: "#601410",
      onErrorContainer: "#FFDAD6",
      info: "#4285F4",
      onPrimary: "#FFFFFF",
      onSecondary: "#FFFFFF",
      onSurface: "#E8EAED",
      onSurfaceVariant: "#9AA0A6",
      inverseSurface: "#E8EAED",
      inverseOnSurface: "#121416",
      inversePrimary: "#0B57D0",
      elevation1: "rgba(66, 133, 244, 0.02)",
      elevation2: "rgba(66, 133, 244, 0.04)",
      elevation3: "rgba(66, 133, 244, 0.06)",
      scrim: "rgba(0, 0, 0, 0.6)",
      divider: "#2A2F35",
      cardBackground: "#1E2124",
      cardBorder: "#2D3238",
    },
  },
  nightAmoled: {
    light: generateLightPalette({ primary: "#62ABFF", secondary: "#8BC4FF", accent: "#4DA3FF", text: "#1C1C1E", textSecondary: "#5F6368", backgroundRoot: "#FFFFFF", backgroundDefault: "#F7F9FC", surface: "#FFFFFF" }),
    dark: {
      text: "#FFFFFF",
      textSecondary: "#A1A1AA",
      textTertiary: "#71717A",
      buttonText: "#000000",
      tabIconDefault: "#71717A",
      tabIconSelected: "#62ABFF",
      link: "#62ABFF",
      primary: "#62ABFF",
      primaryHover: "#7BBAFF",
      primaryPressed: "#4D9CEE",
      primaryContainer: "#1A3A5C",
      onPrimaryContainer: "#B8D9FF",
      secondary: "#8BC4FF",
      secondaryContainer: "#1A4060",
      onSecondaryContainer: "#C8E0FF",
      tertiary: "#B5DCFF",
      tertiaryContainer: "#2A4A68",
      onTertiaryContainer: "#D8ECFF",
      accent: "#4DA3FF",
      backgroundRoot: "#000000",
      backgroundDefault: "#000000",
      backgroundSecondary: "#0D0D0D",
      backgroundTertiary: "#141414",
      surface: "#000000",
      surfaceVariant: "#0D0D0D",
      surfaceContainerLowest: "#000000",
      surfaceContainerLow: "#000000",
      surfaceContainer: "#141414",
      surfaceContainerHigh: "#1C1C1C",
      surfaceContainerHighest: "#1C1C1C",
      outline: "#27272A",
      outlineVariant: "#1F1F1F",
      stroke1: "#27272A",
      stroke2: "#1F1F1F",
      recordButton: "#F97316",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      errorContainer: "#93000A",
      onError: "#601410",
      onErrorContainer: "#FFDAD6",
      info: "#62ABFF",
      onPrimary: "#000000",
      onSecondary: "#000000",
      onSurface: "#FFFFFF",
      onSurfaceVariant: "#A1A1AA",
      inverseSurface: "#FFFFFF",
      inverseOnSurface: "#000000",
      inversePrimary: "#0B57D0",
      elevation1: "rgba(98, 171, 255, 0.03)",
      elevation2: "rgba(98, 171, 255, 0.05)",
      elevation3: "rgba(98, 171, 255, 0.07)",
      scrim: "rgba(0, 0, 0, 0.8)",
      divider: "#1F1F1F",
      cardBackground: "#0D0D0D",
      cardBorder: "#1F1F1F",
    },
  },
  warmNeutral: {
    light: {
      text: "#2A1F1A",
      textSecondary: "#6B5E57",
      textTertiary: "#9C8F88",
      buttonText: "#FFFFFF",
      tabIconDefault: "#9C8F88",
      tabIconSelected: "#C2410C",
      link: "#C2410C",
      primary: "#C2410C",
      primaryHover: "#A83A0A",
      primaryPressed: "#8E3108",
      primaryContainer: "#FFE4D8",
      onPrimaryContainer: "#5C1F08",
      secondary: "#E07A5F",
      secondaryContainer: "#FFDAD0",
      onSecondaryContainer: "#5C2A20",
      tertiary: "#F2A285",
      tertiaryContainer: "#FFE8DF",
      onTertiaryContainer: "#6B3A28",
      accent: "#A63A00",
      backgroundRoot: "#FAF7F4",
      backgroundDefault: "#F5F1ED",
      backgroundSecondary: "#EFE9E3",
      backgroundTertiary: "#E7DED6",
      surface: "#FDFBF9",
      surfaceVariant: "#F5F1ED",
      surfaceContainerLowest: "#FFFFFF",
      surfaceContainerLow: "#FAF7F4",
      surfaceContainer: "#EFE9E3",
      surfaceContainerHigh: "#E7DED6",
      surfaceContainerHighest: "#E7DED6",
      outline: "#D6C8BE",
      outlineVariant: "#E4DAD2",
      stroke1: "#D6C8BE",
      stroke2: "#E4DAD2",
      recordButton: "#EA580C",
      success: "#15803D",
      warning: "#B45309",
      error: "#B91C1C",
      errorContainer: "#FFDAD6",
      onError: "#FFFFFF",
      onErrorContainer: "#410002",
      info: "#C2410C",
      onPrimary: "#FFFFFF",
      onSecondary: "#FFFFFF",
      onSurface: "#2A1F1A",
      onSurfaceVariant: "#6B5E57",
      inverseSurface: "#2A1F1A",
      inverseOnSurface: "#FAF7F4",
      inversePrimary: "#E07A5F",
      elevation1: "rgba(194, 65, 12, 0.03)",
      elevation2: "rgba(194, 65, 12, 0.05)",
      elevation3: "rgba(194, 65, 12, 0.08)",
      scrim: "rgba(0, 0, 0, 0.4)",
      divider: "#E7DED6",
      cardBackground: "#FFFFFF",
      cardBorder: "#E4DAD2",
    },
    dark: {
      text: "#F5F1ED",
      textSecondary: "#BFB5AC",
      textTertiary: "#9C8F88",
      buttonText: "#FFFFFF",
      tabIconDefault: "#9C8F88",
      tabIconSelected: "#E07A5F",
      link: "#E07A5F",
      primary: "#E07A5F",
      primaryHover: "#E8917A",
      primaryPressed: "#CC6A4F",
      primaryContainer: "#5C2A20",
      onPrimaryContainer: "#FFDAD0",
      secondary: "#F2A285",
      secondaryContainer: "#6B3A28",
      onSecondaryContainer: "#FFE8DF",
      tertiary: "#F5C4B0",
      tertiaryContainer: "#7A4A38",
      onTertiaryContainer: "#FFF0E8",
      accent: "#EA580C",
      backgroundRoot: "#1A1614",
      backgroundDefault: "#211C19",
      backgroundSecondary: "#2A2420",
      backgroundTertiary: "#332C27",
      surface: "#211C19",
      surfaceVariant: "#2A2420",
      surfaceContainerLowest: "#1A1614",
      surfaceContainerLow: "#211C19",
      surfaceContainer: "#2A2420",
      surfaceContainerHigh: "#332C27",
      surfaceContainerHighest: "#3D3530",
      outline: "#5C524A",
      outlineVariant: "#433B35",
      stroke1: "#5C524A",
      stroke2: "#433B35",
      recordButton: "#EA580C",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      errorContainer: "#93000A",
      onError: "#601410",
      onErrorContainer: "#FFDAD6",
      info: "#E07A5F",
      onPrimary: "#2A1F1A",
      onSecondary: "#2A1F1A",
      onSurface: "#F5F1ED",
      onSurfaceVariant: "#BFB5AC",
      inverseSurface: "#F5F1ED",
      inverseOnSurface: "#1A1614",
      inversePrimary: "#C2410C",
      elevation1: "rgba(224, 122, 95, 0.03)",
      elevation2: "rgba(224, 122, 95, 0.05)",
      elevation3: "rgba(224, 122, 95, 0.08)",
      scrim: "rgba(0, 0, 0, 0.6)",
      divider: "#332C27",
      cardBackground: "#211C19",
      cardBorder: "#332C27",
    },
  },
  coolBlue: {
    light: {
      text: "#0F172A",
      textSecondary: "#475569",
      textTertiary: "#94A3B8",
      buttonText: "#FFFFFF",
      tabIconDefault: "#94A3B8",
      tabIconSelected: "#2563EB",
      link: "#2563EB",
      primary: "#2563EB",
      primaryHover: "#1D4ED8",
      primaryPressed: "#1E40AF",
      primaryContainer: "#DBEAFE",
      onPrimaryContainer: "#1E3A5F",
      secondary: "#60A5FA",
      secondaryContainer: "#E0F2FE",
      onSecondaryContainer: "#1E4068",
      tertiary: "#93C5FD",
      tertiaryContainer: "#EFF6FF",
      onTertiaryContainer: "#1E4A7A",
      accent: "#1D4ED8",
      backgroundRoot: "#F8FAFC",
      backgroundDefault: "#F1F5F9",
      backgroundSecondary: "#E2E8F0",
      backgroundTertiary: "#CBD5E1",
      surface: "#FFFFFF",
      surfaceVariant: "#F1F5F9",
      surfaceContainerLowest: "#FFFFFF",
      surfaceContainerLow: "#F8FAFC",
      surfaceContainer: "#E2E8F0",
      surfaceContainerHigh: "#CBD5E1",
      surfaceContainerHighest: "#CBD5E1",
      outline: "#CBD5E1",
      outlineVariant: "#E2E8F0",
      stroke1: "#CBD5E1",
      stroke2: "#E2E8F0",
      recordButton: "#F97316",
      success: "#16A34A",
      warning: "#D97706",
      error: "#DC2626",
      errorContainer: "#FFDAD6",
      onError: "#FFFFFF",
      onErrorContainer: "#410002",
      info: "#2563EB",
      onPrimary: "#FFFFFF",
      onSecondary: "#FFFFFF",
      onSurface: "#0F172A",
      onSurfaceVariant: "#475569",
      inverseSurface: "#0F172A",
      inverseOnSurface: "#F8FAFC",
      inversePrimary: "#60A5FA",
      elevation1: "rgba(37, 99, 235, 0.03)",
      elevation2: "rgba(37, 99, 235, 0.05)",
      elevation3: "rgba(37, 99, 235, 0.08)",
      scrim: "rgba(0, 0, 0, 0.4)",
      divider: "#E2E8F0",
      cardBackground: "#FFFFFF",
      cardBorder: "#E2E8F0",
    },
    dark: {
      text: "#F1F5F9",
      textSecondary: "#94A3B8",
      textTertiary: "#64748B",
      buttonText: "#FFFFFF",
      tabIconDefault: "#64748B",
      tabIconSelected: "#60A5FA",
      link: "#60A5FA",
      primary: "#60A5FA",
      primaryHover: "#7BB3FB",
      primaryPressed: "#4997F5",
      primaryContainer: "#1E3A5F",
      onPrimaryContainer: "#DBEAFE",
      secondary: "#93C5FD",
      secondaryContainer: "#1E4068",
      onSecondaryContainer: "#E0F2FE",
      tertiary: "#BFDBFE",
      tertiaryContainer: "#1E4A7A",
      onTertiaryContainer: "#EFF6FF",
      accent: "#3B82F6",
      backgroundRoot: "#0F172A",
      backgroundDefault: "#1E293B",
      backgroundSecondary: "#334155",
      backgroundTertiary: "#475569",
      surface: "#1E293B",
      surfaceVariant: "#334155",
      surfaceContainerLowest: "#0F172A",
      surfaceContainerLow: "#1E293B",
      surfaceContainer: "#334155",
      surfaceContainerHigh: "#475569",
      surfaceContainerHighest: "#64748B",
      outline: "#475569",
      outlineVariant: "#334155",
      stroke1: "#475569",
      stroke2: "#334155",
      recordButton: "#F97316",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      errorContainer: "#93000A",
      onError: "#601410",
      onErrorContainer: "#FFDAD6",
      info: "#60A5FA",
      onPrimary: "#0F172A",
      onSecondary: "#0F172A",
      onSurface: "#F1F5F9",
      onSurfaceVariant: "#94A3B8",
      inverseSurface: "#F1F5F9",
      inverseOnSurface: "#0F172A",
      inversePrimary: "#2563EB",
      elevation1: "rgba(96, 165, 250, 0.03)",
      elevation2: "rgba(96, 165, 250, 0.05)",
      elevation3: "rgba(96, 165, 250, 0.08)",
      scrim: "rgba(0, 0, 0, 0.6)",
      divider: "#334155",
      cardBackground: "#1E293B",
      cardBorder: "#334155",
    },
  },
  // Winamp themes
  winampClassic: { light: generateLightPalette(darkSeeds.winampClassic), dark: generateDarkPalette(darkSeeds.winampClassic) },
  winampModern: { light: generateLightPalette(darkSeeds.winampModern), dark: generateDarkPalette(darkSeeds.winampModern) },
  bento: { light: generateLightPalette(darkSeeds.bento), dark: generateDarkPalette(darkSeeds.bento) },
  bigBento: { light: generateLightPalette(darkSeeds.bigBento), dark: generateDarkPalette(darkSeeds.bigBento) },
  mmd3: { light: generateLightPalette(darkSeeds.mmd3), dark: generateDarkPalette(darkSeeds.mmd3) },
  topaz: { light: generateLightPalette(darkSeeds.topaz), dark: generateDarkPalette(darkSeeds.topaz) },
  retroPixel: { light: generateLightPalette(darkSeeds.retroPixel), dark: generateDarkPalette(darkSeeds.retroPixel) },
  alienGreen: { light: generateLightPalette(darkSeeds.alienGreen), dark: generateDarkPalette(darkSeeds.alienGreen) },
  bubblegumPink: { light: generateLightPalette(darkSeeds.bubblegumPink), dark: generateDarkPalette(darkSeeds.bubblegumPink) },
  milkdrop: { light: generateLightPalette(darkSeeds.milkdrop), dark: generateDarkPalette(darkSeeds.milkdrop) },
  // iTunes themes
  itunesClassic: { light: generateLightPalette(darkSeeds.itunesClassic), dark: generateDarkPalette(darkSeeds.itunesClassic) },
  itunesBrushedMetal: { light: generateLightPaletteFromSeed(lightSeeds.itunesBrushedMetal), dark: generateDarkPalette(darkSeeds.itunesBrushedMetal) },
  itunesAqua: { light: generateLightPalette(darkSeeds.itunesAqua), dark: generateDarkPalette(darkSeeds.itunesAqua) },
  // iOS themes
  iosWhite: { light: generateLightPaletteFromSeed(lightSeeds.iosWhite), dark: generateDarkPalette(darkSeeds.iosDark) },
  iosDark: { light: generateLightPaletteFromSeed(lightSeeds.iosWhite), dark: generateDarkPalette(darkSeeds.iosDark) },
  iosMinimal: { light: generateLightPaletteFromSeed(lightSeeds.iosMinimal), dark: generateDarkPalette(darkSeeds.iosDark) },
  frostedGlass: { light: generateLightPalette(darkSeeds.frostedGlass), dark: generateDarkPalette(darkSeeds.frostedGlass) },
  // Windows Media Player themes
  wmpClassic: { light: generateLightPaletteFromSeed(lightSeeds.wmpClassic), dark: generateDarkPalette(darkSeeds.wmpBlue) },
  wmpBlue: { light: generateLightPalette(darkSeeds.wmpBlue), dark: generateDarkPalette(darkSeeds.wmpBlue) },
  wmpSilver: { light: generateLightPaletteFromSeed(lightSeeds.wmpSilver), dark: generateDarkPalette(darkSeeds.vistaBlack) },
  vistaAero: { light: generateLightPalette(darkSeeds.vistaAero), dark: generateDarkPalette(darkSeeds.vistaAero) },
  aeroGlass: { light: generateLightPalette(darkSeeds.aeroGlass), dark: generateDarkPalette(darkSeeds.aeroGlass) },
  vistaBlack: { light: generateLightPalette(darkSeeds.vistaBlack), dark: generateDarkPalette(darkSeeds.vistaBlack) },
  // Zune themes
  zuneDark: { light: generateLightPalette(darkSeeds.zuneDark), dark: generateDarkPalette(darkSeeds.zuneDark) },
  zuneBrown: { light: generateLightPalette(darkSeeds.zuneBrown), dark: generateDarkPalette(darkSeeds.zuneBrown) },
  zuneRed: { light: generateLightPalette(darkSeeds.zuneRed), dark: generateDarkPalette(darkSeeds.zuneRed) },
  // Android Material themes
  materialLight: { light: generateLightPaletteFromSeed(lightSeeds.materialLight), dark: generateDarkPalette(darkSeeds.materialDark) },
  materialDark: { light: generateLightPaletteFromSeed(lightSeeds.materialLight), dark: generateDarkPalette(darkSeeds.materialDark) },
  materialYou: { light: generateLightPalette(darkSeeds.materialYou), dark: generateDarkPalette(darkSeeds.materialYou) },
  holoLight: { light: generateLightPaletteFromSeed(lightSeeds.holoLight), dark: generateDarkPalette(darkSeeds.holoDark) },
  holoDark: { light: generateLightPaletteFromSeed(lightSeeds.holoLight), dark: generateDarkPalette(darkSeeds.holoDark) },
  kitkatMusic: { light: generateLightPalette(darkSeeds.kitkatMusic), dark: generateDarkPalette(darkSeeds.kitkatMusic) },
  jellyBeanMusic: { light: generateLightPalette(darkSeeds.jellyBeanMusic), dark: generateDarkPalette(darkSeeds.jellyBeanMusic) },
  // Samsung themes
  samsungTouchWiz: { light: generateLightPalette(darkSeeds.samsungTouchWiz), dark: generateDarkPalette(darkSeeds.samsungTouchWiz) },
  samsungNatureUX: { light: generateLightPalette(darkSeeds.samsungNatureUX), dark: generateDarkPalette(darkSeeds.samsungNatureUX) },
  samsungGraceUX: { light: generateLightPalette(darkSeeds.samsungGraceUX), dark: generateDarkPalette(darkSeeds.samsungGraceUX) },
  samsungOneUI: { light: generateLightPalette(darkSeeds.samsungOneUI), dark: generateDarkPalette(darkSeeds.samsungOneUI) },
  samsungAmoled: { light: generateLightPalette(darkSeeds.samsungAmoled), dark: generateDarkPalette(darkSeeds.samsungAmoled) },
  // Third-party player themes
  powerampDark: { light: generateLightPalette(darkSeeds.powerampDark), dark: generateDarkPalette(darkSeeds.powerampDark) },
  powerampFlat: { light: generateLightPalette(darkSeeds.powerampFlat), dark: generateDarkPalette(darkSeeds.powerampFlat) },
  powerampTransparent: { light: generateLightPalette(darkSeeds.powerampTransparent), dark: generateDarkPalette(darkSeeds.powerampTransparent) },
  blackplayerDark: { light: generateLightPalette(darkSeeds.blackplayerDark), dark: generateDarkPalette(darkSeeds.blackplayerDark) },
  blackplayerAmoled: { light: generateLightPalette(darkSeeds.blackplayerAmoled), dark: generateDarkPalette(darkSeeds.blackplayerAmoled) },
  phonographMaterial: { light: generateLightPalette(darkSeeds.phonographMaterial), dark: generateDarkPalette(darkSeeds.phonographMaterial) },
  // Specialty themes
  amoledBlack: { light: generateLightPalette(darkSeeds.amoledBlack), dark: generateDarkPalette(darkSeeds.amoledBlack) },
  darkGlass: { light: generateLightPalette(darkSeeds.darkGlass), dark: generateDarkPalette(darkSeeds.darkGlass) },
  carbonFiber: { light: generateLightPalette(darkSeeds.carbonFiber), dark: generateDarkPalette(darkSeeds.carbonFiber) },
  silverMetallic: { light: generateLightPalette(darkSeeds.silverMetallic), dark: generateDarkPalette(darkSeeds.silverMetallic) },
  midnight: { light: generateLightPalette(darkSeeds.midnight), dark: generateDarkPalette(darkSeeds.midnight) },
  minimalMono: { light: generateLightPalette(darkSeeds.minimalMono), dark: generateDarkPalette(darkSeeds.minimalMono) },
};

export const themeRegistry: { name: ThemeName; label: string; description: string; isDark: boolean; category: string }[] = [
  // Base themes
  { name: "fluent", label: "Fluent Light", description: "Clean Microsoft style", isDark: false, category: "System" },
  { name: "fluentDark", label: "Fluent Dark", description: "Modern dark mode", isDark: true, category: "System" },
  { name: "nightAmoled", label: "Night AMOLED", description: "True black display", isDark: true, category: "System" },
  { name: "warmNeutral", label: "Warm Neutral", description: "Earthy tones", isDark: false, category: "System" },
  { name: "coolBlue", label: "Cool Blue", description: "Professional blue", isDark: false, category: "System" },
  // Winamp themes
  { name: "winampClassic", label: "Winamp Classic", description: "Retro green LCD", isDark: true, category: "Winamp" },
  { name: "winampModern", label: "Winamp Modern", description: "Orange accent", isDark: true, category: "Winamp" },
  { name: "bento", label: "Bento", description: "Modern blue skin", isDark: true, category: "Winamp" },
  { name: "bigBento", label: "Big Bento", description: "Extended Bento", isDark: true, category: "Winamp" },
  { name: "mmd3", label: "MMD3", description: "Cyan glow", isDark: true, category: "Winamp" },
  { name: "topaz", label: "Topaz", description: "Golden yellow", isDark: true, category: "Winamp" },
  { name: "retroPixel", label: "Retro Pixel", description: "8-bit green", isDark: true, category: "Winamp" },
  { name: "alienGreen", label: "Alien Green", description: "Sci-fi neon", isDark: true, category: "Winamp" },
  { name: "bubblegumPink", label: "Bubblegum Pink", description: "Girly candy", isDark: true, category: "Winamp" },
  { name: "milkdrop", label: "Milkdrop", description: "Visualizer style", isDark: true, category: "Winamp" },
  // iTunes themes
  { name: "itunesClassic", label: "iTunes Classic", description: "Apple green", isDark: true, category: "iTunes" },
  { name: "itunesBrushedMetal", label: "iTunes Brushed Metal", description: "Mac OS X style", isDark: false, category: "iTunes" },
  { name: "itunesAqua", label: "iTunes Aqua", description: "Aqua blue", isDark: true, category: "iTunes" },
  // iOS themes
  { name: "iosWhite", label: "iOS White", description: "Clean Apple", isDark: false, category: "iOS" },
  { name: "iosDark", label: "iOS Dark", description: "iOS dark mode", isDark: true, category: "iOS" },
  { name: "iosMinimal", label: "iOS Minimal", description: "Minimal black", isDark: false, category: "iOS" },
  { name: "frostedGlass", label: "Frosted Glass", description: "iOS blur effect", isDark: true, category: "iOS" },
  // Windows Media Player themes
  { name: "wmpClassic", label: "WMP Classic", description: "Windows XP style", isDark: false, category: "Windows" },
  { name: "wmpBlue", label: "WMP Blue", description: "Blue metallic", isDark: true, category: "Windows" },
  { name: "wmpSilver", label: "WMP Silver", description: "Silver chrome", isDark: false, category: "Windows" },
  { name: "vistaAero", label: "Vista Aero", description: "Windows Vista glass", isDark: true, category: "Windows" },
  { name: "aeroGlass", label: "Aero Glass", description: "Translucent blue", isDark: true, category: "Windows" },
  { name: "vistaBlack", label: "Vista Black", description: "Dark Vista", isDark: true, category: "Windows" },
  // Zune themes
  { name: "zuneDark", label: "Zune Dark", description: "Microsoft Zune", isDark: true, category: "Zune" },
  { name: "zuneBrown", label: "Zune Brown", description: "Zune earth", isDark: true, category: "Zune" },
  { name: "zuneRed", label: "Zune Red", description: "Zune orange-red", isDark: true, category: "Zune" },
  // Android Material themes
  { name: "materialLight", label: "Material Light", description: "Google Material", isDark: false, category: "Android" },
  { name: "materialDark", label: "Material Dark", description: "Material dark", isDark: true, category: "Android" },
  { name: "materialYou", label: "Material You", description: "Android 12+", isDark: true, category: "Android" },
  { name: "holoLight", label: "Holo Light", description: "Android 4.0", isDark: false, category: "Android" },
  { name: "holoDark", label: "Holo Dark", description: "Holo dark", isDark: true, category: "Android" },
  { name: "kitkatMusic", label: "KitKat Music", description: "Android 4.4", isDark: true, category: "Android" },
  { name: "jellyBeanMusic", label: "Jelly Bean Music", description: "Android 4.1", isDark: true, category: "Android" },
  // Samsung themes
  { name: "samsungTouchWiz", label: "Samsung TouchWiz", description: "Classic Samsung", isDark: true, category: "Samsung" },
  { name: "samsungNatureUX", label: "Samsung Nature UX", description: "Galaxy S3-S5", isDark: true, category: "Samsung" },
  { name: "samsungGraceUX", label: "Samsung Grace UX", description: "Galaxy S7-S8", isDark: true, category: "Samsung" },
  { name: "samsungOneUI", label: "Samsung One UI", description: "Modern Samsung", isDark: true, category: "Samsung" },
  { name: "samsungAmoled", label: "Samsung AMOLED", description: "True black", isDark: true, category: "Samsung" },
  // Third-party player themes
  { name: "powerampDark", label: "Poweramp Dark", description: "Poweramp player", isDark: true, category: "Players" },
  { name: "powerampFlat", label: "Poweramp Flat", description: "Flat design", isDark: true, category: "Players" },
  { name: "powerampTransparent", label: "Poweramp Transparent", description: "Pink transparent", isDark: true, category: "Players" },
  { name: "blackplayerDark", label: "BlackPlayer Dark", description: "BlackPlayer app", isDark: true, category: "Players" },
  { name: "blackplayerAmoled", label: "BlackPlayer AMOLED", description: "True black", isDark: true, category: "Players" },
  { name: "phonographMaterial", label: "Phonograph Material", description: "Teal material", isDark: true, category: "Players" },
  // Specialty themes
  { name: "amoledBlack", label: "AMOLED Black", description: "Pure black", isDark: true, category: "Specialty" },
  { name: "darkGlass", label: "Dark Glass", description: "Frosted dark", isDark: true, category: "Specialty" },
  { name: "carbonFiber", label: "Carbon Fiber", description: "Industrial", isDark: true, category: "Specialty" },
  { name: "silverMetallic", label: "Silver Metallic", description: "Chrome finish", isDark: true, category: "Specialty" },
  { name: "midnight", label: "Midnight", description: "Purple night", isDark: true, category: "Specialty" },
  { name: "minimalMono", label: "Minimal Mono", description: "Monochrome", isDark: true, category: "Specialty" },
];

export const Colors = ThemeColors.fluent;

export const Layout = {
  topBarHeight: 56,
  secondaryBarHeight: 48,
  bottomNavHeight: 64,
  miniPlayerHeight: 68,
  miniPlayerGapFromNav: 8,
  safeAreaPadding: 16,
  horizontalPadding: 20,
  horizontalPaddingMin: 16,
  horizontalPaddingMax: 24,
  sectionGap: 24,
  sectionGapLarge: 32,
  cardGap: 12,
  cardGapVertical: 16,
  screenMaxWidth: 600,
  listItemCompact: 48,
  listItemStandard: 56,
  listItemRich: 72,
  tabHeight: 48,
  touchTargetMin: 48,
  inputFieldHeight: 48,
  buttonSmall: 36,
  buttonStandard: 44,
  buttonLarge: 48,
  playButtonLarge: 56,
};

export const Spacing = {
  none: 0,
  xxs: 2,
  xs: 4,
  sNudge: 6,
  s: 8,
  mNudge: 10,
  m: 12,
  l: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  size1: 4,
  size2: 8,
  size3: 12,
  size4: 16,
  size5: 20,
  size6: 24,
  size7: 32,
  size8: 40,
  size9: 48,
  size10: 40,
  size12: 48,
  size16: 64,
  size20: 80,
  "2xs": 4,
  sm: 12,
  md: 16,
  lg: 20,
  "2xl": 32,
  "3xl": 48,
  iconGap: 8,
  titleToSubtitle: 4,
  textToIcon: 8,
  contentBlock: 12,
  headingToContent: 12,
  sectionHeaderToCards: 16,
  betweenButtons: 12,
  primaryActionSeparation: 24,
  labelToInput: 4,
  betweenFields: 16,
  formSectionBreak: 24,
  tabIndicatorMargin: 8,
  belowTabs: 16,
  miniPlayerArtworkGap: 12,
  progressBarSpacing: 16,
  controlCluster: 16,
  artworkMargin: 24,
  artworkMarginLarge: 32,
  inputHeight: 32,
  inputHeightLarge: 40,
  buttonHeight: 32,
  buttonHeightSm: 24,
  buttonHeightMd: 32,
  buttonHeightLg: 40,
  buttonHeightLarge: 48,
  iconButtonSize: 32,
  controlSize: 44,
  recordButtonSize: 64,
  albumArtSize: 280,
  albumArtSmall: 48,
  albumArtMedium: 112,
  waveformHeight: 36,
  chipHeight: 32,
  navIconSize: 24,
  listItemHeight: 48,
  touchTargetIOS: 44,
  touchTargetAndroid: 48,
  horizontalXXS: 2,
  horizontalXS: 4,
  horizontalSNudge: 6,
  horizontalS: 8,
  horizontalMNudge: 10,
  horizontalM: 12,
  horizontalL: 16,
  horizontalXL: 20,
  horizontalXXL: 24,
  verticalXXS: 2,
  verticalXS: 4,
  verticalSNudge: 6,
  verticalS: 8,
  verticalMNudge: 10,
  verticalM: 12,
  verticalL: 16,
  verticalXL: 20,
  verticalXXL: 24,
};

export const FluentSpacing = {
  none: 0,
  xxs: 2,
  xs: 4,
  sNudge: 6,
  s: 8,
  mNudge: 10,
  m: 12,
  l: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  horizontal: {
    none: 0,
    xxs: 2,
    xs: 4,
    sNudge: 6,
    s: 8,
    mNudge: 10,
    m: 12,
    l: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  vertical: {
    none: 0,
    xxs: 2,
    xs: 4,
    sNudge: 6,
    s: 8,
    mNudge: 10,
    m: 12,
    l: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
};

export const SafeAreaSpacing = {
  top: 44,
  bottom: 34,
  horizontal: 16,
  bottomWithTabBar: 98,
  bottomWithMiniPlayer: 102,
  bottomWithBoth: 170,
};

export const BorderRadius = {
  none: 0,
  small: 2,
  medium: 4,
  large: 8,
  xLarge: 12,
  circular: 9999,
  sm: 2,
  md: 4,
  lg: 8,
  xl: 12,
  "2xl": 16,
  full: 9999,
  xs: 2,
  button: 4,
  input: 4,
  card: 8,
  cardLarge: 12,
  dialog: 12,
  pill: 9999,
  miniPlayer: 12,
};

export const CardPadding = {
  dense: 12,
  standard: 16,
  rich: 20,
};

export const Typography = {
  displayLarge: {
    fontSize: 68,
    fontWeight: "400" as const,
    lineHeight: 92,
    letterSpacing: 0,
  },
  displayMedium: {
    fontSize: 40,
    fontWeight: "400" as const,
    lineHeight: 52,
    letterSpacing: 0,
  },
  displaySmall: {
    fontSize: 28,
    fontWeight: "400" as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  titleLarge: {
    fontSize: 28,
    fontWeight: "600" as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  titleMedium: {
    fontSize: 24,
    fontWeight: "600" as const,
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleSmall: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 28,
    letterSpacing: 0,
  },
  title4: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 22,
    letterSpacing: 0,
  },
  title5: {
    fontSize: 14,
    fontWeight: "600" as const,
    lineHeight: 20,
    letterSpacing: 0,
  },
  title6: {
    fontSize: 12,
    fontWeight: "600" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  subtitleLarge: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 28,
    letterSpacing: 0,
  },
  subtitleMedium: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 22,
    letterSpacing: 0,
  },
  bodyLarge: {
    fontSize: 16,
    fontWeight: "400" as const,
    lineHeight: 22,
    letterSpacing: 0,
  },
  bodyMedium: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 20,
    letterSpacing: 0,
  },
  bodySmall: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  bodyLargeSemibold: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 22,
    letterSpacing: 0,
  },
  bodyMediumSemibold: {
    fontSize: 14,
    fontWeight: "600" as const,
    lineHeight: 20,
    letterSpacing: 0,
  },
  bodySmallSemibold: {
    fontSize: 12,
    fontWeight: "600" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  captionLarge: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  captionSmall: {
    fontSize: 10,
    fontWeight: "400" as const,
    lineHeight: 12,
    letterSpacing: 0,
  },
  labelLarge: {
    fontSize: 14,
    fontWeight: "600" as const,
    lineHeight: 20,
    letterSpacing: 0,
  },
  labelMedium: {
    fontSize: 12,
    fontWeight: "600" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  labelSmall: {
    fontSize: 10,
    fontWeight: "600" as const,
    lineHeight: 12,
    letterSpacing: 0,
  },
  headlineLarge: {
    fontSize: 28,
    fontWeight: "400" as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontSize: 24,
    fontWeight: "400" as const,
    lineHeight: 32,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontSize: 20,
    fontWeight: "400" as const,
    lineHeight: 28,
    letterSpacing: 0,
  },
  display: {
    fontSize: 68,
    fontWeight: "400" as const,
    lineHeight: 92,
    letterSpacing: 0,
  },
  subtitle1: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 28,
    letterSpacing: 0,
  },
  subtitle2: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 22,
    letterSpacing: 0,
  },
  body: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 20,
    letterSpacing: 0,
  },
  caption: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  h1: {
    fontSize: 28,
    fontWeight: "600" as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  h2: {
    fontSize: 24,
    fontWeight: "600" as const,
    lineHeight: 32,
    letterSpacing: 0,
  },
  h3: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 28,
    letterSpacing: 0,
  },
  h4: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 22,
    letterSpacing: 0,
  },
  small: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  link: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 20,
    letterSpacing: 0,
    textDecorationLine: "underline" as const,
  },
  display1: {
    fontSize: 68,
    fontWeight: "400" as const,
    lineHeight: 92,
    letterSpacing: 0,
  },
  display2: {
    fontSize: 40,
    fontWeight: "400" as const,
    lineHeight: 52,
    letterSpacing: 0,
  },
  display3: {
    fontSize: 28,
    fontWeight: "400" as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  title1: {
    fontSize: 28,
    fontWeight: "600" as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  title2: {
    fontSize: 24,
    fontWeight: "600" as const,
    lineHeight: 32,
    letterSpacing: 0,
  },
  title3: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 28,
    letterSpacing: 0,
  },
  body1: {
    fontSize: 16,
    fontWeight: "400" as const,
    lineHeight: 22,
    letterSpacing: 0,
  },
  body2: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 20,
    letterSpacing: 0,
  },
  caption1: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
  caption2: {
    fontSize: 10,
    fontWeight: "400" as const,
    lineHeight: 12,
    letterSpacing: 0,
  },
};

export const Fluent2Tokens = {
  strokeWidthThin: 1,
  strokeWidthThick: 2,
  strokeWidthThicker: 3,
  strokeWidthThickest: 4,
  durationUltraFast: 50,
  durationFaster: 100,
  durationFast: 150,
  durationNormal: 200,
  durationGentle: 250,
  durationSlow: 300,
  durationSlower: 400,
  durationUltraSlow: 500,
  curveAccelerateMax: "cubic-bezier(0.9, 0.1, 1, 0.2)",
  curveAccelerateMid: "cubic-bezier(1, 0, 1, 1)",
  curveAccelerateMin: "cubic-bezier(0.8, 0, 0.78, 1)",
  curveDecelerateMax: "cubic-bezier(0.1, 0.9, 0.2, 1)",
  curveDecelerateMid: "cubic-bezier(0, 0, 0, 1)",
  curveDecelerateMin: "cubic-bezier(0.33, 0, 0.1, 1)",
  curveEasyEase: "cubic-bezier(0.33, 0, 0.67, 1)",
  curveEasyEaseMax: "cubic-bezier(0.8, 0, 0.2, 1)",
  curveLinear: "cubic-bezier(0, 0, 1, 1)",
  shadowAmbient: "0 0 2px rgba(0, 0, 0, 0.12)",
  shadow2: "0 1px 2px rgba(0, 0, 0, 0.14)",
  shadow4: "0 2px 4px rgba(0, 0, 0, 0.14)",
  shadow8: "0 4px 8px rgba(0, 0, 0, 0.14)",
  shadow16: "0 8px 16px rgba(0, 0, 0, 0.14)",
  shadow28: "0 14px 28px rgba(0, 0, 0, 0.24)",
  shadow64: "0 32px 64px rgba(0, 0, 0, 0.24)",
};

export const FluentMotion = {
  duration: {
    ultraFast: 50,
    faster: 100,
    fast: 150,
    normal: 200,
    slow: 300,
    slower: 500,
  },
  easing: {
    ease: { x1: 0.8, y1: 0, x2: 0.2, y2: 1 },
    linear: { x1: 0, y1: 0, x2: 1, y2: 1 },
    decelerate: { x1: 0, y1: 0.55, x2: 0.45, y2: 1 },
    accelerate: { x1: 0.9, y1: 0.1, x2: 1, y2: 0.2 },
    accelerateMax: { x1: 0.9, y1: 0.1, x2: 1, y2: 0.2 },
    accelerateMid: { x1: 1, y1: 0, x2: 1, y2: 1 },
    accelerateMin: { x1: 0.8, y1: 0, x2: 0.78, y2: 1 },
    decelerateMax: { x1: 0.1, y1: 0.9, x2: 0.2, y2: 1 },
    decelerateMid: { x1: 0, y1: 0, x2: 0, y2: 1 },
    decelerateMin: { x1: 0.33, y1: 0, x2: 0.1, y2: 1 },
    easyEase: { x1: 0.33, y1: 0, x2: 0.67, y2: 1 },
    easyEaseMax: { x1: 0.8, y1: 0, x2: 0.2, y2: 1 },
  },
  curve: {
    ease: "cubic-bezier(0.8, 0, 0.2, 1)",
    linear: "cubic-bezier(0, 0, 1, 1)",
    decelerate: "cubic-bezier(0, 0.55, 0.45, 1)",
    accelerate: "cubic-bezier(0.9, 0.1, 1, 0.2)",
    accelerateMax: "cubic-bezier(0.9, 0.1, 1, 0.2)",
    accelerateMid: "cubic-bezier(1, 0, 1, 1)",
    accelerateMin: "cubic-bezier(0.8, 0, 0.78, 1)",
    decelerateMax: "cubic-bezier(0.1, 0.9, 0.2, 1)",
    decelerateMid: "cubic-bezier(0, 0, 0, 1)",
    decelerateMin: "cubic-bezier(0.33, 0, 0.1, 1)",
    easyEase: "cubic-bezier(0.33, 0, 0.67, 1)",
    easyEaseMax: "cubic-bezier(0.8, 0, 0.2, 1)",
  },
};

export const FluentShadow = {
  shadow2: {
    ambient: { x: 0, y: 0, blur: 2, color: "rgba(0, 0, 0, 0.12)" },
    key: { x: 0, y: 1, blur: 2, color: "rgba(0, 0, 0, 0.14)" },
    combined: "0 0 2px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.14)",
    elevation: 2,
  },
  shadow4: {
    ambient: { x: 0, y: 0, blur: 2, color: "rgba(0, 0, 0, 0.12)" },
    key: { x: 0, y: 2, blur: 4, color: "rgba(0, 0, 0, 0.14)" },
    combined: "0 0 2px rgba(0, 0, 0, 0.12), 0 2px 4px rgba(0, 0, 0, 0.14)",
    elevation: 4,
  },
  shadow8: {
    ambient: { x: 0, y: 0, blur: 2, color: "rgba(0, 0, 0, 0.12)" },
    key: { x: 0, y: 4, blur: 8, color: "rgba(0, 0, 0, 0.14)" },
    combined: "0 0 2px rgba(0, 0, 0, 0.12), 0 4px 8px rgba(0, 0, 0, 0.14)",
    elevation: 8,
  },
  shadow16: {
    ambient: { x: 0, y: 0, blur: 2, color: "rgba(0, 0, 0, 0.12)" },
    key: { x: 0, y: 8, blur: 16, color: "rgba(0, 0, 0, 0.14)" },
    combined: "0 0 2px rgba(0, 0, 0, 0.12), 0 8px 16px rgba(0, 0, 0, 0.14)",
    elevation: 16,
  },
  shadow28: {
    ambient: { x: 0, y: 0, blur: 8, color: "rgba(0, 0, 0, 0.12)" },
    key: { x: 0, y: 14, blur: 28, color: "rgba(0, 0, 0, 0.24)" },
    combined: "0 0 8px rgba(0, 0, 0, 0.12), 0 14px 28px rgba(0, 0, 0, 0.24)",
    elevation: 28,
  },
  shadow64: {
    ambient: { x: 0, y: 0, blur: 8, color: "rgba(0, 0, 0, 0.12)" },
    key: { x: 0, y: 32, blur: 64, color: "rgba(0, 0, 0, 0.24)" },
    combined: "0 0 8px rgba(0, 0, 0, 0.12), 0 32px 64px rgba(0, 0, 0, 0.24)",
    elevation: 64,
  },
};

export const M3Motion = {
  durationShort1: 50,
  durationShort2: 100,
  durationShort3: 150,
  durationShort4: 200,
  durationMedium1: 250,
  durationMedium2: 300,
  durationMedium3: 350,
  durationMedium4: 400,
  durationLong1: 450,
  durationLong2: 500,
  durationLong3: 550,
  durationLong4: 600,
  durationExtraLong1: 700,
  durationExtraLong2: 800,
  durationExtraLong3: 900,
  durationExtraLong4: 1000,
  easingStandard: { x1: 0.2, y1: 0, x2: 0, y2: 1 },
  easingStandardDecelerate: { x1: 0, y1: 0, x2: 0, y2: 1 },
  easingStandardAccelerate: { x1: 0.3, y1: 0, x2: 1, y2: 1 },
  easingEmphasized: { x1: 0.2, y1: 0, x2: 0, y2: 1 },
  easingEmphasizedDecelerate: { x1: 0.05, y1: 0.7, x2: 0.1, y2: 1 },
  easingEmphasizedAccelerate: { x1: 0.3, y1: 0, x2: 0.8, y2: 0.15 },
  easingLegacy: { x1: 0.4, y1: 0, x2: 0.2, y2: 1 },
  easingLegacyDecelerate: { x1: 0, y1: 0, x2: 0.2, y2: 1 },
  easingLegacyAccelerate: { x1: 0.4, y1: 0, x2: 1, y2: 1 },
  easingLinear: { x1: 0, y1: 0, x2: 1, y2: 1 },
};

export const M3Elevation = {
  level0: { elevation: 0, shadowOpacity: 0 },
  level1: { elevation: 1, shadowOpacity: 0.05 },
  level2: { elevation: 3, shadowOpacity: 0.08 },
  level3: { elevation: 6, shadowOpacity: 0.11 },
  level4: { elevation: 8, shadowOpacity: 0.12 },
  level5: { elevation: 12, shadowOpacity: 0.14 },
};

export const M3Shape = {
  cornerNone: 0,
  cornerExtraSmall: 4,
  cornerSmall: 8,
  cornerMedium: 12,
  cornerLarge: 16,
  cornerExtraLarge: 28,
  cornerFull: 9999,
};

export const FontFamily = Platform.select({
  ios: {
    regular: "System",
    medium: "System",
    semibold: "System",
    bold: "System",
  },
  android: {
    regular: "Roboto",
    medium: "Roboto-Medium",
    semibold: "Roboto-Medium",
    bold: "Roboto-Bold",
  },
  default: {
    regular: "Segoe UI, system-ui, -apple-system, BlinkMacSystemFont, Roboto, sans-serif",
    medium: "Segoe UI, system-ui, -apple-system, BlinkMacSystemFont, Roboto, sans-serif",
    semibold: "Segoe UI Semibold, system-ui, -apple-system, BlinkMacSystemFont, Roboto, sans-serif",
    bold: "Segoe UI Bold, system-ui, -apple-system, BlinkMacSystemFont, Roboto, sans-serif",
  },
});

export const Fonts = Platform.select({
  ios: {
    sans: "System",
    serif: "Georgia",
    mono: "Menlo",
  },
  android: {
    sans: "Roboto",
    serif: "Georgia",
    mono: "monospace",
  },
  default: {
    sans: "Segoe UI, system-ui, -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    mono: "Consolas, SFMono-Regular, Menlo, Monaco, monospace",
  },
  web: {
    sans: "Segoe UI, system-ui, -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    mono: "Consolas, SFMono-Regular, Menlo, Monaco, monospace",
  },
});

export const Elevation = {
  level0: 0,
  level1: 2,
  level2: 4,
  level3: 8,
  level4: 16,
  level5: 24,
};

export const EQPresets = ['Rock', 'Pop', 'Jazz', 'Classical', 'Balanced'] as const;
export const SoundModes = ['Cinema', 'Music', 'Sports', '360 Reality'] as const;

export const Motion = {
  easing: {
    emphasized: "cubic-bezier(0.2, 0.0, 0, 1.0)",
    emphasizedDecelerate: "cubic-bezier(0.05, 0.7, 0.1, 1.0)",
    emphasizedAccelerate: "cubic-bezier(0.3, 0.0, 0.8, 0.15)",
    standard: "cubic-bezier(0.2, 0.0, 0, 1.0)",
    standardDecelerate: "cubic-bezier(0, 0, 0, 1)",
    standardAccelerate: "cubic-bezier(0.3, 0, 1, 1)",
    fluent: "cubic-bezier(0.33, 0, 0.67, 1)",
    fluentDecelerate: "cubic-bezier(0.1, 0.9, 0.2, 1)",
    fluentAccelerate: "cubic-bezier(0.9, 0.1, 1, 0.2)",
    easeOut: "ease-out",
    easeInOut: "ease-in-out",
  },
  duration: {
    ultraFast: 50,
    fast: 100,
    normal: 200,
    slow: 300,
    slower: 400,
    faster: 100,
    ultraSlow: 500,
    short1: 50,
    short2: 100,
    short3: 150,
    short4: 200,
    medium1: 250,
    medium2: 300,
    medium3: 350,
    medium4: 400,
    long1: 450,
    long2: 500,
  },
  spring: {
    damping: 20,
    stiffness: 300,
    mass: 1,
  },
  slowSpring: {
    damping: 25,
    stiffness: 200,
    mass: 1,
  },
};

export const ModeStyles = {
  listen: {
    overlayOpacityDark: 0.3,
    overlayOpacityLight: 0.2,
  },
  studio: {
    overlayOpacityDark: 0.5,
    overlayOpacityLight: 0.4,
  },
};
